/* ============ ENGLISCH – Klasse 4 & 5 ============ */
const TESTS_ENGLISH = [

/* ---------------- KLASSE 4 ---------------- */
{ id:'e4-first', grade:4, subject:'english', icon:'🌈',
  title:{de:'Colours, Numbers & Animals',ru:'Цвета, числа и животные',en:'Colours, Numbers & Animals'},
  desc:{de:'Die wichtigsten ersten Wörter',ru:'Самые важные первые слова',en:'The most important first words'},
  qs:[
    {t:'match', q:'Verbinde die Farben mit der deutschen Bedeutung:', tr:{ru:'Соедини цвета с переводом:',en:'Match the colours:'},
      pairs:[['red','rot'],['blue','blau'],['green','grün'],['yellow','gelb']], h:'engVocab', pts:4},
    {t:'mc', q:'Wie heißt die Zahl 7 auf Englisch?', tr:{ru:'Как по-английски число 7?',en:'What is 7 in English?'}, opts:['seven','six','eleven','seventeen'], a:0, h:'engVocab', pts:1},
    {t:'mc', q:'„twelve" bedeutet ...', tr:{ru:'„twelve" – это ...',en:'"twelve" means ...'}, opts:['12','20','2','11'], a:0, h:'engVocab', pts:1},
    {t:'mc', q:'Wie heißt „der Hund" auf Englisch?', tr:{ru:'Как по-английски «собака»?',en:'What is "der Hund" in English?'}, opts:['dog','cat','duck','frog'], a:0, h:'engVocab', pts:1},
    {t:'mc', q:'Welches Tier ist „der Vogel"?', tr:{ru:'Какое слово значит «птица»?',en:'Which animal is "der Vogel"?'}, opts:['bird','bear','bee','bat'], a:0, h:'engVocab', pts:1},
    {t:'match', q:'Verbinde die Zahlen:', tr:{ru:'Соедини числа:',en:'Match the numbers:'},
      pairs:[['three','3'],['five','5'],['eight','8'],['ten','10']], h:'engVocab', pts:4},
    {t:'mc', q:'What colour is the sun?', tr:{ru:'Какого цвета солнце?',en:'What colour is the sun?'}, opts:['yellow','blue','green','black'], a:0, h:'engVocab', pts:1},
    {t:'mc', q:'Wie heißt „das Pferd" auf Englisch?', tr:{ru:'Как по-английски «лошадь»?',en:'What is "das Pferd" in English?'}, opts:['horse','house','mouse','hedgehog'], a:0, h:'engVocab', pts:1},
  ]},

{ id:'e4-family', grade:4, subject:'english', icon:'👨‍👩‍👧‍👦',
  title:{de:'My Family & Me',ru:'Моя семья и я',en:'My Family & Me'},
  desc:{de:'Familie, Körper und sich vorstellen',ru:'Семья, тело и рассказ о себе',en:'Family, body and introducing yourself'},
  qs:[
    {t:'match', q:'Verbinde die Familienwörter:', tr:{ru:'Соедини слова о семье:',en:'Match the family words:'},
      pairs:[['mother','Mutter'],['father','Vater'],['sister','Schwester'],['brother','Bruder']], h:'engVocab', pts:4},
    {t:'mc', q:'Wie stellst du dich auf Englisch vor?', tr:{ru:'Как представиться по-английски?',en:'How do you introduce yourself?'},
      opts:['My name is Tom.','My name have Tom.','I name Tom.'], a:0, h:'engVocab', pts:1},
    {t:'mc', q:'„How old are you?" – Welche Antwort passt?', tr:{ru:'„How old are you?" – какой ответ подходит?',en:'"How old are you?" – which answer fits?'},
      opts:['I am eleven.','I have eleven.','I is eleven.'], a:0, h:'engTobe', pts:1},
    {t:'match', q:'Verbinde die Körperteile:', tr:{ru:'Соедини части тела:',en:'Match the body parts:'},
      pairs:[['head','Kopf'],['arm','Arm'],['leg','Bein'],['hand','Hand']], h:'engVocab', pts:4},
    {t:'mc', q:'Was sagst du morgens zur Begrüßung?', tr:{ru:'Как поздороваться утром?',en:'What do you say in the morning?'},
      opts:['Good morning!','Good night!','Goodbye!'], a:0, h:'engVocab', pts:1},
    {t:'mc', q:'Wie heißt „die Großmutter" auf Englisch?', tr:{ru:'Как по-английски «бабушка»?',en:'What is "die Großmutter" in English?'}, opts:['grandma','grandpa','aunt','uncle'], a:0, h:'engVocab', pts:1},
  ]},

{ id:'e4-school', grade:4, subject:'english', icon:'🎒',
  title:{de:'School & Hobbies',ru:'Школа и хобби',en:'School & Hobbies'},
  desc:{de:'Schulsachen, Wochentage und Freizeit',ru:'Школьные вещи, дни недели и досуг',en:'School things, weekdays and free time'},
  qs:[
    {t:'match', q:'Verbinde die Schulsachen:', tr:{ru:'Соедини школьные предметы:',en:'Match the school things:'},
      pairs:[['pen','Stift'],['book','Buch'],['chair','Stuhl'],['table','Tisch']], h:'engVocab', pts:4},
    {t:'mc', q:'Wie sagst du: „Ich spiele gern Fußball"?', tr:{ru:'Как сказать: «Я люблю играть в футбол»?',en:'How do you say: "I like playing football"?'},
      opts:['I like playing football.','I like play football.','I am like football.'], a:0, h:'engVocab', pts:1},
    {t:'mc', q:'Wie heißt „Montag" auf Englisch?', tr:{ru:'Как по-английски «понедельник»?',en:'What is "Montag" in English?'}, opts:['Monday','Sunday','Money-day','Mayday'], a:0, h:'engVocab', pts:1},
    {t:'mc', q:'What day comes after Monday?', tr:{ru:'Какой день после понедельника?',en:'What day comes after Monday?'}, opts:['Tuesday','Thursday','Sunday','Friday'], a:0, h:'engVocab', pts:1},
    {t:'match', q:'Verbinde die Hobbys:', tr:{ru:'Соедини хобби:',en:'Match the hobbies:'},
      pairs:[['swimming','Schwimmen'],['reading','Lesen'],['singing','Singen'],['dancing','Tanzen']], h:'engVocab', pts:4},
    {t:'mc', q:'Wie heißt „die Schultasche" auf Englisch?', tr:{ru:'Как по-английски «школьный рюкзак»?',en:'What is "die Schultasche" in English?'}, opts:['school bag','school back','school box'], a:0, h:'engVocab', pts:1},
  ]},

/* ---------------- KLASSE 5 ---------------- */
{ id:'e5-tobe', grade:5, subject:'english', icon:'🅰️',
  title:{de:'to be – am, is, are',ru:'Глагол to be – am, is, are',en:'to be – am, is, are'},
  desc:{de:'Das wichtigste Verb der englischen Sprache',ru:'Самый важный глагол английского языка',en:'The most important English verb'},
  qs:[
    {t:'mc', q:'I ___ eleven years old.', tr:{ru:'Выбери форму: I ___ eleven years old.',en:'Choose: I ___ eleven years old.'}, opts:['am','is','are'], a:0, noshuffle:true, h:'engTobe', pts:1},
    {t:'mc', q:'She ___ my best friend.', tr:{ru:'Выбери форму: She ___ my best friend.',en:'Choose: She ___ my best friend.'}, opts:['is','am','are'], a:0, noshuffle:true, h:'engTobe', pts:1},
    {t:'mc', q:'We ___ in class 5a.', tr:{ru:'Выбери форму: We ___ in class 5a.',en:'Choose: We ___ in class 5a.'}, opts:['are','is','am'], a:0, noshuffle:true, h:'engTobe', pts:1},
    {t:'mc', q:'My parents ___ at home.', tr:{ru:'Выбери форму: My parents ___ at home.',en:'Choose: My parents ___ at home.'}, opts:['are','is','am'], a:0, noshuffle:true, h:'engTobe', pts:1},
    {t:'mc', q:'The dog ___ in the garden.', tr:{ru:'Выбери форму: The dog ___ in the garden.',en:'Choose: The dog ___ in the garden.'}, opts:['is','are','am'], a:0, noshuffle:true, h:'engTobe', pts:1},
    {t:'mc', q:'You ___ very funny!', tr:{ru:'Выбери форму: You ___ very funny!',en:'Choose: You ___ very funny!'}, opts:['are','is','am'], a:0, noshuffle:true, h:'engTobe', pts:1},
    {t:'mc', q:'It ___ cold today.', tr:{ru:'Выбери форму: It ___ cold today.',en:'Choose: It ___ cold today.'}, opts:['is','are','am'], a:0, noshuffle:true, h:'engTobe', pts:1},
    {t:'mc', q:'Welche Frage ist richtig?', tr:{ru:'Какой вопрос правильный?',en:'Which question is correct?'}, opts:['Are you tired?','You are tired?','Is you tired?'], a:0, h:'engTobe', pts:1},
    {t:'mc', q:'Verneine richtig: „He is happy." →', tr:{ru:'Правильное отрицание: „He is happy." →',en:'Negate correctly: "He is happy." →'}, opts:['He is not happy.','He not is happy.','He is no happy.'], a:0, h:'engTobe', pts:1},
    {t:'mc', q:'Tom and I ___ brothers.', tr:{ru:'Выбери форму: Tom and I ___ brothers.',en:'Choose: Tom and I ___ brothers.'}, opts:['are','is','am'], a:0, noshuffle:true, h:'engTobe', pts:1},
  ]},

{ id:'e5-have', grade:5, subject:'english', icon:'🎁',
  title:{de:'have got & Plural',ru:'have got и множественное число',en:'have got & Plurals'},
  desc:{de:'have/has got und die Mehrzahl bilden',ru:'have/has got и множественное число',en:'have/has got and building plurals'},
  qs:[
    {t:'mc', q:'I ___ a new bike.', tr:{ru:'Выбери: I ___ a new bike.',en:'Choose: I ___ a new bike.'}, opts:['have got','has got'], a:0, noshuffle:true, h:'engHave', pts:1},
    {t:'mc', q:'She ___ two cats.', tr:{ru:'Выбери: She ___ two cats.',en:'Choose: She ___ two cats.'}, opts:['has got','have got'], a:0, noshuffle:true, h:'engHave', pts:1},
    {t:'mc', q:'My brother ___ a computer.', tr:{ru:'Выбери: My brother ___ a computer.',en:'Choose: My brother ___ a computer.'}, opts:['has got','have got'], a:0, noshuffle:true, h:'engHave', pts:1},
    {t:'mc', q:'We ___ a big garden.', tr:{ru:'Выбери: We ___ a big garden.',en:'Choose: We ___ a big garden.'}, opts:['have got','has got'], a:0, noshuffle:true, h:'engHave', pts:1},
    {t:'mc', q:'Welche Frage ist richtig?', tr:{ru:'Какой вопрос правильный?',en:'Which question is correct?'}, opts:['Has she got a dog?','Have she got a dog?','She has got a dog?'], a:0, h:'engHave', pts:1},
    {t:'text', q:'Bilde die Mehrzahl: one cat → two ...', tr:{ru:'Множественное число: one cat → two ...',en:'Plural: one cat → two ...'}, a:['cats'], h:'engPlural', pts:1},
    {t:'text', q:'Bilde die Mehrzahl: one box → two ...', tr:{ru:'Множественное число: one box → two ...',en:'Plural: one box → two ...'}, a:['boxes'], h:'engPlural', pts:1},
    {t:'text', q:'Bilde die Mehrzahl: one baby → two ...', tr:{ru:'Множественное число: one baby → two ...',en:'Plural: one baby → two ...'}, a:['babies'], h:'engPlural', pts:1},
    {t:'text', q:'Bilde die Mehrzahl: one child → two ...', tr:{ru:'Множественное число: one child → two ...',en:'Plural: one child → two ...'}, a:['children'], h:'engPlural', pts:1},
    {t:'text', q:'Bilde die Mehrzahl: one mouse → two ...', tr:{ru:'Множественное число: one mouse → two ...',en:'Plural: one mouse → two ...'}, a:['mice'], h:'engPlural', pts:1},
  ]},

{ id:'e5-simple', grade:5, subject:'english', icon:'🔁',
  title:{de:'Simple Present',ru:'Simple Present',en:'Simple Present'},
  desc:{de:'He, she, it – das s muss mit!',ru:'He, she, it – не забудь про s!',en:'He, she, it – add the s!'},
  qs:[
    {t:'mc', q:'She ___ football every day.', tr:{ru:'Выбери: She ___ football every day.',en:'Choose: She ___ football every day.'}, opts:['plays','play','playing'], a:0, h:'engSimplePres', pts:1},
    {t:'mc', q:'I ___ to school at 8 o’clock.', tr:{ru:'Выбери: I ___ to school at 8 o’clock.',en:'Choose: I ___ to school at 8 o’clock.'}, opts:['go','goes','going'], a:0, h:'engSimplePres', pts:1},
    {t:'mc', q:'My dad ___ in an office.', tr:{ru:'Выбери: My dad ___ in an office.',en:'Choose: My dad ___ in an office.'}, opts:['works','work','worked'], a:0, h:'engSimplePres', pts:1},
    {t:'mc', q:'We ___ TV in the evening.', tr:{ru:'Выбери: We ___ TV in the evening.',en:'Choose: We ___ TV in the evening.'}, opts:['watch','watches','watching'], a:0, h:'engSimplePres', pts:1},
    {t:'mc', q:'Verneine richtig: „He plays tennis." →', tr:{ru:'Правильное отрицание: „He plays tennis." →',en:'Negate correctly: "He plays tennis." →'},
      opts:['He doesn’t play tennis.','He doesn’t plays tennis.','He don’t play tennis.'], a:0, h:'engSimplePres', pts:1},
    {t:'mc', q:'Welche Frage ist richtig?', tr:{ru:'Какой вопрос правильный?',en:'Which question is correct?'},
      opts:['Does she like pizza?','Does she likes pizza?','Do she like pizza?'], a:0, h:'engSimplePres', pts:1},
    {t:'mc', q:'The cat ___ milk.', tr:{ru:'Выбери: The cat ___ milk.',en:'Choose: The cat ___ milk.'}, opts:['likes','like','liking'], a:0, h:'engSimplePres', pts:1},
    {t:'mc', q:'They ___ in Paderborn.', tr:{ru:'Выбери: They ___ in Paderborn.',en:'Choose: They ___ in Paderborn.'}, opts:['live','lives','living'], a:0, h:'engSimplePres', pts:1},
    {t:'mc', q:'___ you speak English?', tr:{ru:'Выбери: ___ you speak English?',en:'Choose: ___ you speak English?'}, opts:['Do','Does','Are'], a:0, noshuffle:true, h:'engSimplePres', pts:1},
    {t:'mc', q:'My sister ___ her homework after lunch.', tr:{ru:'Выбери: My sister ___ her homework after lunch.',en:'Choose: My sister ___ her homework after lunch.'}, opts:['does','do','doing'], a:0, h:'engSimplePres', pts:1},
  ]},

{ id:'e5-questions', grade:5, subject:'english', icon:'❔',
  title:{de:'Question Words',ru:'Вопросительные слова',en:'Question Words'},
  desc:{de:'What, where, who, when, why, how',ru:'What, where, who, when, why, how',en:'What, where, who, when, why, how'},
  qs:[
    {t:'mc', q:'„___ is your name?" – „My name is Alex."', tr:{ru:'„___ is your name?" – „My name is Alex."',en:'"___ is your name?" – "My name is Alex."'}, opts:['What','Where','Who','When'], a:0, h:'engQuestions', pts:1},
    {t:'mc', q:'„___ do you live?" – „In Paderborn."', tr:{ru:'„___ do you live?" – „In Paderborn."',en:'"___ do you live?" – "In Paderborn."'}, opts:['Where','What','Who','Why'], a:0, h:'engQuestions', pts:1},
    {t:'mc', q:'„___ is your teacher?" – „Mrs Miller."', tr:{ru:'„___ is your teacher?" – „Mrs Miller."',en:'"___ is your teacher?" – "Mrs Miller."'}, opts:['Who','What','Where','When'], a:0, h:'engQuestions', pts:1},
    {t:'mc', q:'„___ is your birthday?" – „In May."', tr:{ru:'„___ is your birthday?" – „In May."',en:'"___ is your birthday?" – "In May."'}, opts:['When','Who','What','Where'], a:0, h:'engQuestions', pts:1},
    {t:'mc', q:'„___ old are you?" – „I am eleven."', tr:{ru:'„___ old are you?" – „I am eleven."',en:'"___ old are you?" – "I am eleven."'}, opts:['How','What','Who','Where'], a:0, h:'engQuestions', pts:1},
    {t:'mc', q:'„___ are you sad?" – „Because I lost my pen."', tr:{ru:'„___ are you sad?" – „Because I lost my pen."',en:'"___ are you sad?" – "Because I lost my pen."'}, opts:['Why','When','Where','What'], a:0, h:'engQuestions', pts:1},
    {t:'mc', q:'„___ many brothers have you got?" – „Two."', tr:{ru:'„___ many brothers have you got?" – „Two."',en:'"___ many brothers have you got?" – "Two."'}, opts:['How','What','Who','Where'], a:0, h:'engQuestions', pts:1},
    {t:'mc', q:'Welche Wortstellung ist richtig?', tr:{ru:'Какой порядок слов правильный?',en:'Which word order is correct?'},
      opts:['Where do you play football?','Where you do play football?','Where play you do football?'], a:0, h:'engQuestions', pts:1},
  ]},

{ id:'e5-vocab', grade:5, subject:'english', icon:'📚',
  title:{de:'Vocabulary Power',ru:'Сила словарного запаса',en:'Vocabulary Power'},
  desc:{de:'Schule, Familie, Freizeit – und a oder an',ru:'Школа, семья, досуг – и a или an',en:'School, family, free time – and a or an'},
  qs:[
    {t:'match', q:'Verbinde die Schulfächer:', tr:{ru:'Соедини школьные предметы:',en:'Match the school subjects:'},
      pairs:[['maths','Mathematik'],['history','Geschichte'],['science','Naturwissenschaften'],['art','Kunst']], h:'engVocab', pts:4},
    {t:'match', q:'Verbinde die Freizeitwörter:', tr:{ru:'Соедини слова о досуге:',en:'Match the free-time words:'},
      pairs:[['ride a bike','Fahrrad fahren'],['listen to music','Musik hören'],['meet friends','Freunde treffen'],['do sports','Sport machen']], h:'engVocab', pts:4},
    {t:'mc', q:'a oder an? „___ apple"', tr:{ru:'a или an? „___ apple"',en:'a or an? "___ apple"'}, opts:['an','a'], a:0, noshuffle:true, h:'engArticles', pts:1},
    {t:'mc', q:'a oder an? „___ dog"', tr:{ru:'a или an? „___ dog"',en:'a or an? "___ dog"'}, opts:['a','an'], a:0, noshuffle:true, h:'engArticles', pts:1},
    {t:'mc', q:'a oder an? „___ elephant"', tr:{ru:'a или an? „___ elephant"',en:'a or an? "___ elephant"'}, opts:['an','a'], a:0, noshuffle:true, h:'engArticles', pts:1},
    {t:'mc', q:'Wie heißt „das Klassenzimmer" auf Englisch?', tr:{ru:'Как по-английски «классная комната»?',en:'What is "das Klassenzimmer" in English?'}, opts:['classroom','class house','school room'], a:0, h:'engVocab', pts:1},
    {t:'mc', q:'„break" bedeutet in der Schule ...', tr:{ru:'„break" в школе значит ...',en:'"break" at school means ...'}, opts:['Pause','Hausaufgabe','Zeugnis'], a:0, h:'engVocab', pts:1},
    {t:'mc', q:'Wie heißt „die Turnhalle" auf Englisch?', tr:{ru:'Как по-английски «спортзал»?',en:'What is "die Turnhalle" in English?'}, opts:['gym','swimming pool','playground'], a:0, h:'engVocab', pts:1},
  ]},

/* ---------- Erweiterung: mehr Englisch-Tests ---------- */
{ id:'e4-food', grade:4, subject:'english', icon:'🍎',
  title:{de:'Food & Drinks',ru:'Еда и напитки',en:'Food & Drinks'},
  desc:{de:'Essen und Trinken auf Englisch',ru:'Еда и напитки по-английски',en:'Food and drinks in English'},
  qs:[
    {t:'match', q:'Verbinde das Essen:', tr:{ru:'Соедини еду:',en:'Match the food:'},
      pairs:[['apple','Apfel'],['bread','Brot'],['milk','Milch'],['cheese','Käse']], h:'engVocab', pts:4},
    {t:'mc', q:'Wie heißt „das Wasser" auf Englisch?', tr:{ru:'Как по-английски «вода»?',en:'What is "das Wasser" in English?'}, opts:['water','juice','tea'], a:0, h:'engVocab', pts:1},
    {t:'mc', q:'What do you eat for breakfast?', tr:{ru:'Что едят на завтрак? (выбери разумный ответ)',en:'What do you eat for breakfast?'}, opts:['cereal and toast','a football','my school bag'], a:0, h:'engVocab', pts:1},
    {t:'mc', q:'Wie sagst du: „Ich mag Pizza"?', tr:{ru:'Как сказать: «Я люблю пиццу»?',en:'How do you say "Ich mag Pizza"?'}, opts:['I like pizza.','I am pizza.','I pizza like.'], a:0, h:'engVocab', pts:1},
    {t:'mc', q:'Wie sagst du: „Ich mag keinen Käse"?', tr:{ru:'Как сказать: «Я не люблю сыр»?',en:'How do you say "Ich mag keinen Käse"?'}, opts:['I don’t like cheese.','I no like cheese.','I like no cheese.'], a:0, h:'engVocab', pts:1},
    {t:'match', q:'Verbinde die Getränke und Süßes:', tr:{ru:'Соедини напитки и сладкое:',en:'Match drinks and sweets:'},
      pairs:[['orange juice','Orangensaft'],['ice cream','Eis'],['cake','Kuchen'],['sweets','Süßigkeiten']], h:'engVocab', pts:4},
    {t:'mc', q:'„I am hungry" bedeutet:', tr:{ru:'„I am hungry" значит:',en:'"I am hungry" means:'}, opts:['Ich habe Hunger.','Ich habe Durst.','Ich bin müde.'], a:0, h:'engVocab', pts:1},
  ]},

{ id:'e4-year', grade:4, subject:'english', icon:'🌦️',
  title:{de:'Seasons, Months & Weather',ru:'Времена года, месяцы, погода',en:'Seasons, Months & Weather'},
  desc:{de:'Jahreszeiten, Monate und das Wetter',ru:'Времена года, месяцы и погода',en:'Seasons, months and the weather'},
  qs:[
    {t:'match', q:'Verbinde die Jahreszeiten:', tr:{ru:'Соедини времена года:',en:'Match the seasons:'},
      pairs:[['spring','Frühling'],['summer','Sommer'],['autumn','Herbst'],['winter','Winter']], h:'engVocab', pts:4},
    {t:'mc', q:'Which is the first month of the year?', tr:{ru:'Какой первый месяц года?',en:'Which is the first month of the year?'}, opts:['January','February','December'], a:0, h:'engTime', pts:1},
    {t:'mc', q:'Wie heißt „der Regen" auf Englisch?', tr:{ru:'Как по-английски «дождь»?',en:'What is "der Regen" in English?'}, opts:['rain','snow','wind'], a:0, h:'engVocab', pts:1},
    {t:'mc', q:'„It is snowing" bedeutet:', tr:{ru:'„It is snowing" значит:',en:'"It is snowing" means:'}, opts:['Es schneit.','Es regnet.','Die Sonne scheint.'], a:0, h:'engVocab', pts:1},
    {t:'num', q:'How many months has a year?', tr:{ru:'Сколько месяцев в году?',en:'How many months has a year?'}, a:12, h:'engTime', pts:1},
    {t:'match', q:'Verbinde das Wetter:', tr:{ru:'Соедини погоду:',en:'Match the weather:'},
      pairs:[['sunny','sonnig'],['cloudy','wolkig'],['windy','windig'],['rainy','regnerisch']], h:'engVocab', pts:4},
    {t:'mc', q:'In which season do you build a snowman?', tr:{ru:'В какое время года лепят снеговика?',en:'In which season do you build a snowman?'}, opts:['in winter','in summer','in spring'], a:0, h:'engVocab', pts:1},
  ]},

{ id:'e5-can', grade:5, subject:'english', icon:'💪',
  title:{de:'can & can’t',ru:'can и can’t',en:'can & can’t'},
  desc:{de:'Sagen, was man kann und nicht kann',ru:'Говорим, что умеем и не умеем',en:'Saying what you can and can’t do'},
  qs:[
    {t:'mc', q:'„Ich kann schwimmen." heißt auf Englisch:', tr:{ru:'«Я умею плавать» по-английски:',en:'"Ich kann schwimmen" in English:'}, opts:['I can swim.','I can to swim.','I can swimming.'], a:0, h:'engCan', pts:1},
    {t:'mc', q:'She ___ ride a bike.', tr:{ru:'Выбери: She ___ ride a bike.',en:'Choose: She ___ ride a bike.'}, opts:['can','cans','can to'], a:0, h:'engCan', pts:1},
    {t:'mc', q:'Verneine richtig: „He can fly." →', tr:{ru:'Правильное отрицание: „He can fly." →',en:'Negate: "He can fly." →'}, opts:['He can’t fly.','He don’t can fly.','He no can fly.'], a:0, h:'engCan', pts:1},
    {t:'mc', q:'Welche Frage ist richtig?', tr:{ru:'Какой вопрос правильный?',en:'Which question is correct?'}, opts:['Can you help me?','You can help me?','Do you can help me?'], a:0, h:'engCan', pts:1},
    {t:'mc', q:'„Can you sing?" – Welche Antwort ist richtig?', tr:{ru:'„Can you sing?" – какой ответ правильный?',en:'"Can you sing?" – which answer is correct?'}, opts:['Yes, I can.','Yes, I sing.','Yes, I am.'], a:0, h:'engCan', pts:1},
    {t:'mc', q:'The baby ___ walk yet.', tr:{ru:'Выбери: The baby ___ walk yet. (ещё не умеет)',en:'Choose: The baby ___ walk yet.'}, opts:['can’t','can','doesn’t can'], a:0, h:'engCan', pts:1},
    {t:'mc', q:'Nach „can" steht das Verb ...', tr:{ru:'После „can" глагол стоит ...',en:'After "can" the verb is ...'}, opts:['in der Grundform (ohne s)','immer mit s','in der ing-Form'], a:0, h:'engCan', pts:1},
    {t:'mc', q:'A fish ___ swim, but it ___ climb.', tr:{ru:'Выбери: A fish ___ swim, but it ___ climb.',en:'Choose: A fish ___ swim, but it ___ climb.'}, opts:['can / can’t','can’t / can','can / can'], a:0, h:'engCan', pts:1},
  ]},

{ id:'e5-time', grade:5, subject:'english', icon:'⏰',
  title:{de:'Telling the Time',ru:'Который час?',en:'Telling the Time'},
  desc:{de:'Uhrzeit, Tage und Monate auf Englisch',ru:'Время, дни и месяцы по-английски',en:'Time, days and months in English'},
  qs:[
    {t:'mc', q:'3:00 – What time is it?', tr:{ru:'3:00 – который час?',en:'3:00 – What time is it?'}, opts:['It’s three o’clock.','It’s three hours.','It’s clock three.'], a:0, h:'engTime', pts:1},
    {t:'mc', q:'4:30 – What time is it?', tr:{ru:'4:30 – который час?',en:'4:30 – What time is it?'}, opts:['It’s half past four.','It’s half to four.','It’s four half.'], a:0, h:'engTime', pts:1},
    {t:'mc', q:'7:15 – What time is it?', tr:{ru:'7:15 – который час?',en:'7:15 – What time is it?'}, opts:['It’s quarter past seven.','It’s quarter to seven.','It’s seven and quarter.'], a:0, h:'engTime', pts:1},
    {t:'mc', q:'Wie fragt man nach der Uhrzeit?', tr:{ru:'Как спросить, который час?',en:'How do you ask for the time?'}, opts:['What time is it?','How много time?','When is the clock?'], a:0, h:'engTime', pts:1},
    {t:'match', q:'Verbinde die Wochentage:', tr:{ru:'Соедини дни недели:',en:'Match the days:'},
      pairs:[['Wednesday','Mittwoch'],['Thursday','Donnerstag'],['Saturday','Samstag'],['Sunday','Sonntag']], h:'engTime', pts:4},
    {t:'mc', q:'Which month comes after June?', tr:{ru:'Какой месяц после июня?',en:'Which month comes after June?'}, opts:['July','May','August'], a:0, h:'engTime', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Im Englischen schreibt man Wochentage groß: Monday."', tr:{ru:'Верно ли: в английском дни недели пишутся с большой буквы?',en:'True or false: English weekdays are capitalised?'}, a:true, h:'engTime', pts:1},
    {t:'num', q:'How many days has a week?', tr:{ru:'Сколько дней в неделе?',en:'How many days has a week?'}, a:7, h:'engTime', pts:1},
  ]},

{ id:'e5-reading', grade:5, subject:'english', icon:'📖',
  title:{de:'Reading: My New School',ru:'Чтение: Моя новая школа',en:'Reading: My New School'},
  desc:{de:'Dein erster englischer Lesetext!',ru:'Твой первый текст на английском!',en:'Your first English reading text!'},
  reading:{title:'My New School',
    text:`Hello! My name is Ben and I am eleven years old. I live in Paderborn with my mum, my dad and my little sister Mia. She is seven.
My new school is great. My favourite subjects are maths and sport. We have six lessons every day. School starts at eight o'clock and finishes at one o'clock.
In the big break I play football with my friends Tom and Leo. After school I do my homework. Then I can play computer games for thirty minutes – but only when my homework is finished!
On Saturdays I have no school. I ride my bike in the park or I visit my grandma. She makes the best pancakes in the world!`},
  qs:[
    {t:'num', q:'How old is Ben?', tr:{ru:'Сколько лет Бену?',en:'How old is Ben?'}, a:11, h:'lesen', pts:1},
    {t:'mc', q:'Who is Mia?', tr:{ru:'Кто такая Миа?',en:'Who is Mia?'}, opts:['Ben’s little sister','Ben’s mum','Ben’s friend'], a:0, h:'lesen', pts:1},
    {t:'mc', q:'What are Ben’s favourite subjects?', tr:{ru:'Какие любимые предметы у Бена?',en:'What are Ben’s favourite subjects?'}, opts:['maths and sport','English and art','music and history'], a:0, h:'lesen', pts:1},
    {t:'mc', q:'When does school start?', tr:{ru:'Когда начинаются уроки?',en:'When does school start?'}, opts:['at eight o’clock','at one o’clock','at seven o’clock'], a:0, h:'lesen', pts:1},
    {t:'mc', q:'What does Ben do in the big break?', tr:{ru:'Что Бен делает на большой перемене?',en:'What does Ben do in the big break?'}, opts:['He plays football.','He does his homework.','He rides his bike.'], a:0, h:'lesen', pts:1},
    {t:'num', q:'How many minutes can Ben play computer games?', tr:{ru:'Сколько минут Бен может играть в компьютер?',en:'How many minutes can Ben play computer games?'}, a:30, h:'lesen', pts:1},
    {t:'tf', q:'True or false?\n„Ben has school on Saturdays."', tr:{ru:'Верно или неверно: «У Бена есть школа по субботам».',en:'True or false: "Ben has school on Saturdays."'}, a:false, h:'lesen', pts:1},
    {t:'mc', q:'Who makes the best pancakes?', tr:{ru:'Кто печёт лучшие блины?',en:'Who makes the best pancakes?'}, opts:['Ben’s grandma','Ben’s mum','Ben’s sister'], a:0, h:'lesen', pts:1},
  ]},
];
