/* ============ SACHUNTERRICHT (Kl. 4) · BIOLOGIE & ERDKUNDE (Kl. 5) ============ */
const TESTS_OTHER = [

/* ---------------- SACHUNTERRICHT KLASSE 4 ---------------- */
{ id:'s4-deutschland', grade:4, subject:'sach', icon:'🗺️',
  title:{de:'Deutschland & Karten',ru:'Германия и карты',en:'Germany & Maps'},
  desc:{de:'Bundesländer, Hauptstädte, Himmelsrichtungen',ru:'Федеральные земли, столицы, стороны света',en:'Federal states, capitals, compass directions'},
  qs:[
    {t:'num', q:'Wie viele Bundesländer hat Deutschland?', tr:{ru:'Сколько федеральных земель в Германии?',en:'How many federal states does Germany have?'}, a:16, h:'sachMap', pts:1},
    {t:'mc', q:'Wie heißt die Hauptstadt von Deutschland?', tr:{ru:'Столица Германии?',en:'What is the capital of Germany?'}, opts:['Berlin','München','Hamburg','Köln'], a:0, h:'sachMap', pts:1},
    {t:'mc', q:'In welchem Bundesland liegt Paderborn?', tr:{ru:'В какой федеральной земле находится Падерборн?',en:'In which state is Paderborn?'}, opts:['Nordrhein-Westfalen','Bayern','Hessen','Niedersachsen'], a:0, h:'sachMap', pts:1},
    {t:'mc', q:'Wie heißt die Landeshauptstadt von Nordrhein-Westfalen?', tr:{ru:'Столица земли Северный Рейн-Вестфалия?',en:'What is the state capital of NRW?'}, opts:['Düsseldorf','Köln','Dortmund','Essen'], a:0, h:'sachMap', pts:1},
    {t:'mc', q:'Wo ist auf einer Karte normalerweise NORDEN?', tr:{ru:'Где на карте обычно СЕВЕР?',en:'Where is NORTH usually on a map?'}, opts:['oben','unten','rechts','links'], a:0, h:'sachMap', pts:1},
    {t:'mc', q:'Die Sonne geht auf im ...', tr:{ru:'Солнце восходит на ...',en:'The sun rises in the ...'}, opts:['Osten','Westen','Norden','Süden'], a:0, h:'sachMap', pts:1},
    {t:'mc', q:'Wohin zeigt die Kompassnadel immer?', tr:{ru:'Куда всегда показывает стрелка компаса?',en:'Where does a compass needle always point?'}, opts:['nach Norden','nach Süden','zur Sonne','nach Hause'], a:0, h:'sachMap', pts:1},
    {t:'mc', q:'Merksatz für die Himmelsrichtungen im Uhrzeigersinn:', tr:{ru:'Запоминалка сторон света по часовой стрелке:',en:'Memory aid for compass directions clockwise:'},
      opts:['Nie Ohne Seife Waschen','Nur Oben Sind Wolken','Nach Osten Schnell Wandern'], a:0, h:'sachMap', pts:1},
    {t:'match', q:'Verbinde Bundesland und Landeshauptstadt:', tr:{ru:'Соедини землю и её столицу:',en:'Match state and capital:'},
      pairs:[['Nordrhein-Westfalen','Düsseldorf'],['Bayern','München'],['Hessen','Wiesbaden'],['Niedersachsen','Hannover']], h:'sachMap', pts:4},
  ]},

{ id:'s4-wasser', grade:4, subject:'sach', icon:'💧',
  title:{de:'Wasser & Wetter',ru:'Вода и погода',en:'Water & Weather'},
  desc:{de:'Wasserkreislauf und die drei Zustände',ru:'Круговорот воды и три состояния',en:'Water cycle and the three states'},
  qs:[
    {t:'mc', q:'Wie nennt man es, wenn Wasser durch die Sonne zu Wasserdampf wird?', tr:{ru:'Как называется превращение воды в пар под солнцем?',en:'What is it called when the sun turns water into vapour?'},
      opts:['Verdunstung','Niederschlag','Kondensation'], a:0, h:'sachWater', pts:1},
    {t:'mc', q:'Was entsteht, wenn Wasserdampf in der Höhe abkühlt?', tr:{ru:'Что образуется, когда пар охлаждается наверху?',en:'What forms when vapour cools high up?'},
      opts:['Wolken','Blitze','Wind'], a:0, h:'sachWater', pts:1},
    {t:'mc', q:'Regen, Schnee und Hagel nennt man ...', tr:{ru:'Дождь, снег и град называют ...',en:'Rain, snow and hail are called ...'},
      opts:['Niederschlag','Verdunstung','Nebel'], a:0, h:'sachWater', pts:1},
    {t:'mc', q:'Welche drei Zustände hat Wasser?', tr:{ru:'Какие три состояния у воды?',en:'What are the three states of water?'},
      opts:['fest, flüssig, gasförmig','kalt, warm, heiß','klar, trüb, salzig'], a:0, h:'sachWater', pts:1},
    {t:'num', q:'Bei wie viel Grad Celsius gefriert Wasser?', tr:{ru:'При скольких градусах Цельсия замерзает вода?',en:'At how many degrees Celsius does water freeze?'}, a:0, unit:'°C', h:'sachWater', pts:1},
    {t:'num', q:'Bei wie viel Grad Celsius kocht Wasser?', tr:{ru:'При скольких градусах Цельсия кипит вода?',en:'At how many degrees Celsius does water boil?'}, a:100, unit:'°C', h:'sachWater', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Eis ist der feste Zustand von Wasser."', tr:{ru:'Верно ли: лёд – твёрдое состояние воды?',en:'True or false: ice is the solid state of water?'}, a:true, h:'sachWater', pts:1},
    {t:'mc', q:'In welcher Reihenfolge läuft der Wasserkreislauf ab?', tr:{ru:'В каком порядке идёт круговорот воды?',en:'In which order does the water cycle run?'},
      opts:['Verdunstung → Wolken → Regen → Fluss','Regen → Verdunstung → Fluss → Wolken','Wolken → Verdunstung → Regen → Fluss'], a:0, h:'sachWater', pts:1},
  ]},

{ id:'s4-strom', grade:4, subject:'sach', icon:'⚡',
  title:{de:'Strom & Energie',ru:'Электричество и энергия',en:'Electricity & Energy'},
  desc:{de:'Stromkreis, Leiter und Sicherheit',ru:'Электрическая цепь, проводники и безопасность',en:'Circuit, conductors and safety'},
  qs:[
    {t:'mc', q:'Wann leuchtet das Lämpchen in einem Stromkreis?', tr:{ru:'Когда горит лампочка в цепи?',en:'When does the bulb light up in a circuit?'},
      opts:['Wenn der Stromkreis geschlossen ist.','Wenn der Stromkreis offen ist.','Wenn die Batterie fehlt.'], a:0, h:'sachStrom', pts:1},
    {t:'mc', q:'Welcher Stoff leitet Strom?', tr:{ru:'Какой материал проводит ток?',en:'Which material conducts electricity?'},
      opts:['Kupfer (Metall)','Holz','Gummi','Glas'], a:0, h:'sachStrom', pts:1},
    {t:'mc', q:'Welcher Stoff leitet KEINEN Strom (Isolator)?', tr:{ru:'Какой материал НЕ проводит ток (изолятор)?',en:'Which material does NOT conduct (insulator)?'},
      opts:['Kunststoff','Eisen','Kupfer','Silber'], a:0, h:'sachStrom', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Man darf mit Strom aus der Steckdose experimentieren."', tr:{ru:'Верно ли: можно экспериментировать с током из розетки?',en:'True or false: you may experiment with mains electricity?'}, a:false, h:'sachStrom', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Wasser und Strom zusammen sind gefährlich."', tr:{ru:'Верно ли: вода и электричество вместе опасны?',en:'True or false: water and electricity together are dangerous?'}, a:true, h:'sachStrom', pts:1},
    {t:'mc', q:'Was gehört in einen einfachen Stromkreis?', tr:{ru:'Что входит в простую электрическую цепь?',en:'What belongs in a simple circuit?'},
      opts:['Batterie, Kabel, Lämpchen','Wasser, Rohr, Hahn','Sonne, Spiegel, Glas'], a:0, h:'sachStrom', pts:1},
    {t:'mc', q:'Womit kann man einen Stromkreis ein- und ausschalten?', tr:{ru:'Чем можно включать и выключать цепь?',en:'What switches a circuit on and off?'},
      opts:['mit einem Schalter','mit einem Magneten','mit einer Schere'], a:0, h:'sachStrom', pts:1},
  ]},

{ id:'s4-verkehr', grade:4, subject:'sach', icon:'🚲',
  title:{de:'Verkehr & Fahrradprüfung',ru:'Дорожное движение и велоэкзамен',en:'Traffic & Bike Test'},
  desc:{de:'Alles für die Radfahrprüfung!',ru:'Всё для экзамена по вождению велосипеда!',en:'Everything for the cycling test!'},
  qs:[
    {t:'mc', q:'Welche Farbe hat das Licht VORNE am Fahrrad?', tr:{ru:'Какого цвета фара СПЕРЕДИ велосипеда?',en:'What colour is the FRONT bike light?'}, opts:['weiß','rot','gelb','blau'], a:0, h:'sachVerkehr', pts:1},
    {t:'mc', q:'Welche Farbe hat das Licht HINTEN am Fahrrad?', tr:{ru:'Какого цвета фонарь СЗАДИ велосипеда?',en:'What colour is the REAR bike light?'}, opts:['rot','weiß','grün','gelb'], a:0, h:'sachVerkehr', pts:1},
    {t:'num', q:'Wie viele unabhängige Bremsen braucht ein verkehrssicheres Fahrrad?', tr:{ru:'Сколько независимых тормозов нужно безопасному велосипеду?',en:'How many independent brakes does a road-safe bike need?'}, a:2, h:'sachVerkehr', pts:1},
    {t:'mc', q:'Was machst du, BEVOR du mit dem Rad links abbiegst?', tr:{ru:'Что нужно сделать ПЕРЕД поворотом налево?',en:'What do you do BEFORE turning left?'},
      opts:['Umschauen und Handzeichen geben','Klingeln und schnell fahren','Die Augen schließen'], a:0, h:'sachVerkehr', pts:1},
    {t:'mc', q:'An einer Kreuzung ohne Schilder gilt:', tr:{ru:'На перекрёстке без знаков действует правило:',en:'At a crossing without signs the rule is:'},
      opts:['rechts vor links','links vor rechts','der Schnellere zuerst'], a:0, h:'sachVerkehr', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Ein Helm schützt deinen Kopf – du solltest ihn immer tragen."', tr:{ru:'Верно ли: шлем защищает голову, его нужно носить всегда?',en:'True or false: a helmet protects your head – always wear it?'}, a:true, h:'sachVerkehr', pts:1},
    {t:'mc', q:'Was gehört zu einem verkehrssicheren Fahrrad?', tr:{ru:'Что входит в безопасный велосипед?',en:'What belongs to a road-safe bike?'},
      opts:['Klingel und Reflektoren','Musikbox und Hupe','Regenschirm und Spiegel'], a:0, h:'sachVerkehr', pts:1},
    {t:'mc', q:'Auf welcher Seite der Straße fährst du mit dem Fahrrad?', tr:{ru:'По какой стороне дороги едут на велосипеде?',en:'On which side of the road do you cycle?'}, opts:['rechts','links','in der Mitte'], a:0, h:'sachVerkehr', pts:1},
  ]},

{ id:'s4-koerper', grade:4, subject:'sach', icon:'🫀',
  title:{de:'Mein Körper & Ernährung',ru:'Моё тело и питание',en:'My Body & Nutrition'},
  desc:{de:'Herz, Lunge, Skelett und gesundes Essen',ru:'Сердце, лёгкие, скелет и здоровая еда',en:'Heart, lungs, skeleton and healthy food'},
  qs:[
    {t:'mc', q:'Welches Organ pumpt das Blut durch den Körper?', tr:{ru:'Какой орган качает кровь по телу?',en:'Which organ pumps blood through the body?'}, opts:['das Herz','die Lunge','der Magen','das Gehirn'], a:0, h:'sachBody', pts:1},
    {t:'mc', q:'Womit atmen wir?', tr:{ru:'Чем мы дышим?',en:'What do we breathe with?'}, opts:['mit der Lunge','mit dem Herzen','mit dem Magen'], a:0, h:'sachBody', pts:1},
    {t:'mc', q:'Was schützt unser Gehirn?', tr:{ru:'Что защищает наш мозг?',en:'What protects our brain?'}, opts:['der Schädel','die Rippen','die Wirbelsäule'], a:0, h:'sachBody', pts:1},
    {t:'mc', q:'Wovon sollst du am MEISTEN essen und trinken?', tr:{ru:'Чего нужно есть и пить БОЛЬШЕ всего?',en:'What should you eat and drink MOST?'},
      opts:['Wasser, Obst und Gemüse','Süßigkeiten und Chips','Limonade und Eis'], a:0, h:'sachBody', pts:1},
    {t:'mc', q:'Wie oft solltest du dir die Zähne putzen?', tr:{ru:'Как часто нужно чистить зубы?',en:'How often should you brush your teeth?'},
      opts:['mindestens zweimal am Tag','einmal in der Woche','nur nach Süßigkeiten'], a:0, h:'sachBody', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Das Skelett stützt unseren Körper."', tr:{ru:'Верно ли: скелет поддерживает наше тело?',en:'True or false: the skeleton supports our body?'}, a:true, h:'sachBody', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Die Rippen schützen Herz und Lunge."', tr:{ru:'Верно ли: рёбра защищают сердце и лёгкие?',en:'True or false: the ribs protect heart and lungs?'}, a:true, h:'sachBody', pts:1},
    {t:'match', q:'Verbinde Organ und Aufgabe:', tr:{ru:'Соедини орган и его функцию:',en:'Match organ and job:'},
      pairs:[['Herz','pumpt das Blut'],['Lunge','atmet ein und aus'],['Magen','verdaut das Essen'],['Gehirn','denkt und steuert']], h:'sachBody', pts:4},
  ]},

/* ---------------- BIOLOGIE KLASSE 5 ---------------- */
{ id:'b5-hundkatze', grade:5, subject:'bio', icon:'🐕',
  title:{de:'Säugetiere: Hund & Katze',ru:'Млекопитающие: собака и кошка',en:'Mammals: Dog & Cat'},
  desc:{de:'Das erste große Bio-Thema in Klasse 5',ru:'Первая большая тема биологии в 5 классе',en:'The first big biology topic in grade 5'},
  qs:[
    {t:'mc', q:'Was machen alle Säugetier-Mütter mit ihren Jungen?', tr:{ru:'Что делают все мамы-млекопитающие с детёнышами?',en:'What do all mammal mothers do with their young?'},
      opts:['Sie säugen sie mit Milch.','Sie legen Eier.','Sie lassen sie allein.'], a:0, h:'bioMammal', pts:1},
    {t:'mc', q:'Der Hund stammt vom ... ab.', tr:{ru:'Собака произошла от ...',en:'The dog descends from the ...'}, opts:['Wolf','Fuchs','Bären','Schakal'], a:0, h:'bioMammal', pts:1},
    {t:'mc', q:'Welcher Sinn ist beim Hund besonders gut?', tr:{ru:'Какое чувство у собаки особенно развито?',en:'Which sense is especially good in dogs?'},
      opts:['der Geruchssinn (Nase)','der Geschmackssinn','der Tastsinn'], a:0, h:'bioMammal', pts:1},
    {t:'mc', q:'Was kann die Katze mit ihren Krallen machen?', tr:{ru:'Что кошка может делать со своими когтями?',en:'What can a cat do with its claws?'},
      opts:['einziehen','abwerfen','färben'], a:0, h:'bioMammal', pts:1},
    {t:'mc', q:'Wie jagt die Katze?', tr:{ru:'Как охотится кошка?',en:'How does a cat hunt?'},
      opts:['lautlos anschleichen und springen','laut bellend hinterherrennen','in der Gruppe hetzen'], a:0, h:'bioMammal', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Der Hund ist ein Rudeltier."', tr:{ru:'Верно ли: собака – стайное животное?',en:'True or false: the dog is a pack animal?'}, a:true, h:'bioMammal', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Säugetiere sind wechselwarm."', tr:{ru:'Верно ли: млекопитающие холоднокровные?',en:'True or false: mammals are cold-blooded?'}, a:false, h:'bioMammal', pts:1},
    {t:'mc', q:'Wie nennt man die Zähne, mit denen der Hund Fleisch reißt?', tr:{ru:'Как называются зубы, которыми собака рвёт мясо?',en:'What are the teeth called that a dog tears meat with?'},
      opts:['Fang- und Reißzähne','Milchzähne','Mahlzähne'], a:0, h:'bioMammal', pts:1},
    {t:'match', q:'Verbinde Tier und Eigenschaft:', tr:{ru:'Соедини животное и признак:',en:'Match animal and feature:'},
      pairs:[['Hund','sehr gute Nase'],['Katze','einziehbare Krallen'],['Wolf','Vorfahre des Hundes'],['Kätzchen','wird mit Milch gesäugt']], h:'bioMammal', pts:4},
  ]},

{ id:'b5-skelett', grade:5, subject:'bio', icon:'🦴',
  title:{de:'Skelett & Muskeln',ru:'Скелет и мышцы',en:'Skeleton & Muscles'},
  desc:{de:'Knochen, Gelenke und Muskelpaare',ru:'Кости, суставы и пары мышц',en:'Bones, joints and muscle pairs'},
  qs:[
    {t:'mc', q:'Was schützt der Schädel?', tr:{ru:'Что защищает череп?',en:'What does the skull protect?'}, opts:['das Gehirn','das Herz','den Magen'], a:0, h:'bioSkeleton', pts:1},
    {t:'mc', q:'Was schützt der Brustkorb (die Rippen)?', tr:{ru:'Что защищает грудная клетка?',en:'What does the ribcage protect?'}, opts:['Herz und Lunge','Gehirn und Augen','Magen und Darm'], a:0, h:'bioSkeleton', pts:1},
    {t:'mc', q:'Wie heißt die bewegliche Knochenkette in deinem Rücken?', tr:{ru:'Как называется подвижная цепь костей в спине?',en:'What is the flexible chain of bones in your back called?'},
      opts:['Wirbelsäule','Beckenknochen','Schlüsselbein'], a:0, h:'bioSkeleton', pts:1},
    {t:'mc', q:'Was verbindet Knochen beweglich miteinander?', tr:{ru:'Что подвижно соединяет кости?',en:'What connects bones so they can move?'},
      opts:['Gelenke','Haare','Adern'], a:0, h:'bioSkeleton', pts:1},
    {t:'mc', q:'Muskeln arbeiten immer ...', tr:{ru:'Мышцы всегда работают ...',en:'Muscles always work ...'},
      opts:['in Paaren (Beuger und Strecker)','allein','nur nachts'], a:0, h:'bioSkeleton', pts:1},
    {t:'mc', q:'Wie heißt der Beugemuskel im Oberarm?', tr:{ru:'Как называется мышца-сгибатель плеча?',en:'What is the flexor muscle in the upper arm called?'},
      opts:['Bizeps','Trizeps','Quadrizeps'], a:0, h:'bioSkeleton', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Die Wirbelsäule schützt das Rückenmark."', tr:{ru:'Верно ли: позвоночник защищает спинной мозг?',en:'True or false: the spine protects the spinal cord?'}, a:true, h:'bioSkeleton', pts:1},
    {t:'match', q:'Verbinde Knochen und Aufgabe:', tr:{ru:'Соедини кость и её функцию:',en:'Match bone and job:'},
      pairs:[['Schädel','schützt das Gehirn'],['Rippen','schützen Herz und Lunge'],['Wirbelsäule','trägt den Rücken'],['Gelenk','macht Bewegung möglich']], h:'bioSkeleton', pts:4},
  ]},

{ id:'b5-wirbel', grade:5, subject:'bio', icon:'🐟',
  title:{de:'Die 5 Wirbeltierklassen',ru:'5 классов позвоночных',en:'The 5 Vertebrate Classes'},
  desc:{de:'Fische, Amphibien, Reptilien, Vögel, Säugetiere',ru:'Рыбы, амфибии, рептилии, птицы, млекопитающие',en:'Fish, amphibians, reptiles, birds, mammals'},
  qs:[
    {t:'mc', q:'Womit atmen Fische?', tr:{ru:'Чем дышат рыбы?',en:'What do fish breathe with?'}, opts:['mit Kiemen','mit Lungen','mit der Haut'], a:0, h:'bioVertebrates', pts:1},
    {t:'mc', q:'Welches Tier ist ein Amphib?', tr:{ru:'Какое животное – амфибия?',en:'Which animal is an amphibian?'}, opts:['der Frosch','die Schlange','der Adler','der Delfin'], a:0, h:'bioVertebrates', pts:1},
    {t:'mc', q:'Welche Tiergruppe hat Federn?', tr:{ru:'У какой группы животных есть перья?',en:'Which animal group has feathers?'}, opts:['Vögel','Reptilien','Säugetiere','Fische'], a:0, h:'bioVertebrates', pts:1},
    {t:'mc', q:'„Wechselwarm" bedeutet:', tr:{ru:'«Холоднокровный» означает:',en:'"Cold-blooded" means:'},
      opts:['Die Körpertemperatur hängt von der Umgebung ab.','Das Tier ist immer kalt.','Das Tier friert nie.'], a:0, h:'bioVertebrates', pts:1},
    {t:'mc', q:'Welches Tier ist ein Säugetier, obwohl es im Wasser lebt?', tr:{ru:'Какое животное – млекопитающее, хотя живёт в воде?',en:'Which animal is a mammal although it lives in water?'},
      opts:['der Delfin','der Hai','der Lachs','der Tintenfisch'], a:0, h:'bioVertebrates', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Reptilien wie Schlangen sind wechselwarm."', tr:{ru:'Верно ли: рептилии, например змеи, холоднокровные?',en:'True or false: reptiles like snakes are cold-blooded?'}, a:true, h:'bioVertebrates', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Vögel bringen lebende Junge zur Welt."', tr:{ru:'Верно ли: птицы рождают живых детёнышей?',en:'True or false: birds give birth to live young?'}, a:false, h:'bioVertebrates', pts:1},
    {t:'match', q:'Verbinde Tier und Wirbeltierklasse:', tr:{ru:'Соедини животное и класс позвоночных:',en:'Match animal and vertebrate class:'},
      pairs:[['Forelle','Fisch'],['Frosch','Amphib'],['Eidechse','Reptil'],['Amsel','Vogel']], h:'bioVertebrates', pts:4},
  ]},

{ id:'b5-ernaehrung', grade:5, subject:'bio', icon:'🥗',
  title:{de:'Gesunde Ernährung',ru:'Здоровое питание',en:'Healthy Eating'},
  desc:{de:'Nährstoffe und die Ernährungspyramide',ru:'Питательные вещества и пирамида питания',en:'Nutrients and the food pyramid'},
  qs:[
    {t:'mc', q:'Welcher Nährstoff liefert schnelle Energie?', tr:{ru:'Какое вещество даёт быструю энергию?',en:'Which nutrient gives quick energy?'},
      opts:['Kohlenhydrate (Brot, Nudeln)','Vitamine','Wasser'], a:0, h:'bioFood', pts:1},
    {t:'mc', q:'Wofür braucht der Körper Eiweiß (Protein)?', tr:{ru:'Для чего телу нужен белок?',en:'What does the body need protein for?'},
      opts:['als Baustoff für Muskeln und Zellen','nur zum Schwitzen','für die Haarfarbe'], a:0, h:'bioFood', pts:1},
    {t:'mc', q:'In welchen Lebensmitteln stecken viele Vitamine?', tr:{ru:'В каких продуктах много витаминов?',en:'Which foods contain many vitamins?'},
      opts:['Obst und Gemüse','Chips und Cola','Gummibärchen'], a:0, h:'bioFood', pts:1},
    {t:'mc', q:'Was solltest du am meisten trinken?', tr:{ru:'Что нужно пить больше всего?',en:'What should you drink most?'},
      opts:['Wasser','Limonade','Energy-Drinks'], a:0, h:'bioFood', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Süßigkeiten stehen ganz oben in der Ernährungspyramide – man soll nur wenig davon essen."', tr:{ru:'Верно ли: сладости на вершине пирамиды – их нужно есть мало?',en:'True or false: sweets are at the top of the pyramid – eat only a little?'}, a:true, h:'bioFood', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Milchprodukte enthalten Kalzium für starke Knochen."', tr:{ru:'Верно ли: молочные продукты содержат кальций для крепких костей?',en:'True or false: dairy contains calcium for strong bones?'}, a:true, h:'bioFood', pts:1},
    {t:'match', q:'Verbinde Nährstoff und Beispiel:', tr:{ru:'Соедини вещество и пример:',en:'Match nutrient and example:'},
      pairs:[['Kohlenhydrate','Nudeln'],['Eiweiß','Eier'],['Fett','Butter'],['Vitamine','Apfel']], h:'bioFood', pts:4},
    {t:'mc', q:'Ein gesundes Pausenbrot enthält am besten ...', tr:{ru:'Здоровый школьный перекус – это ...',en:'A healthy school snack contains ...'},
      opts:['Vollkornbrot, Gemüse und Obst','Schokoriegel und Chips','nur Kaugummi'], a:0, h:'bioFood', pts:1},
  ]},

/* ---------------- ERDKUNDE KLASSE 5 ---------------- */
{ id:'g5-welt', grade:5, subject:'geo', icon:'🌍',
  title:{de:'Kontinente & Ozeane',ru:'Континенты и океаны',en:'Continents & Oceans'},
  desc:{de:'Eine Reise um die ganze Welt',ru:'Путешествие вокруг света',en:'A journey around the world'},
  qs:[
    {t:'num', q:'Wie viele Kontinente gibt es?', tr:{ru:'Сколько на Земле континентов?',en:'How many continents are there?'}, a:7, h:'geoWorld', pts:1},
    {t:'mc', q:'Welcher Kontinent ist der GRÖSSTE?', tr:{ru:'Какой континент самый большой?',en:'Which continent is the LARGEST?'}, opts:['Asien','Afrika','Europa','Australien'], a:0, h:'geoWorld', pts:1},
    {t:'mc', q:'Welcher Ozean ist der größte?', tr:{ru:'Какой океан самый большой?',en:'Which ocean is the largest?'}, opts:['Pazifik','Atlantik','Indischer Ozean','Nordpolarmeer'], a:0, h:'geoWorld', pts:1},
    {t:'mc', q:'Auf welchem Kontinent liegt Deutschland?', tr:{ru:'На каком континенте находится Германия?',en:'On which continent is Germany?'}, opts:['Europa','Asien','Afrika','Nordamerika'], a:0, h:'geoWorld', pts:1},
    {t:'mc', q:'Welcher Kontinent ist fast ganz mit Eis bedeckt?', tr:{ru:'Какой континент почти весь покрыт льдом?',en:'Which continent is almost completely covered in ice?'}, opts:['Antarktis','Afrika','Australien','Südamerika'], a:0, h:'geoWorld', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Europa und Asien bilden zusammen die Landmasse Eurasien."', tr:{ru:'Верно ли: Европа и Азия вместе образуют Евразию?',en:'True or false: Europe and Asia together form Eurasia?'}, a:true, h:'geoWorld', pts:1},
    {t:'mc', q:'Zwischen Europa und Amerika liegt der ...', tr:{ru:'Между Европой и Америкой находится ...',en:'Between Europe and America lies the ...'}, opts:['Atlantik','Pazifik','Indische Ozean'], a:0, h:'geoWorld', pts:1},
    {t:'match', q:'Verbinde Tier und Kontinent, auf dem es wild lebt:', tr:{ru:'Соедини животное и континент, где оно живёт в природе:',en:'Match animal and its wild continent:'},
      pairs:[['Löwe','Afrika'],['Känguru','Australien'],['Pinguin','Antarktis'],['Braunbär','Europa']], h:'geoWorld', pts:4},
  ]},

{ id:'g5-deutschland', grade:5, subject:'geo', icon:'🇩🇪',
  title:{de:'Deutschland & NRW',ru:'Германия и NRW',en:'Germany & NRW'},
  desc:{de:'Dein Land, dein Bundesland, deine Stadt Paderborn',ru:'Твоя страна, твоя земля, твой город Падерборн',en:'Your country, your state, your city Paderborn'},
  qs:[
    {t:'num', q:'Wie viele Nachbarländer hat Deutschland?', tr:{ru:'Сколько стран граничит с Германией?',en:'How many neighbouring countries does Germany have?'}, a:9, h:'geoGermany', pts:1},
    {t:'mc', q:'Welches Land ist KEIN Nachbar von Deutschland?', tr:{ru:'Какая страна НЕ граничит с Германией?',en:'Which country is NOT a neighbour of Germany?'},
      opts:['Spanien','Frankreich','Polen','Österreich'], a:0, h:'geoGermany', pts:1},
    {t:'mc', q:'Wie heißt der höchste Berg Deutschlands?', tr:{ru:'Самая высокая гора Германии?',en:'What is Germany’s highest mountain?'},
      opts:['Zugspitze','Brocken','Feldberg','Watzmann'], a:0, h:'geoGermany', pts:1},
    {t:'mc', q:'Welcher große Fluss fließt durch Nordrhein-Westfalen?', tr:{ru:'Какая крупная река течёт через NRW?',en:'Which big river flows through NRW?'},
      opts:['der Rhein','die Donau','die Elbe','die Oder'], a:0, h:'geoGermany', pts:1},
    {t:'mc', q:'Was ist das Besondere an der Pader in Paderborn?', tr:{ru:'Чем особенна река Падер в Падерборне?',en:'What is special about the Pader in Paderborn?'},
      opts:['Sie ist der kürzeste Fluss Deutschlands.','Sie ist der längste Fluss Deutschlands.','Sie ist der tiefste Fluss Europas.'], a:0, h:'geoGermany', pts:1},
    {t:'mc', q:'Die größte Stadt in NRW ist ...', tr:{ru:'Крупнейший город NRW – это ...',en:'The biggest city in NRW is ...'}, opts:['Köln','Düsseldorf','Paderborn','Bonn'], a:0, h:'geoGermany', pts:1},
    {t:'mc', q:'In welchem Teil von NRW liegt Paderborn?', tr:{ru:'В какой части NRW находится Падерборн?',en:'In which part of NRW is Paderborn?'},
      opts:['Ostwestfalen','Ruhrgebiet','Rheinland','Sauerland'], a:0, h:'geoGermany', pts:1},
    {t:'match', q:'Verbinde Stadt und Fluss:', tr:{ru:'Соедини город и реку:',en:'Match city and river:'},
      pairs:[['Köln','Rhein'],['Hamburg','Elbe'],['Paderborn','Pader'],['Bremen','Weser']], h:'geoGermany', pts:4},
  ]},

{ id:'g5-karte', grade:5, subject:'geo', icon:'🧭',
  title:{de:'Karte, Kompass & Maßstab',ru:'Карта, компас и масштаб',en:'Map, Compass & Scale'},
  desc:{de:'Wie ein echter Entdecker Karten lesen',ru:'Читаем карты как настоящий исследователь',en:'Reading maps like a real explorer'},
  qs:[
    {t:'mc', q:'Was erklärt die LEGENDE einer Karte?', tr:{ru:'Что объясняет легенда карты?',en:'What does a map LEGEND explain?'},
      opts:['die Kartenzeichen und Farben','die Geschichte des Landes','das Wetter von morgen'], a:0, h:'geoMapSkills', pts:1},
    {t:'mc', q:'Maßstab 1:100.000 – Wie weit ist 1 cm auf der Karte in Wirklichkeit?', tr:{ru:'Масштаб 1:100.000 – сколько в реальности 1 см на карте?',en:'Scale 1:100,000 – how far is 1 cm on the map in reality?'},
      opts:['1 km','100 km','10 m','100 m'], a:0, h:'geoMapSkills', pts:1},
    {t:'num', q:'Maßstab 1:100.000: Auf der Karte sind es 5 cm.\nWie viele km sind es in Wirklichkeit?', tr:{ru:'Масштаб 1:100.000: на карте 5 см. Сколько км в реальности?',en:'Scale 1:100,000: 5 cm on the map. How many km in reality?'},
      a:5, unit:'km', h:'geoMapSkills', pts:2},
    {t:'mc', q:'Welche Himmelsrichtung liegt zwischen Norden und Osten?', tr:{ru:'Какая сторона света между севером и востоком?',en:'Which direction lies between north and east?'},
      opts:['Nordosten','Nordwesten','Südosten'], a:0, h:'geoMapSkills', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Auf einer Karte ist Norden fast immer oben."', tr:{ru:'Верно ли: на карте север почти всегда сверху?',en:'True or false: on a map north is almost always at the top?'}, a:true, h:'geoMapSkills', pts:1},
    {t:'mc', q:'Womit findest du im Wald ohne Handy die Himmelsrichtung?', tr:{ru:'Чем найти стороны света в лесу без телефона?',en:'How do you find directions in a forest without a phone?'},
      opts:['mit einem Kompass','mit einem Lineal','mit einer Lupe'], a:0, h:'geoMapSkills', pts:1},
    {t:'mc', q:'Je GRÖSSER die Maßstabszahl (z. B. 1:1.000.000), desto ...', tr:{ru:'Чем больше число масштаба (напр. 1:1.000.000), тем ...',en:'The BIGGER the scale number (e.g. 1:1,000,000), the ...'},
      opts:['größer ist das gezeigte Gebiet (weniger Details)','kleiner ist das gezeigte Gebiet (mehr Details)'], a:0, h:'geoMapSkills', pts:1},
  ]},

/* ---------- Erweiterung ---------- */
{ id:'s4-zeit', grade:4, subject:'sach', icon:'📅',
  title:{de:'Kalender & Jahreszeiten',ru:'Календарь и времена года',en:'Calendar & Seasons'},
  desc:{de:'Monate, Tage, Schaltjahr und die Jahresuhr',ru:'Месяцы, дни, високосный год',en:'Months, days, leap year and the yearly cycle'},
  qs:[
    {t:'num', q:'Wie viele Monate hat ein Jahr?', tr:{ru:'Сколько месяцев в году?',en:'How many months has a year?'}, a:12, h:'kalender', pts:1},
    {t:'num', q:'Wie viele Tage hat ein normales Jahr?', tr:{ru:'Сколько дней в обычном году?',en:'How many days has a normal year?'}, a:365, h:'kalender', pts:1},
    {t:'num', q:'Wie viele Tage hat ein Schaltjahr?', tr:{ru:'Сколько дней в високосном году?',en:'How many days has a leap year?'}, a:366, h:'kalender', pts:1},
    {t:'mc', q:'Welcher Monat hat nur 28 Tage (im Schaltjahr 29)?', tr:{ru:'В каком месяце только 28 дней (29 в високосном)?',en:'Which month has only 28 days (29 in a leap year)?'}, opts:['Februar','April','November'], a:0, h:'kalender', pts:1},
    {t:'mc', q:'Welcher Monat hat 31 Tage?', tr:{ru:'В каком месяце 31 день?',en:'Which month has 31 days?'}, opts:['Juli','April','Juni','September'], a:0, h:'kalender', pts:1},
    {t:'mc', q:'In welcher Jahreszeit beginnt das Schuljahr in Deutschland?', tr:{ru:'В какое время года начинается учебный год в Германии?',en:'In which season does the German school year start?'}, opts:['im Sommer/Spätsommer','im Winter','im Frühling'], a:0, h:'kalender', pts:1},
    {t:'num', q:'Wie viele Stunden hat ein Tag?', tr:{ru:'Сколько часов в сутках?',en:'How many hours has a day?'}, a:24, h:'kalender', pts:1},
    {t:'match', q:'Verbinde Jahreszeit und Monat:', tr:{ru:'Соедини время года и месяц:',en:'Match season and month:'},
      pairs:[['Winter','Januar'],['Frühling','Mai'],['Sommer','Juli'],['Herbst','Oktober']], h:'kalender', pts:4},
  ]},

{ id:'b5-voegel', grade:5, subject:'bio', icon:'🐦',
  title:{de:'Vögel',ru:'Птицы',en:'Birds'},
  desc:{de:'Gebaut zum Fliegen: Federn, Schnäbel, Zugvögel',ru:'Созданы для полёта: перья, клювы, перелётные птицы',en:'Built to fly: feathers, beaks, migratory birds'},
  qs:[
    {t:'mc', q:'Was haben NUR Vögel?', tr:{ru:'Что есть ТОЛЬКО у птиц?',en:'What do ONLY birds have?'}, opts:['Federn','Flügel','zwei Beine','Eier'], a:0, h:'bioBirds', pts:1},
    {t:'mc', q:'Was haben Vögel statt Zähnen?', tr:{ru:'Что у птиц вместо зубов?',en:'What do birds have instead of teeth?'}, opts:['einen Schnabel','starke Lippen','Mahlplatten'], a:0, h:'bioBirds', pts:1},
    {t:'mc', q:'Warum sind Vogelknochen besonders?', tr:{ru:'Чем особенны кости птиц?',en:'Why are bird bones special?'}, opts:['Sie sind hohl und leicht.','Sie sind aus Metall.','Sie sind besonders schwer.'], a:0, h:'bioBirds', pts:1},
    {t:'mc', q:'Was machen ZUGVÖGEL im Herbst?', tr:{ru:'Что делают перелётные птицы осенью?',en:'What do migratory birds do in autumn?'}, opts:['Sie fliegen in den warmen Süden.','Sie halten Winterschlaf.','Sie bauen ein Winternest.'], a:0, h:'bioBirds', pts:1},
    {t:'mc', q:'Welcher Vogel ist ein STANDVOGEL (bleibt im Winter hier)?', tr:{ru:'Какая птица оседлая (остаётся на зиму)?',en:'Which bird is a resident (stays in winter)?'}, opts:['die Amsel','der Storch','die Schwalbe'], a:0, h:'bioBirds', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Vögel sind gleichwarme Tiere."', tr:{ru:'Верно ли: птицы – теплокровные животные?',en:'True or false: birds are warm-blooded?'}, a:true, h:'bioBirds', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Alle Vögel können fliegen."', tr:{ru:'Верно ли: все птицы умеют летать?',en:'True or false: all birds can fly?'}, a:false, h:'bioBirds', pts:1},
    {t:'match', q:'Verbinde Schnabelform und Nahrung:', tr:{ru:'Соедини форму клюва и питание:',en:'Match beak shape and food:'},
      pairs:[['spitzer Schnabel','Insekten'],['dicker Kegelschnabel','Körner'],['Hakenschnabel','Fleisch (Greifvogel)'],['langer Schnabel','Würmer im Boden']], h:'bioBirds', pts:4},
  ]},

{ id:'g5-europa', grade:5, subject:'geo', icon:'🇪🇺',
  title:{de:'Europa entdecken',ru:'Открываем Европу',en:'Discovering Europe'},
  desc:{de:'Länder, Hauptstädte und Rekorde Europas',ru:'Страны, столицы и рекорды Европы',en:'Countries, capitals and records of Europe'},
  qs:[
    {t:'match', q:'Verbinde Land und Hauptstadt:', tr:{ru:'Соедини страну и столицу:',en:'Match country and capital:'},
      pairs:[['Frankreich','Paris'],['Italien','Rom'],['Spanien','Madrid'],['Polen','Warschau']], h:'geoEurope', pts:4},
    {t:'mc', q:'Wie heißt die Hauptstadt von Österreich?', tr:{ru:'Столица Австрии?',en:'What is the capital of Austria?'}, opts:['Wien','Salzburg','Zürich'], a:0, h:'geoEurope', pts:1},
    {t:'mc', q:'Welches Gebirge trennt Deutschland/Österreich von Italien?', tr:{ru:'Какие горы отделяют Германию/Австрию от Италии?',en:'Which mountains separate Germany/Austria from Italy?'}, opts:['die Alpen','die Pyrenäen','der Ural'], a:0, h:'geoEurope', pts:1},
    {t:'mc', q:'Der längste Fluss Europas ist ...', tr:{ru:'Самая длинная река Европы – ...',en:'The longest river of Europe is ...'}, opts:['die Wolga','der Rhein','die Donau'], a:0, h:'geoEurope', pts:1},
    {t:'mc', q:'Mit welchem Geld bezahlt man in Deutschland und vielen EU-Ländern?', tr:{ru:'Какими деньгами платят в Германии и многих странах ЕС?',en:'Which money is used in Germany and many EU countries?'}, opts:['mit dem Euro','mit dem Dollar','mit dem Pfund'], a:0, h:'geoEurope', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Europa ist der größte Kontinent der Erde."', tr:{ru:'Верно ли: Европа – самый большой континент Земли?',en:'True or false: Europe is the largest continent?'}, a:false, h:'geoEurope', pts:1},
    {t:'mc', q:'Welches Land ist Deutschlands Nachbar im Westen?', tr:{ru:'Какая страна – западный сосед Германии?',en:'Which country is Germany’s western neighbour?'}, opts:['Frankreich','Polen','Tschechien'], a:0, h:'geoEurope', pts:1},
    {t:'match', q:'Verbinde Land und bekanntes Wahrzeichen:', tr:{ru:'Соедини страну и известный символ:',en:'Match country and famous landmark:'},
      pairs:[['Frankreich','Eiffelturm'],['Italien','Schiefer Turm von Pisa'],['England','Big Ben'],['Griechenland','Akropolis']], h:'geoEurope', pts:4},
  ]},
];
