/* ============ DEUTSCH – Klasse 4 & 5 ============ */
const WA = ['Nomen','Verb','Adjektiv','Artikel','Pronomen'];
const ZF4 = ['Präsens','Präteritum','Perfekt','Futur'];
const ZF5 = ['Präsens','Präteritum','Perfekt','Plusquamperfekt','Futur I'];
const FALL = ['Nominativ','Genitiv','Dativ','Akkusativ'];

const TESTS_GERMAN = [

/* ---------------- KLASSE 4 ---------------- */
{ id:'d4-wortarten', grade:4, subject:'german', icon:'🔤',
  title:{de:'Wortarten-Profi',ru:'Части речи',en:'Parts of Speech'},
  desc:{de:'Nomen, Verben, Adjektive, Artikel, Pronomen erkennen',ru:'Существительные, глаголы, прилагательные',en:'Nouns, verbs, adjectives, articles, pronouns'},
  qs:[
    {t:'mc', q:'„Der Hund bellt laut."\nWelche Wortart ist „Hund"?', tr:{ru:'Какая часть речи слово „Hund"?',en:'What part of speech is "Hund"?'}, opts:WA, a:0, noshuffle:true, h:'wortarten', pts:1},
    {t:'mc', q:'„Der Hund bellt laut."\nWelche Wortart ist „bellt"?', tr:{ru:'Какая часть речи слово „bellt"?',en:'What part of speech is "bellt"?'}, opts:WA, a:1, noshuffle:true, h:'wortarten', pts:1},
    {t:'mc', q:'„Der Hund bellt laut."\nWelche Wortart ist „laut"?', tr:{ru:'Какая часть речи слово „laut"?',en:'What part of speech is "laut"?'}, opts:WA, a:2, noshuffle:true, h:'wortarten', pts:1},
    {t:'mc', q:'„Der Hund bellt laut."\nWelche Wortart ist „der"?', tr:{ru:'Какая часть речи слово „der"?',en:'What part of speech is "der"?'}, opts:WA, a:3, noshuffle:true, h:'wortarten', pts:1},
    {t:'mc', q:'„Sie spielt im Garten."\nWelche Wortart ist „sie"?', tr:{ru:'Какая часть речи слово „sie"?',en:'What part of speech is "sie"?'}, opts:WA, a:4, noshuffle:true, h:'wortarten', pts:1},
    {t:'mc', q:'Welches Wort ist ein Nomen?', tr:{ru:'Какое слово – существительное?',en:'Which word is a noun?'}, opts:['Freude','laufen','schnell','und'], a:0, h:'wortarten', pts:1},
    {t:'mc', q:'Welches Wort ist ein Verb?', tr:{ru:'Какое слово – глагол?',en:'Which word is a verb?'}, opts:['schwimmen','Wasser','nass','tief'], a:0, h:'wortarten', pts:1},
    {t:'mc', q:'Welches Wort ist ein Adjektiv?', tr:{ru:'Какое слово – прилагательное?',en:'Which word is an adjective?'}, opts:['mutig','Mut','Held','sich trauen'], a:0, h:'wortarten', pts:1},
    {t:'mc', q:'Steigere richtig: schnell – schneller – ...?', tr:{ru:'Правильная превосходная степень: schnell – schneller – ...?',en:'Compare correctly: schnell – schneller – ...?'}, opts:['am schnellsten','am schnellem','schnellstens','mehr schnell'], a:0, h:'wortarten', pts:1},
    {t:'mc', q:'Mit welcher Probe erkennst du ein Nomen?', tr:{ru:'Как проверить, что слово – существительное?',en:'How do you test for a noun?'}, opts:['Man kann der, die oder das davorsetzen.','Man kann es steigern.','Man kann „ich" davorsetzen.'], a:0, h:'wortarten', pts:1},
  ]},

{ id:'d4-zeiten', grade:4, subject:'german', icon:'⏳',
  title:{de:'Zeitformen-Training',ru:'Времена глагола',en:'Tenses Training'},
  desc:{de:'Präsens, Präteritum, Perfekt und Futur',ru:'Настоящее, прошедшее и будущее время',en:'Present, past and future tense'},
  qs:[
    {t:'mc', q:'„Wir spielen Fußball."\nIn welcher Zeitform steht der Satz?', tr:{ru:'В каком времени стоит предложение?',en:'Which tense is the sentence in?'}, opts:ZF4, a:0, noshuffle:true, h:'zeiten', pts:1},
    {t:'mc', q:'„Anna ging nach Hause."\nZeitform?', tr:{ru:'Какое время?',en:'Which tense?'}, opts:ZF4, a:1, noshuffle:true, h:'zeiten', pts:1},
    {t:'mc', q:'„Wir haben viel gelacht."\nZeitform?', tr:{ru:'Какое время?',en:'Which tense?'}, opts:ZF4, a:2, noshuffle:true, h:'zeiten', pts:1},
    {t:'mc', q:'„Ich werde morgen lesen."\nZeitform?', tr:{ru:'Какое время?',en:'Which tense?'}, opts:ZF4, a:3, noshuffle:true, h:'zeiten', pts:1},
    {t:'text', q:'Wie heißt das Präteritum von „gehen"?\n(ich ...)', tr:{ru:'Форма Präteritum глагола „gehen"? (ich ...)',en:'What is the Präteritum of "gehen"? (ich ...)'}, a:['ging'], h:'zeiten', pts:1},
    {t:'text', q:'Wie heißt das Präteritum von „essen"?\n(er ...)', tr:{ru:'Форма Präteritum глагола „essen"? (er ...)',en:'What is the Präteritum of "essen"? (er ...)'}, a:['aß','ass'], h:'zeiten', pts:1},
    {t:'mc', q:'Perfekt: „Ich ___ zum Bahnhof gelaufen."', tr:{ru:'Перфект: „Ich ___ zum Bahnhof gelaufen."',en:'Perfect: "Ich ___ zum Bahnhof gelaufen."'}, opts:['bin','habe','werde'], a:0, h:'zeiten', pts:1},
    {t:'mc', q:'Perfekt: „Wir ___ ein Spiel gespielt."', tr:{ru:'Перфект: „Wir ___ ein Spiel gespielt."',en:'Perfect: "Wir ___ ein Spiel gespielt."'}, opts:['haben','sind','werden'], a:0, h:'zeiten', pts:1},
    {t:'text', q:'Setze ins Präteritum: „Er kommt." → „Er ..."', tr:{ru:'Поставь в Präteritum: „Er kommt." → „Er ..."',en:'Put into Präteritum: "Er kommt." → "Er ..."'}, a:['kam'], h:'zeiten', pts:1},
    {t:'mc', q:'Futur: „Ich ___ morgen schwimmen."', tr:{ru:'Будущее время: „Ich ___ morgen schwimmen."',en:'Future: "Ich ___ morgen schwimmen."'}, opts:['werde','wurde','bin'], a:0, h:'zeiten', pts:1},
  ]},

{ id:'d4-recht1', grade:4, subject:'german', icon:'✍️',
  title:{de:'Rechtschreibung: ie, h & Doppelkonsonanten',ru:'Правописание: ie, h и двойные согласные',en:'Spelling: ie, h & double consonants'},
  desc:{de:'Wiese oder Wise? kommen oder komen?',ru:'Wiese или Wise? kommen или komen?',en:'Wiese or Wise? kommen or komen?'},
  qs:[
    {t:'mc', q:'Wie schreibt man das Wort richtig? (die grüne Fläche mit Gras)', tr:{ru:'Как пишется слово правильно? (зелёная лужайка)',en:'Which spelling is correct? (grassy meadow)'}, opts:['Wiese','Wise','Wihse'], a:0, h:'rechtIE', pts:1},
    {t:'mc', q:'Wie schreibt man richtig?', tr:{ru:'Как правильно?',en:'Which is correct?'}, opts:['spielen','spilen','spiehlen'], a:0, h:'rechtIE', pts:1},
    {t:'mc', q:'Wie schreibt man richtig? (mit dem Auto ...)', tr:{ru:'Как правильно? (ехать)',en:'Which is correct? (to drive)'}, opts:['fahren','faren','farhen'], a:0, h:'rechtIE', pts:1},
    {t:'mc', q:'Wie schreibt man richtig? (1, 2, 3 ist eine ...)', tr:{ru:'Как правильно? (число)',en:'Which is correct? (number)'}, opts:['Zahl','Zal','Zaal'], a:0, h:'rechtIE', pts:1},
    {t:'mc', q:'Wie schreibt man richtig? (Möbelstück zum Sitzen)', tr:{ru:'Как правильно? (стул)',en:'Which is correct? (chair)'}, opts:['Stuhl','Stul','Stuhll'], a:0, h:'rechtIE', pts:1},
    {t:'mc', q:'Wie schreibt man richtig?', tr:{ru:'Как правильно?',en:'Which is correct?'}, opts:['kommen','komen','kohmen'], a:0, h:'rechtDoppel', pts:1},
    {t:'mc', q:'Wie schreibt man richtig? (warme Jahreszeit)', tr:{ru:'Как правильно? (лето)',en:'Which is correct? (summer)'}, opts:['Sommer','Somer','Sommmer'], a:0, h:'rechtDoppel', pts:1},
    {t:'mc', q:'Wie schreibt man richtig? (sich im Wasser bewegen)', tr:{ru:'Как правильно? (плавать)',en:'Which is correct? (to swim)'}, opts:['schwimmen','schwimen','schwiemen'], a:0, h:'rechtDoppel', pts:1},
    {t:'mc', q:'Wie schreibt man richtig? (sehr schnell laufen)', tr:{ru:'Как правильно? (бежать)',en:'Which is correct? (to run)'}, opts:['rennen','renen','rehnen'], a:0, h:'rechtDoppel', pts:1},
    {t:'mc', q:'Warum schreibt man „kommen" mit Doppel-m?', tr:{ru:'Почему „kommen" пишется с двумя m?',en:'Why is "kommen" written with double m?'}, opts:['Weil das o kurz gesprochen wird.','Weil das o lang gesprochen wird.','Weil das Wort ein Nomen ist.'], a:0, h:'rechtDoppel', pts:1},
  ]},

{ id:'d4-recht2', grade:4, subject:'german', icon:'📝',
  title:{de:'Rechtschreibung: ck, tz, ß und Auslaut',ru:'Правописание: ck, tz, ß и конец слова',en:'Spelling: ck, tz, ß & final sounds'},
  desc:{de:'Katze, Zucker, Straße – alles richtig schreiben',ru:'Katze, Zucker, Straße – пишем правильно',en:'Katze, Zucker, Straße – spell it right'},
  qs:[
    {t:'mc', q:'Wie schreibt man richtig? (Brot im Ofen machen)', tr:{ru:'Как правильно? (печь)',en:'Which is correct? (to bake)'}, opts:['backen','bakken','baken'], a:0, h:'rechtDoppel', pts:1},
    {t:'mc', q:'Wie schreibt man richtig? (macht den Kuchen süß)', tr:{ru:'Как правильно? (сахар)',en:'Which is correct? (sugar)'}, opts:['Zucker','Zukker','Zuker'], a:0, h:'rechtDoppel', pts:1},
    {t:'mc', q:'Wie schreibt man richtig? (Haustier, das miaut)', tr:{ru:'Как правильно? (кошка)',en:'Which is correct? (cat)'}, opts:['Katze','Kaze','Kazze'], a:0, h:'rechtDoppel', pts:1},
    {t:'mc', q:'Wie schreibt man richtig? (auf einem Stuhl ...)', tr:{ru:'Как правильно? (сидеть)',en:'Which is correct? (to sit)'}, opts:['sitzen','sizen','sietzen'], a:0, h:'rechtDoppel', pts:1},
    {t:'mc', q:'Wie schreibt man richtig? (Autos fahren darauf)', tr:{ru:'Как правильно? (улица)',en:'Which is correct? (street)'}, opts:['Straße','Strase','Sträße'], a:0, h:'rechtSS', pts:1},
    {t:'mc', q:'Wie schreibt man richtig? (großes fließendes Gewässer)', tr:{ru:'Как правильно? (река)',en:'Which is correct? (river)'}, opts:['Fluss','Fluß','Flus'], a:0, h:'rechtSS', pts:1},
    {t:'mc', q:'Wie schreibt man richtig? (Gegenteil von klein)', tr:{ru:'Как правильно? (большой)',en:'Which is correct? (big)'}, opts:['groß','gross','gros'], a:0, h:'rechtSS', pts:1},
    {t:'mc', q:'ß oder ss? Nach einem KURZEN Vokal schreibt man ...', tr:{ru:'ß или ss? После КОРОТКОГО гласного пишут ...',en:'ß or ss? After a SHORT vowel you write ...'}, opts:['ss (wie in Fluss)','ß (wie in Straße)'], a:0, h:'rechtSS', pts:1},
    {t:'mc', q:'Warum schreibt man „Hund" am Ende mit d?', tr:{ru:'Почему „Hund" пишется с d на конце?',en:'Why is "Hund" written with a final d?'}, opts:['Verlängere: „Hunde" – da hört man das d.','Weil d schöner aussieht.','Weil man das d deutlich hört.'], a:0, h:'rechtEnd', pts:1},
    {t:'mc', q:'Wie schreibt man richtig? (hoher Felsen in den Alpen)', tr:{ru:'Как правильно? (гора)',en:'Which is correct? (mountain)'}, opts:['Berg','Berk','Bergk'], a:0, h:'rechtEnd', pts:1},
  ]},

{ id:'d4-faelle', grade:4, subject:'german', icon:'❓',
  title:{de:'Die 4 Fälle',ru:'4 падежа',en:'The 4 Cases'},
  desc:{de:'Nominativ, Genitiv, Dativ, Akkusativ',ru:'Nominativ, Genitiv, Dativ, Akkusativ',en:'Nominative, genitive, dative, accusative'},
  qs:[
    {t:'mc', q:'„Der Hund bellt."\nIn welchem Fall steht „der Hund"?', tr:{ru:'В каком падеже стоит „der Hund"?',en:'Which case is "der Hund" in?'}, opts:FALL, a:0, noshuffle:true, h:'faelle', pts:1},
    {t:'mc', q:'„Ich gebe dem Hund einen Knochen."\nIn welchem Fall steht „dem Hund"?', tr:{ru:'В каком падеже стоит „dem Hund"?',en:'Which case is "dem Hund" in?'}, opts:FALL, a:2, noshuffle:true, h:'faelle', pts:1},
    {t:'mc', q:'„Ich sehe den Hund."\nIn welchem Fall steht „den Hund"?', tr:{ru:'В каком падеже стоит „den Hund"?',en:'Which case is "den Hund" in?'}, opts:FALL, a:3, noshuffle:true, h:'faelle', pts:1},
    {t:'mc', q:'„Das ist das Halsband des Hundes."\nIn welchem Fall steht „des Hundes"?', tr:{ru:'В каком падеже стоит „des Hundes"?',en:'Which case is "des Hundes" in?'}, opts:FALL, a:1, noshuffle:true, h:'faelle', pts:1},
    {t:'mc', q:'Mit welcher Frage findest du den DATIV?', tr:{ru:'Каким вопросом находят DATIV?',en:'Which question finds the DATIVE?'}, opts:['Wem?','Wen oder was?','Wessen?','Wer oder was?'], a:0, h:'faelle', pts:1},
    {t:'mc', q:'Mit welcher Frage findest du den AKKUSATIV?', tr:{ru:'Каким вопросом находят AKKUSATIV?',en:'Which question finds the ACCUSATIVE?'}, opts:['Wen oder was?','Wem?','Wessen?','Wer oder was?'], a:0, h:'faelle', pts:1},
    {t:'mc', q:'Mit welcher Frage findest du den GENITIV?', tr:{ru:'Каким вопросом находят GENITIV?',en:'Which question finds the GENITIVE?'}, opts:['Wessen?','Wem?','Wen oder was?','Wer oder was?'], a:0, h:'faelle', pts:1},
    {t:'mc', q:'Setze richtig ein: „___ Mann gebe ich die Zeitung." (Dativ)', tr:{ru:'Вставь правильно: „___ Mann gebe ich die Zeitung." (Dativ)',en:'Fill in: "___ Mann gebe ich die Zeitung." (dative)'}, opts:['Dem','Den','Des','Der'], a:0, h:'faelle', pts:1},
  ]},

{ id:'d4-satz', grade:4, subject:'german', icon:'🧩',
  title:{de:'Satzglieder & Satzarten',ru:'Члены и виды предложений',en:'Sentence Parts & Types'},
  desc:{de:'Subjekt, Prädikat, Objekt und die Satzarten',ru:'Подлежащее, сказуемое, дополнение',en:'Subject, predicate, object and sentence types'},
  qs:[
    {t:'mc', q:'„Lena liest ein Buch."\nWas ist das SUBJEKT?', tr:{ru:'Что здесь подлежащее?',en:'What is the SUBJECT?'}, opts:['Lena','liest','ein Buch'], a:0, h:'satzglieder', pts:1},
    {t:'mc', q:'„Lena liest ein Buch."\nWas ist das PRÄDIKAT?', tr:{ru:'Что здесь сказуемое?',en:'What is the PREDICATE?'}, opts:['liest','Lena','ein Buch'], a:0, h:'satzglieder', pts:1},
    {t:'mc', q:'„Lena liest ein Buch."\nWas ist „ein Buch"?', tr:{ru:'Чем является „ein Buch"?',en:'What is "ein Buch"?'}, opts:['Akkusativobjekt','Subjekt','Prädikat','Dativobjekt'], a:0, h:'satzglieder', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Im Aussagesatz steht das Prädikat an zweiter Stelle."', tr:{ru:'Верно ли: в повествовательном предложении сказуемое стоит на втором месте?',en:'True or false: in a statement the predicate is in 2nd position?'}, a:true, h:'satzglieder', pts:1},
    {t:'mc', q:'„Kommst du morgen mit?"\nWelche Satzart ist das?', tr:{ru:'Какой это вид предложения?',en:'What sentence type is this?'}, opts:['Fragesatz','Aussagesatz','Aufforderungssatz'], a:0, h:'satzarten', pts:1},
    {t:'mc', q:'„Räum bitte dein Zimmer auf!"\nWelche Satzart ist das?', tr:{ru:'Какой это вид предложения?',en:'What sentence type is this?'}, opts:['Aufforderungssatz','Fragesatz','Aussagesatz'], a:0, h:'satzarten', pts:1},
    {t:'mc', q:'„Wir fahren morgen nach Köln."\nWelches Satzzeichen kommt ans Ende?', tr:{ru:'Какой знак ставится в конце?',en:'Which punctuation mark ends the sentence?'}, opts:['. (Punkt)','? (Fragezeichen)','! (Ausrufezeichen)'], a:0, h:'satzarten', pts:1},
    {t:'mc', q:'„Wem gehört der Ball?" – „Der Ball gehört dem Jungen."\n„dem Jungen" ist ein ...', tr:{ru:'„dem Jungen" – это ...',en:'"dem Jungen" is a ...'}, opts:['Dativobjekt','Akkusativobjekt','Subjekt'], a:0, h:'satzglieder', pts:1},
  ]},

{ id:'d4-lesen', grade:4, subject:'german', icon:'🦔',
  title:{de:'Leseverstehen: Der Igel',ru:'Чтение: Ёжик',en:'Reading: The Hedgehog'},
  desc:{de:'Lies den Text genau und beantworte die Fragen',ru:'Внимательно прочитай текст и ответь на вопросы',en:'Read carefully and answer the questions'},
  reading:{title:'Der Igel – ein stacheliger Geselle',
    text:`Der Igel ist ein nachtaktives Tier: Am Tag schläft er gut versteckt unter Laub und Hecken, in der Nacht geht er auf Futtersuche. Am liebsten frisst er Insekten, Würmer und Schnecken. Milch darf ein Igel niemals trinken, denn sie macht ihn krank!
Auf seinem Rücken trägt der Igel etwa 6.000 bis 8.000 Stacheln. Bei Gefahr rollt er sich blitzschnell zu einer stacheligen Kugel zusammen – so kann ihm kaum ein Feind etwas anhaben.
Im Herbst frisst sich der Igel eine dicke Speckschicht an. Die braucht er auch, denn von November bis März hält er Winterschlaf. Erst im Frühling wacht er wieder auf – hungrig und dünn.`},
  qs:[
    {t:'mc', q:'Wann ist der Igel aktiv?', tr:{ru:'Когда ёжик активен?',en:'When is the hedgehog active?'}, opts:['in der Nacht','am Tag','nur im Winter'], a:0, h:'lesen', pts:1},
    {t:'mc', q:'Was frisst der Igel am liebsten?', tr:{ru:'Что ёжик любит есть больше всего?',en:'What does the hedgehog like to eat most?'}, opts:['Insekten, Würmer und Schnecken','Gras und Blätter','Obst und Nüsse'], a:0, h:'lesen', pts:1},
    {t:'mc', q:'Warum darf ein Igel keine Milch trinken?', tr:{ru:'Почему ёжику нельзя молоко?',en:'Why must a hedgehog not drink milk?'}, opts:['Milch macht ihn krank.','Milch schmeckt ihm nicht.','Milch macht ihn müde.'], a:0, h:'lesen', pts:1},
    {t:'mc', q:'Wie schützt sich der Igel bei Gefahr?', tr:{ru:'Как ёжик защищается при опасности?',en:'How does the hedgehog protect itself?'}, opts:['Er rollt sich zu einer Kugel zusammen.','Er rennt schnell weg.','Er klettert auf einen Baum.'], a:0, h:'lesen', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Der Igel hält Winterschlaf."', tr:{ru:'Верно или неверно: «Ёжик впадает в зимнюю спячку».',en:'True or false: "The hedgehog hibernates."'}, a:true, h:'lesen', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Ein Igel hat ungefähr 100 Stacheln."', tr:{ru:'Верно или неверно: «У ёжика примерно 100 иголок».',en:'True or false: "A hedgehog has about 100 spines."'}, a:false, h:'lesen', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Am Tag schläft der Igel."', tr:{ru:'Верно или неверно: «Днём ёжик спит».',en:'True or false: "The hedgehog sleeps during the day."'}, a:true, h:'lesen', pts:1},
    {t:'mc', q:'Von wann bis wann hält der Igel Winterschlaf?', tr:{ru:'С какого по какой месяц ёжик спит зимой?',en:'From when to when does the hedgehog hibernate?'}, opts:['von November bis März','von September bis Dezember','von Januar bis Juni'], a:0, h:'lesen', pts:1},
  ]},

{ id:'d4-rede', grade:4, subject:'german', icon:'💬',
  title:{de:'Wörtliche Rede',ru:'Прямая речь',en:'Direct Speech'},
  desc:{de:'Doppelpunkt, Anführungszeichen & Co.',ru:'Двоеточие, кавычки и всё остальное',en:'Colon, quotation marks & co.'},
  qs:[
    {t:'mc', q:'Welcher Satz ist RICHTIG geschrieben?', tr:{ru:'Какое предложение написано ПРАВИЛЬНО?',en:'Which sentence is written CORRECTLY?'},
      opts:['Anna sagt: „Ich komme mit."','Anna sagt „Ich komme mit.":','Anna sagt, Ich komme mit.'], a:0, h:'woertlRede', pts:1},
    {t:'mc', q:'Welches Zeichen steht VOR der wörtlichen Rede, wenn der Begleitsatz vorne steht?', tr:{ru:'Какой знак стоит ПЕРЕД прямой речью, если слова автора впереди?',en:'Which sign comes BEFORE direct speech when the speaker part is first?'},
      opts:['Doppelpunkt (:)','Komma (,)','Punkt (.)'], a:0, h:'woertlRede', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Die wörtliche Rede beginnt immer mit einem großen Buchstaben."', tr:{ru:'Верно ли: прямая речь всегда начинается с большой буквы?',en:'True or false: direct speech always starts with a capital letter?'}, a:true, h:'woertlRede', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„,Ich habe Hunger", sagt Tom.‘ – Nach der wörtlichen Rede steht hier ein Komma."', tr:{ru:'Верно ли: после прямой речи здесь стоит запятая?',en:'True or false: after the direct speech there is a comma here?'}, a:true, h:'woertlRede', pts:1},
    {t:'mc', q:'Wo stehen die Anführungszeichen am ANFANG der wörtlichen Rede?', tr:{ru:'Где стоят кавычки в НАЧАЛЕ прямой речи?',en:'Where are the quotation marks at the START of direct speech?'},
      opts:['unten („)','oben (")','in der Mitte'], a:0, h:'woertlRede', pts:1},
    {t:'mc', q:'Welcher Satz ist RICHTIG?', tr:{ru:'Какое предложение ПРАВИЛЬНОЕ?',en:'Which sentence is CORRECT?'},
      opts:['„Wo ist mein Heft?", fragt Lea.','„Wo ist mein Heft?" fragt Lea:','Wo ist mein Heft?, „fragt Lea."'], a:0, h:'woertlRede', pts:1},
  ]},

/* ---------------- KLASSE 5 ---------------- */
{ id:'d5-wortarten', grade:5, subject:'german', icon:'🎓',
  title:{de:'Wortarten & Wortbildung',ru:'Части речи и словообразование',en:'Word Types & Word Building'},
  desc:{de:'Jetzt mit Präpositionen, Konjunktionen und Wortfamilien',ru:'Теперь с предлогами, союзами и семьями слов',en:'Now with prepositions, conjunctions and word families'},
  qs:[
    {t:'mc', q:'„Der Ball liegt unter dem Tisch."\nWelche Wortart ist „unter"?', tr:{ru:'Какая часть речи „unter"?',en:'What part of speech is "unter"?'}, opts:['Präposition','Artikel','Adjektiv','Konjunktion'], a:0, h:'wortarten', pts:1},
    {t:'mc', q:'„Ich bleibe zu Hause, weil ich krank bin."\nWelche Wortart ist „weil"?', tr:{ru:'Какая часть речи „weil"?',en:'What part of speech is "weil"?'}, opts:['Konjunktion','Präposition','Pronomen','Verb'], a:0, h:'wortarten', pts:1},
    {t:'mc', q:'„Die Freundschaft ist wichtig."\nWelches Wort ist das Nomen?', tr:{ru:'Какое слово – существительное?',en:'Which word is the noun?'}, opts:['Freundschaft','wichtig','ist'], a:0, h:'wortarten', pts:1},
    {t:'mc', q:'Welches Wort gehört NICHT zur Wortfamilie „fahren"?', tr:{ru:'Какое слово НЕ из семьи слова „fahren"?',en:'Which word does NOT belong to the family of "fahren"?'}, opts:['Farbe','Fahrer','Abfahrt','Fahrrad'], a:0, h:'wortfamilie', pts:1},
    {t:'mc', q:'Welches Wort gehört zum WORTFELD „sagen"?', tr:{ru:'Какое слово из поля «говорить»?',en:'Which word belongs to the word field "to say"?'}, opts:['flüstern','rennen','schlafen','springen'], a:0, h:'wortfamilie', pts:1},
    {t:'mc', q:'Welches Wort ist ein zusammengesetztes Nomen?', tr:{ru:'Какое слово – сложное существительное?',en:'Which word is a compound noun?'}, opts:['Haustür','Häuser','häuslich','hausen'], a:0, h:'wortarten', pts:1},
    {t:'mc', q:'Wie heißt der richtige Artikel? „___ Mädchen"', tr:{ru:'Правильный артикль: „___ Mädchen"',en:'Correct article: "___ Mädchen"'}, opts:['das','die','der'], a:0, h:'wortarten', pts:1},
    {t:'mc', q:'Steigere richtig: gut – ... – am besten', tr:{ru:'Сравнительная степень: gut – ... – am besten',en:'Compare correctly: gut – ... – am besten'}, opts:['besser','guter','mehr gut'], a:0, h:'wortarten', pts:1},
    {t:'mc', q:'„Es regnet."\nWelche Wortart ist „es"?', tr:{ru:'Какая часть речи „es"?',en:'What part of speech is "es"?'}, opts:['Pronomen','Artikel','Nomen'], a:0, h:'wortarten', pts:1},
    {t:'mc', q:'Aus welchem Verb kommt das Nomen „der Sprung"?', tr:{ru:'От какого глагола существительное „der Sprung"?',en:'From which verb does the noun "der Sprung" come?'}, opts:['springen','sprechen','spritzen'], a:0, h:'wortfamilie', pts:1},
  ]},

{ id:'d5-zeiten', grade:5, subject:'german', icon:'🕰️',
  title:{de:'Alle Zeitformen',ru:'Все времена глагола',en:'All Tenses'},
  desc:{de:'Jetzt auch mit Plusquamperfekt!',ru:'Теперь и с Plusquamperfekt!',en:'Now including Plusquamperfekt!'},
  qs:[
    {t:'mc', q:'„Er hatte schon gegessen."\nZeitform?', tr:{ru:'Какое время?',en:'Which tense?'}, opts:ZF5, a:3, noshuffle:true, h:'zeiten', pts:1},
    {t:'mc', q:'„Sie wird morgen kommen."\nZeitform?', tr:{ru:'Какое время?',en:'Which tense?'}, opts:ZF5, a:4, noshuffle:true, h:'zeiten', pts:1},
    {t:'mc', q:'„Wir sangen ein Lied."\nZeitform?', tr:{ru:'Какое время?',en:'Which tense?'}, opts:ZF5, a:1, noshuffle:true, h:'zeiten', pts:1},
    {t:'mc', q:'„Ihr habt das Spiel gewonnen."\nZeitform?', tr:{ru:'Какое время?',en:'Which tense?'}, opts:ZF5, a:2, noshuffle:true, h:'zeiten', pts:1},
    {t:'text', q:'Präteritum von „laufen"? (ich ...)', tr:{ru:'Präteritum глагола „laufen"? (ich ...)',en:'Präteritum of "laufen"? (ich ...)'}, a:['lief'], h:'zeiten', pts:1},
    {t:'text', q:'Präteritum von „sehen"? (er ...)', tr:{ru:'Präteritum глагола „sehen"? (er ...)',en:'Präteritum of "sehen"? (er ...)'}, a:['sah'], h:'zeiten', pts:1},
    {t:'text', q:'Partizip II von „schreiben"? (ich habe ...)', tr:{ru:'Partizip II глагола „schreiben"? (ich habe ...)',en:'Past participle of "schreiben"? (ich habe ...)'}, a:['geschrieben'], h:'zeiten', pts:1},
    {t:'mc', q:'Perfekt: „Wir ___ nach Berlin gefahren."', tr:{ru:'Перфект: „Wir ___ nach Berlin gefahren."',en:'Perfect: "Wir ___ nach Berlin gefahren."'}, opts:['sind','haben','werden'], a:0, h:'zeiten', pts:1},
    {t:'text', q:'Präteritum von „nehmen"? (sie ...)', tr:{ru:'Präteritum глагола „nehmen"? (sie ...)',en:'Präteritum of "nehmen"? (sie ...)'}, a:['nahm'], h:'zeiten', pts:1},
    {t:'mc', q:'Wie bildet man das Futur I?', tr:{ru:'Как образуется Futur I?',en:'How do you build Futur I?'}, opts:['werden + Grundform (ich werde lernen)','haben + Partizip (ich habe gelernt)','sein + Grundform (ich bin lernen)'], a:0, h:'zeiten', pts:1},
  ]},

{ id:'d5-satzglieder', grade:5, subject:'german', icon:'🔍',
  title:{de:'Satzglieder-Detektiv',ru:'Детектив членов предложения',en:'Sentence Part Detective'},
  desc:{de:'Mit adverbialen Bestimmungen von Ort und Zeit',ru:'С обстоятельствами места и времени',en:'With adverbials of place and time'},
  qs:[
    {t:'mc', q:'„Am Morgen füttert Papa die Katze."\nWas ist das SUBJEKT?', tr:{ru:'Что здесь подлежащее?',en:'What is the SUBJECT?'}, opts:['Papa','Am Morgen','die Katze'], a:0, h:'satzglieder', pts:1},
    {t:'mc', q:'„Am Morgen füttert Papa die Katze."\nWas ist „Am Morgen"?', tr:{ru:'Чем является „Am Morgen"?',en:'What is "Am Morgen"?'}, opts:['adverbiale Bestimmung der Zeit','Subjekt','Akkusativobjekt'], a:0, h:'satzglieder', pts:1},
    {t:'mc', q:'„Die Kinder spielen in der Schule."\nWas ist „in der Schule"?', tr:{ru:'Чем является „in der Schule"?',en:'What is "in der Schule"?'}, opts:['adverbiale Bestimmung des Ortes','Dativobjekt','Prädikat'], a:0, h:'satzglieder', pts:1},
    {t:'mc', q:'Mit welcher Frage findest du die adverbiale Bestimmung des ORTES?', tr:{ru:'Каким вопросом находят обстоятельство МЕСТА?',en:'Which question finds the adverbial of PLACE?'}, opts:['Wo?','Wann?','Wie?','Wen?'], a:0, h:'satzglieder', pts:1},
    {t:'mc', q:'„Ich schenke meiner Oma Blumen."\nWas ist „meiner Oma"?', tr:{ru:'Чем является „meiner Oma"?',en:'What is "meiner Oma"?'}, opts:['Dativobjekt','Akkusativobjekt','Subjekt'], a:0, h:'satzglieder', pts:1},
    {t:'mc', q:'„Ich schenke meiner Oma Blumen."\nWas ist „Blumen"?', tr:{ru:'Чем является „Blumen"?',en:'What is "Blumen"?'}, opts:['Akkusativobjekt','Dativobjekt','Prädikat'], a:0, h:'satzglieder', pts:1},
    {t:'mc', q:'„Morgen fahren wir nach Paderborn."\nWas ist das PRÄDIKAT?', tr:{ru:'Что здесь сказуемое?',en:'What is the PREDICATE?'}, opts:['fahren','Morgen','wir','nach Paderborn'], a:0, h:'satzglieder', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Bei der Umstellprobe bleiben Satzglieder immer als Block zusammen."', tr:{ru:'Верно ли: при перестановке члены предложения двигаются целиком?',en:'True or false: when rearranging, sentence parts stay together as a block?'}, a:true, h:'satzglieder', pts:1},
  ]},

{ id:'d5-recht', grade:5, subject:'german', icon:'🔠',
  title:{de:'Groß, klein & Kommas',ru:'Большие буквы и запятые',en:'Capitals & Commas'},
  desc:{de:'Großschreibung und Kommas bei Aufzählungen',ru:'Заглавные буквы и запятые при перечислении',en:'Capitalisation and commas in lists'},
  qs:[
    {t:'mc', q:'Wie schreibt man richtig?\n„Das ___ macht mir Spaß."', tr:{ru:'Как правильно: „Das ___ macht mir Spaß."?',en:'Which is correct: "Das ___ macht mir Spaß."?'}, opts:['Laufen','laufen'], a:0, h:'grossklein', pts:1},
    {t:'mc', q:'Wie schreibt man richtig?\n„Beim ___ trage ich eine Brille."', tr:{ru:'Как правильно: „Beim ___ trage ich eine Brille."?',en:'Which is correct: "Beim ___ trage ich eine Brille."?'}, opts:['Schwimmen','schwimmen'], a:0, h:'grossklein', pts:1},
    {t:'mc', q:'Wie schreibt man richtig?\n„Ich habe etwas ___ gesehen."', tr:{ru:'Как правильно: „Ich habe etwas ___ gesehen."?',en:'Which is correct: "Ich habe etwas ___ gesehen."?'}, opts:['Schönes','schönes'], a:0, h:'grossklein', pts:1},
    {t:'mc', q:'Wie schreibt man richtig?\n„Wir ___ heute Fußball."', tr:{ru:'Как правильно: „Wir ___ heute Fußball."?',en:'Which is correct: "Wir ___ heute Fußball."?'}, opts:['spielen','Spielen'], a:0, h:'grossklein', pts:1},
    {t:'mc', q:'Wo fehlt ein Komma?\n„Ich kaufe Äpfel Birnen und Trauben."', tr:{ru:'Где не хватает запятой?',en:'Where is a comma missing?'}, opts:['nach „Äpfel"','nach „Birnen"','vor „und"'], a:0, h:'kommas', pts:1},
    {t:'mc', q:'Welcher Satz ist RICHTIG?', tr:{ru:'Какое предложение ПРАВИЛЬНОЕ?',en:'Which sentence is CORRECT?'},
      opts:['Im Zoo sehen wir Löwen, Tiger, Affen und Elefanten.','Im Zoo sehen wir Löwen, Tiger, Affen, und Elefanten.','Im Zoo sehen wir Löwen Tiger Affen und Elefanten.'], a:0, h:'kommas', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Vor ,und‘ steht bei Aufzählungen KEIN Komma."', tr:{ru:'Верно ли: перед „und" при перечислении запятая НЕ ставится?',en:'True or false: in lists there is NO comma before "und"?'}, a:true, h:'kommas', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Die höfliche Anrede ,Sie‘ schreibt man groß."', tr:{ru:'Верно ли: вежливое обращение „Sie" пишется с большой буквы?',en:'True or false: the polite "Sie" is capitalised?'}, a:true, h:'grossklein', pts:1},
    {t:'mc', q:'Wie schreibt man richtig?\n„Am ___ habe ich Training."', tr:{ru:'Как правильно: „Am ___ habe ich Training."?',en:'Which is correct: "Am ___ habe ich Training."?'}, opts:['Montag','montag'], a:0, h:'grossklein', pts:1},
    {t:'mc', q:'Welche Wörter sind Signalwörter für ein großgeschriebenes Verb (Nominalisierung)?', tr:{ru:'Какие слова – сигналы, что глагол пишется с большой буквы?',en:'Which words signal a capitalised verb (nominalisation)?'}, opts:['das, beim, zum, vom','und, oder, aber','ich, du, er'], a:0, h:'grossklein', pts:1},
  ]},

{ id:'d5-lesen', grade:5, subject:'german', icon:'🔬',
  title:{de:'Leseverstehen: Lise Meitner',ru:'Чтение: Лиза Мейтнер',en:'Reading: Lise Meitner'},
  desc:{de:'Die berühmte Forscherin, nach der deine Schule benannt ist!',ru:'Знаменитая учёная, в честь которой названа твоя школа!',en:'The famous scientist your school is named after!'},
  reading:{title:'Lise Meitner – die Namensgeberin deiner Schule',
    text:`Lise Meitner wurde 1878 in Wien geboren. Schon als Kind liebte sie Mathematik und Naturwissenschaften – zu einer Zeit, als Mädchen noch nicht einmal aufs Gymnasium gehen durften! Mit viel Fleiß wurde sie eine der ersten Frauen, die in Physik promovierten.
In Berlin forschte sie über 30 Jahre lang mit dem Chemiker Otto Hahn. Gemeinsam untersuchten sie Atomkerne. Als Lise Meitner 1938 wegen ihrer jüdischen Herkunft aus Deutschland fliehen musste, ging sie nach Schweden. Von dort lieferte sie die entscheidende Erklärung für die Kernspaltung – eine der wichtigsten Entdeckungen des 20. Jahrhunderts.
Bis heute wird Lise Meitner bewundert: Das chemische Element 109, „Meitnerium", trägt ihren Namen. Und in Paderborn ist die Realschule Lise Meitner nach ihr benannt – deine neue Schule!`},
  qs:[
    {t:'mc', q:'Wo wurde Lise Meitner geboren?', tr:{ru:'Где родилась Лиза Мейтнер?',en:'Where was Lise Meitner born?'}, opts:['in Wien','in Berlin','in Paderborn'], a:0, h:'lesen', pts:1},
    {t:'mc', q:'Welchen Beruf hatte Lise Meitner?', tr:{ru:'Кем была Лиза Мейтнер?',en:'What was Lise Meitner’s profession?'}, opts:['Physikerin','Musikerin','Lehrerin'], a:0, h:'lesen', pts:1},
    {t:'mc', q:'Mit wem forschte sie in Berlin?', tr:{ru:'С кем она работала в Берлине?',en:'With whom did she do research in Berlin?'}, opts:['mit Otto Hahn','mit Albert Einstein','mit Marie Curie'], a:0, h:'lesen', pts:1},
    {t:'mc', q:'Wofür lieferte sie die entscheidende Erklärung?', tr:{ru:'Что она объяснила?',en:'What did she deliver the key explanation for?'}, opts:['für die Kernspaltung','für den Regenbogen','für die Schwerkraft'], a:0, h:'lesen', pts:1},
    {t:'mc', q:'Wohin floh sie 1938?', tr:{ru:'Куда она бежала в 1938 году?',en:'Where did she flee to in 1938?'}, opts:['nach Schweden','nach Amerika','nach England'], a:0, h:'lesen', pts:1},
    {t:'mc', q:'Welches Element trägt ihren Namen?', tr:{ru:'Какой элемент назван в её честь?',en:'Which element is named after her?'}, opts:['Meitnerium','Einsteinium','Lisium'], a:0, h:'lesen', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Deine neue Schule in Paderborn ist nach Lise Meitner benannt."', tr:{ru:'Верно ли: твоя новая школа в Падерборне названа в честь Лизы Мейтнер?',en:'True or false: your new school in Paderborn is named after Lise Meitner?'}, a:true, h:'lesen', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Als Lise Meitner ein Kind war, durften Mädchen ganz normal aufs Gymnasium gehen."', tr:{ru:'Верно ли: когда Лиза была ребёнком, девочки могли спокойно ходить в гимназию?',en:'True or false: when Lise was a child, girls could attend Gymnasium normally?'}, a:false, h:'lesen', pts:1},
  ]},

{ id:'d5-mix', grade:5, subject:'german', icon:'🎲',
  title:{de:'Großer Grammatik-Mix',ru:'Большой грамматический микс',en:'Big Grammar Mix'},
  desc:{de:'Alles durcheinander – wie in einer echten Klassenarbeit',ru:'Всё вперемешку – как в настоящей контрольной',en:'Everything mixed – like a real class test'},
  qs:[
    {t:'mc', q:'Welche Wortart ist „glücklich"?', tr:{ru:'Какая часть речи „glücklich"?',en:'What part of speech is "glücklich"?'}, opts:['Adjektiv','Nomen','Verb','Artikel'], a:0, h:'wortarten', pts:1},
    {t:'mc', q:'„Der Lehrer lobte die Klasse."\nZeitform?', tr:{ru:'Какое время?',en:'Which tense?'}, opts:['Präteritum','Präsens','Perfekt','Futur I'], a:0, h:'zeiten', pts:1},
    {t:'mc', q:'„Ich helfe dem Kind."\nIn welchem Fall steht „dem Kind"?', tr:{ru:'В каком падеже стоит „dem Kind"?',en:'Which case is "dem Kind" in?'}, opts:['Dativ','Akkusativ','Nominativ','Genitiv'], a:0, h:'faelle', pts:1},
    {t:'mc', q:'Wie schreibt man richtig?', tr:{ru:'Как правильно?',en:'Which is correct?'}, opts:['plötzlich','plözlich','plötzlih'], a:0, h:'rechtDoppel', pts:1},
    {t:'mc', q:'„Gestern besuchte uns Oma."\nWas ist „Gestern"?', tr:{ru:'Чем является „Gestern"?',en:'What is "Gestern"?'}, opts:['adverbiale Bestimmung der Zeit','Subjekt','Objekt'], a:0, h:'satzglieder', pts:1},
    {t:'text', q:'Partizip II von „finden"? (ich habe ...)', tr:{ru:'Partizip II глагола „finden"? (ich habe ...)',en:'Past participle of "finden"? (ich habe ...)'}, a:['gefunden'], h:'zeiten', pts:1},
    {t:'mc', q:'Welcher Satz ist ein Fragesatz?', tr:{ru:'Какое предложение вопросительное?',en:'Which sentence is a question?'}, opts:['Hast du Hunger?','Ich habe Hunger.','Iss dein Brot!'], a:0, h:'satzarten', pts:1},
    {t:'mc', q:'Wie schreibt man richtig?\n„Das ___ fällt mir leicht."', tr:{ru:'Как правильно: „Das ___ fällt mir leicht."?',en:'Which is correct: "Das ___ fällt mir leicht."?'}, opts:['Lesen','lesen'], a:0, h:'grossklein', pts:1},
    {t:'mc', q:'Welches Wort gehört zur Wortfamilie „spielen"?', tr:{ru:'Какое слово из семьи „spielen"?',en:'Which word belongs to the family of "spielen"?'}, opts:['Spieler','Spiegel','Speise'], a:0, h:'wortfamilie', pts:1},
    {t:'mc', q:'Welcher Satz ist RICHTIG geschrieben?', tr:{ru:'Какое предложение написано правильно?',en:'Which sentence is written correctly?'},
      opts:['Tom sagt: „Ich mag Pizza, Nudeln und Salat."','Tom sagt: „ich mag Pizza, Nudeln, und Salat."','Tom sagt „Ich mag Pizza Nudeln und Salat.":'], a:0, h:'woertlRede', pts:1},
  ]},

/* ---------- Erweiterung: mehr Deutsch-Tests ---------- */
{ id:'d4-nomen', grade:4, subject:'german', icon:'🏷️',
  title:{de:'Nomen: Artikel & Mehrzahl',ru:'Существительные: артикль и мн. число',en:'Nouns: Article & Plural'},
  desc:{de:'der, die, das und die Mehrzahl bilden',ru:'der, die, das и множественное число',en:'der, die, das and building plurals'},
  qs:[
    {t:'text', q:'Bilde die Mehrzahl: das Kind → die ...', tr:{ru:'Множественное число: das Kind → die ...',en:'Plural: das Kind → die ...'}, a:['kinder'], h:'nomen', pts:1},
    {t:'text', q:'Bilde die Mehrzahl: der Baum → die ...', tr:{ru:'Множественное число: der Baum → die ...',en:'Plural: der Baum → die ...'}, a:['bäume','baeume'], h:'nomen', pts:1},
    {t:'text', q:'Bilde die Mehrzahl: die Maus → die ...', tr:{ru:'Множественное число: die Maus → die ...',en:'Plural: die Maus → die ...'}, a:['mäuse','maeuse'], h:'nomen', pts:1},
    {t:'mc', q:'Wie heißt der richtige Artikel? „___ Schule"', tr:{ru:'Правильный артикль: „___ Schule"',en:'Correct article: "___ Schule"'}, opts:['die','der','das'], a:0, h:'nomen', pts:1},
    {t:'mc', q:'Wie heißt der richtige Artikel? „___ Auto"', tr:{ru:'Правильный артикль: „___ Auto"',en:'Correct article: "___ Auto"'}, opts:['das','die','der'], a:0, h:'nomen', pts:1},
    {t:'text', q:'Bilde die Einzahl: die Häuser → das ...', tr:{ru:'Единственное число: die Häuser → das ...',en:'Singular: die Häuser → das ...'}, a:['haus'], h:'nomen', pts:1},
    {t:'mc', q:'Schule + Hof = ? Wie heißt das zusammengesetzte Nomen?', tr:{ru:'Schule + Hof = ? Как называется сложное слово?',en:'Schule + Hof = ? What is the compound noun?'}, opts:['der Schulhof','die Schulehof','das Hofschule'], a:0, h:'nomen', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Bei zusammengesetzten Nomen bestimmt das letzte Wort den Artikel."', tr:{ru:'Верно ли: в сложных словах артикль определяет последнее слово?',en:'True or false: in compounds the last word decides the article?'}, a:true, h:'nomen', pts:1},
    {t:'mc', q:'Welches Wort ist ein Nomen, das man nicht anfassen kann (abstrakt)?', tr:{ru:'Какое существительное нельзя потрогать (абстрактное)?',en:'Which noun can you not touch (abstract)?'}, opts:['das Glück','der Tisch','die Blume'], a:0, h:'nomen', pts:1},
    {t:'match', q:'Verbinde Einzahl und Mehrzahl:', tr:{ru:'Соедини единственное и множественное число:',en:'Match singular and plural:'},
      pairs:[['der Apfel','die Äpfel'],['das Buch','die Bücher'],['die Blume','die Blumen'],['das Foto','die Fotos']], h:'nomen', pts:4},
  ]},

{ id:'d4-verben', grade:4, subject:'german', icon:'🏃',
  title:{de:'Verben-Werkstatt',ru:'Мастерская глаголов',en:'Verb Workshop'},
  desc:{de:'Grundform finden und richtig konjugieren',ru:'Начальная форма и спряжение',en:'Base form and conjugation'},
  qs:[
    {t:'text', q:'Wie heißt die Grundform von „läuft"?', tr:{ru:'Начальная форма глагола „läuft"?',en:'Base form of "läuft"?'}, a:['laufen'], h:'verben', pts:1},
    {t:'text', q:'Wie heißt die Grundform von „isst"?', tr:{ru:'Начальная форма глагола „isst"?',en:'Base form of "isst"?'}, a:['essen'], h:'verben', pts:1},
    {t:'text', q:'Setze richtig ein: „du (gehen)" → du ...', tr:{ru:'Вставь правильно: „du (gehen)" → du ...',en:'Fill in: "du (gehen)" → du ...'}, a:['gehst'], h:'verben', pts:1},
    {t:'text', q:'Setze richtig ein: „er (lesen)" → er ...', tr:{ru:'Вставь правильно: „er (lesen)" → er ...',en:'Fill in: "er (lesen)" → er ...'}, a:['liest'], h:'verben', pts:1},
    {t:'text', q:'Setze richtig ein: „wir (sein)" → wir ...', tr:{ru:'Вставь правильно: „wir (sein)" → wir ...',en:'Fill in: "wir (sein)" → wir ...'}, a:['sind'], h:'verben', pts:1},
    {t:'mc', q:'Welche Form passt? „Ihr ___ heute Fußball."', tr:{ru:'Какая форма подходит: „Ihr ___ heute Fußball."?',en:'Which form fits: "Ihr ___ heute Fußball."?'}, opts:['spielt','spielst','spielen'], a:0, h:'verben', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Verben schreibt man im Satz klein."', tr:{ru:'Верно ли: глаголы в предложении пишутся с маленькой буквы?',en:'True or false: verbs are written lowercase in a sentence?'}, a:true, h:'verben', pts:1},
    {t:'mc', q:'Wie heißt die Befehlsform (du) von „kommen"?', tr:{ru:'Повелительная форма (du) глагола „kommen"?',en:'Command form (du) of "kommen"?'}, opts:['Komm!','Kommst!','Kommen!'], a:0, h:'verben', pts:1},
    {t:'match', q:'Verbinde Person und Verbform von „fahren":', tr:{ru:'Соедини лицо и форму глагола „fahren":',en:'Match person and form of "fahren":'},
      pairs:[['ich','fahre'],['du','fährst'],['er','fährt'],['wir','fahren']], h:'verben', pts:4},
  ]},

{ id:'d4-adjektive', grade:4, subject:'german', icon:'🌈',
  title:{de:'Adjektive & Gegenteile',ru:'Прилагательные и антонимы',en:'Adjectives & Opposites'},
  desc:{de:'Steigern und Gegenteile finden',ru:'Степени сравнения и противоположности',en:'Comparing and finding opposites'},
  qs:[
    {t:'text', q:'Wie heißt das Gegenteil von „groß"?', tr:{ru:'Антоним слова „groß"?',en:'Opposite of "groß"?'}, a:['klein'], h:'adjektive', pts:1},
    {t:'text', q:'Wie heißt das Gegenteil von „hell"?', tr:{ru:'Антоним слова „hell"?',en:'Opposite of "hell"?'}, a:['dunkel'], h:'adjektive', pts:1},
    {t:'mc', q:'Steigere richtig: alt – ... – am ältesten', tr:{ru:'Сравнительная степень: alt – ... – am ältesten',en:'Compare: alt – ... – am ältesten'}, opts:['älter','alter','mehr alt'], a:0, h:'adjektive', pts:1},
    {t:'mc', q:'Steigere richtig: viel – mehr – ...', tr:{ru:'Превосходная степень: viel – mehr – ...',en:'Superlative: viel – mehr – ...'}, opts:['am meisten','am vielsten','am mehrsten'], a:0, h:'adjektive', pts:1},
    {t:'mc', q:'Steigere richtig: gern – ... – am liebsten', tr:{ru:'Сравнительная степень: gern – ... – am liebsten',en:'Compare: gern – ... – am liebsten'}, opts:['lieber','gerner','mehr gern'], a:0, h:'adjektive', pts:1},
    {t:'mc', q:'„Der kleine Hund schläft."\nWelches Wort ist das Adjektiv?', tr:{ru:'Какое слово – прилагательное?',en:'Which word is the adjective?'}, opts:['kleine','Hund','schläft'], a:0, h:'adjektive', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Adjektive kann man steigern."', tr:{ru:'Верно ли: прилагательные можно сравнивать по степеням?',en:'True or false: adjectives can be compared?'}, a:true, h:'adjektive', pts:1},
    {t:'match', q:'Verbinde die Gegenteile:', tr:{ru:'Соедини противоположности:',en:'Match the opposites:'},
      pairs:[['schnell','langsam'],['laut','leise'],['warm','kalt'],['schwer','leicht']], h:'adjektive', pts:4},
  ]},

{ id:'d4-lesen2', grade:4, subject:'german', icon:'🐿️',
  title:{de:'Leseverstehen: Das Eichhörnchen',ru:'Чтение: Белка',en:'Reading: The Squirrel'},
  desc:{de:'Ein zweiter Lesetext mit kniffligen Fragen',ru:'Второй текст с хитрыми вопросами',en:'A second reading text with tricky questions'},
  reading:{title:'Das Eichhörnchen – ein flinker Kletterer',
    text:`Das Eichhörnchen lebt in Wäldern und Parks. Mit seinem langen, buschigen Schwanz hält es beim Springen das Gleichgewicht – wie mit einem Steuerruder. Von Ast zu Ast schafft es Sprünge von bis zu fünf Metern!
Im Herbst ist das Eichhörnchen sehr fleißig: Es vergräbt Nüsse, Eicheln und Samen als Wintervorrat im Boden. Lustig ist: Viele Verstecke vergisst es wieder. Aus den vergessenen Nüssen wachsen im Frühling neue Bäume – so pflanzt das Eichhörnchen zufällig einen ganzen Wald!
Das Eichhörnchen hält KEINEN Winterschlaf, sondern nur Winterruhe: Es schläft viel, wacht aber immer wieder auf, um von seinen Vorräten zu fressen. Sein Nest aus Zweigen heißt Kobel.`},
  qs:[
    {t:'mc', q:'Wozu braucht das Eichhörnchen seinen buschigen Schwanz?', tr:{ru:'Зачем белке пушистый хвост?',en:'What does the squirrel need its bushy tail for?'}, opts:['zum Gleichgewicht halten beim Springen','zum Wärmen der Nüsse','zum Graben im Boden'], a:0, h:'lesen', pts:1},
    {t:'mc', q:'Wie weit kann ein Eichhörnchen springen?', tr:{ru:'Как далеко может прыгнуть белка?',en:'How far can a squirrel jump?'}, opts:['bis zu fünf Meter','bis zu fünfzig Meter','einen halben Meter'], a:0, h:'lesen', pts:1},
    {t:'mc', q:'Was macht das Eichhörnchen im Herbst?', tr:{ru:'Что белка делает осенью?',en:'What does the squirrel do in autumn?'}, opts:['Es vergräbt Vorräte im Boden.','Es fliegt in den Süden.','Es baut ein Haus aus Steinen.'], a:0, h:'lesen', pts:1},
    {t:'mc', q:'Warum wachsen durch das Eichhörnchen neue Bäume?', tr:{ru:'Почему благодаря белке вырастают новые деревья?',en:'Why do new trees grow because of the squirrel?'}, opts:['Es vergisst viele Nussverstecke.','Es gießt die Bäume.','Es sät absichtlich Samen.'], a:0, h:'lesen', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Das Eichhörnchen hält einen tiefen Winterschlaf."', tr:{ru:'Верно или неверно: «Белка впадает в глубокую зимнюю спячку».',en:'True or false: "The squirrel goes into deep hibernation."'}, a:false, h:'lesen', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Das Nest des Eichhörnchens heißt Kobel."', tr:{ru:'Верно или неверно: «Гнездо белки называется Kobel».',en:'True or false: "The squirrel’s nest is called Kobel."'}, a:true, h:'lesen', pts:1},
    {t:'mc', q:'Was frisst das Eichhörnchen im Winter?', tr:{ru:'Что белка ест зимой?',en:'What does the squirrel eat in winter?'}, opts:['seine vergrabenen Vorräte','frisches Gras','Insekten'], a:0, h:'lesen', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Der Schwanz funktioniert wie ein Steuerruder."', tr:{ru:'Верно или неверно: «Хвост работает как руль».',en:'True or false: "The tail works like a rudder."'}, a:true, h:'lesen', pts:1},
  ]},

{ id:'d5-woerter', grade:5, subject:'german', icon:'🔁',
  title:{de:'Synonyme & Antonyme',ru:'Синонимы и антонимы',en:'Synonyms & Antonyms'},
  desc:{de:'Wörter mit gleicher und entgegengesetzter Bedeutung',ru:'Слова с одинаковым и противоположным значением',en:'Words with same and opposite meaning'},
  qs:[
    {t:'mc', q:'Welches Wort ist ein SYNONYM für „sprechen"?', tr:{ru:'Какое слово – синоним „sprechen"?',en:'Which word is a synonym of "sprechen"?'}, opts:['reden','rennen','schlafen'], a:0, h:'synonyme', pts:1},
    {t:'mc', q:'Welches Wort ist ein SYNONYM für „schön"?', tr:{ru:'Какое слово – синоним „schön"?',en:'Which word is a synonym of "schön"?'}, opts:['hübsch','hässlich','laut'], a:0, h:'synonyme', pts:1},
    {t:'mc', q:'Welches Wort ist das GEGENTEIL von „mutig"?', tr:{ru:'Какое слово – антоним „mutig"?',en:'Which is the opposite of "mutig"?'}, opts:['ängstlich','stark','ehrlich'], a:0, h:'synonyme', pts:1},
    {t:'mc', q:'Apfel, Birne, Kirsche – wie heißt der OBERBEGRIFF?', tr:{ru:'Apfel, Birne, Kirsche – какое обобщающее слово?',en:'Apfel, Birne, Kirsche – what is the umbrella term?'}, opts:['Obst','Gemüse','Getränke'], a:0, h:'synonyme', pts:1},
    {t:'mc', q:'Hammer, Säge, Zange – wie heißt der OBERBEGRIFF?', tr:{ru:'Hammer, Säge, Zange – какое обобщающее слово?',en:'Hammer, Säge, Zange – what is the umbrella term?'}, opts:['Werkzeug','Spielzeug','Besteck'], a:0, h:'synonyme', pts:1},
    {t:'mc', q:'Welches Wort passt NICHT in die Reihe?\ngehen – laufen – rennen – singen', tr:{ru:'Какое слово лишнее? gehen – laufen – rennen – singen',en:'Which word does NOT fit? gehen – laufen – rennen – singen'}, opts:['singen','gehen','rennen'], a:0, h:'synonyme', pts:1},
    {t:'match', q:'Verbinde die Synonyme:', tr:{ru:'Соедини синонимы:',en:'Match the synonyms:'},
      pairs:[['froh','glücklich'],['müde','erschöpft'],['schauen','blicken'],['rufen','schreien']], h:'synonyme', pts:4},
    {t:'match', q:'Verbinde die Gegenteile:', tr:{ru:'Соедини антонимы:',en:'Match the opposites:'},
      pairs:[['Anfang','Ende'],['Sieg','Niederlage'],['Frage','Antwort'],['Lärm','Stille']], h:'synonyme', pts:4},
  ]},

{ id:'d5-diktat', grade:5, subject:'german', icon:'🕵️',
  title:{de:'Fehler-Detektiv',ru:'Детектив ошибок',en:'Mistake Detective'},
  desc:{de:'Finde das falsch geschriebene Wort!',ru:'Найди слово с ошибкой!',en:'Find the misspelled word!'},
  qs:[
    {t:'mc', q:'Welches Wort ist FALSCH geschrieben?\nfahren – Farrad – Fahrer – Abfahrt', tr:{ru:'Какое слово написано НЕПРАВИЛЬНО?',en:'Which word is spelled WRONG?'}, opts:['Farrad','fahren','Fahrer','Abfahrt'], a:0, h:'rechtIE', pts:1},
    {t:'mc', q:'Welches Wort ist FALSCH geschrieben?\nSommer – schwimen – Sonne – warm', tr:{ru:'Какое слово с ошибкой?',en:'Which word is spelled wrong?'}, opts:['schwimen','Sommer','Sonne','warm'], a:0, h:'rechtDoppel', pts:1},
    {t:'mc', q:'Welches Wort ist FALSCH geschrieben?\nStraße – Fluss – grosse – heißen', tr:{ru:'Какое слово с ошибкой?',en:'Which word is spelled wrong?'}, opts:['grosse','Straße','Fluss','heißen'], a:0, h:'rechtSS', pts:1},
    {t:'mc', q:'Welches Wort ist FALSCH geschrieben?\nKatze – Zucker – sitzen – bakken', tr:{ru:'Какое слово с ошибкой?',en:'Which word is spelled wrong?'}, opts:['bakken','Katze','Zucker','sitzen'], a:0, h:'rechtDoppel', pts:1},
    {t:'mc', q:'In welchem Satz sind ALLE Wörter richtig geschrieben?', tr:{ru:'В каком предложении ВСЕ слова написаны правильно?',en:'In which sentence are ALL words spelled correctly?'},
      opts:['Wir spielen im Sommer gern im Garten.','Wir spielen im Somer gern im Garten.','Wir spilen im Sommer gern im Garten.'], a:0, h:'rechtDoppel', pts:1},
    {t:'mc', q:'In welchem Satz sind ALLE Wörter richtig geschrieben?', tr:{ru:'В каком предложении ВСЕ слова написаны правильно?',en:'In which sentence are ALL words spelled correctly?'},
      opts:['Der Hund läuft schnell über die Wiese.','Der Hunt läuft schnell über die Wiese.','Der Hund läuft schnell über die Wise.'], a:0, h:'rechtEnd', pts:1},
    {t:'mc', q:'Welches Wort ist FALSCH geschrieben?\nStuhl – Zahl – fahren – Schtul', tr:{ru:'Какое слово с ошибкой?',en:'Which word is spelled wrong?'}, opts:['Schtul','Stuhl','Zahl','fahren'], a:0, h:'rechtIE', pts:1},
    {t:'mc', q:'Welches Wort ist FALSCH geschrieben?\nspielen – Wiese – sieben – schpielen', tr:{ru:'Какое слово с ошибкой?',en:'Which word is spelled wrong?'}, opts:['schpielen','spielen','Wiese','sieben'], a:0, h:'rechtIE', pts:1},
  ]},

{ id:'d5-lesen2', grade:5, subject:'german', icon:'🏰',
  title:{de:'Leseverstehen: Paderborn',ru:'Чтение: Падерборн',en:'Reading: Paderborn'},
  desc:{de:'Deine neue Heimatstadt – kennst du sie gut?',ru:'Твой город – хорошо ли ты его знаешь?',en:'Your city – do you know it well?'},
  reading:{title:'Paderborn – Stadt an der kürzesten Quelle Deutschlands',
    text:`Paderborn liegt in Ostwestfalen in Nordrhein-Westfalen. Die Stadt hat ihren Namen von der Pader – einem ganz besonderen Fluss: Mit nur etwa vier Kilometern Länge ist die Pader der kürzeste Fluss Deutschlands! Sie entspringt aus über 200 Quellen mitten in der Stadt.
Schon vor über 1.200 Jahren war Paderborn wichtig: Kaiser Karl der Große hielt hier im Jahr 777 einen großen Reichstag ab und ließ eine Pfalz bauen. Der hohe Dom mit seinem mächtigen Turm ist bis heute das Wahrzeichen der Stadt.
Berühmt ist auch das Heinz Nixdorf MuseumsForum – das größte Computermuseum der Welt! Dort kannst du sehen, wie aus riesigen Rechenmaschinen die heutigen Smartphones wurden. Paderborn ist also eine echte Computerstadt – perfekt für dein neues Schulfach Informatik!`},
  qs:[
    {t:'mc', q:'In welchem Landesteil liegt Paderborn?', tr:{ru:'В какой части земли находится Падерборн?',en:'In which region is Paderborn?'}, opts:['Ostwestfalen','Rheinland','Sauerland'], a:0, h:'lesen', pts:1},
    {t:'mc', q:'Was ist das Besondere an der Pader?', tr:{ru:'Чем особенна река Падер?',en:'What is special about the Pader?'}, opts:['Sie ist der kürzeste Fluss Deutschlands.','Sie ist der längste Fluss Deutschlands.','Sie ist der wärmste Fluss Europas.'], a:0, h:'lesen', pts:1},
    {t:'num', q:'Aus wie vielen Quellen entspringt die Pader ungefähr? (Zahl aus dem Text)', tr:{ru:'Из скольких источников берёт начало Падер? (число из текста)',en:'From about how many springs does the Pader rise? (number from the text)'}, a:200, h:'lesen', pts:1},
    {t:'mc', q:'Welcher Kaiser hielt 777 einen Reichstag in Paderborn ab?', tr:{ru:'Какой император провёл в Падерборне рейхстаг в 777 году?',en:'Which emperor held an assembly in Paderborn in 777?'}, opts:['Karl der Große','Otto der Erste','Napoleon'], a:0, h:'lesen', pts:1},
    {t:'mc', q:'Was ist das Wahrzeichen von Paderborn?', tr:{ru:'Что является символом Падерборна?',en:'What is Paderborn’s landmark?'}, opts:['der Dom','ein Fernsehturm','eine Brücke'], a:0, h:'lesen', pts:1},
    {t:'mc', q:'Was ist das Heinz Nixdorf MuseumsForum?', tr:{ru:'Что такое Heinz Nixdorf MuseumsForum?',en:'What is the Heinz Nixdorf MuseumsForum?'}, opts:['das größte Computermuseum der Welt','ein Fußballstadion','ein Schwimmbad'], a:0, h:'lesen', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Die Pader ist ungefähr vier Kilometer lang."', tr:{ru:'Верно или неверно: «Падер длиной около четырёх километров».',en:'True or false: "The Pader is about four kilometres long."'}, a:true, h:'lesen', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Paderborn wurde erst vor 100 Jahren gegründet."', tr:{ru:'Верно или неверно: «Падерборн основан всего 100 лет назад».',en:'True or false: "Paderborn was founded only 100 years ago."'}, a:false, h:'lesen', pts:1},
  ]},
];
