/* ============ Klasse 6–10: Physik · Chemie · Geschichte · Politik · Französisch
                             + Biologie · Erdkunde · Informatik ============ */
const TESTS_SUBJ_HIGH = [

/* ================= PHYSIK ================= */
{ id:'ph6-basics', grade:6, subject:'physik', icon:'🔭',
  title:{de:'Physik entdecken: Messen & Stoffe',ru:'Открываем физику: измерения',en:'Discovering Physics: Measuring'},
  desc:{de:'Größen, Einheiten und Aggregatzustände',ru:'Величины, единицы и состояния вещества',en:'Quantities, units and states of matter'},
  qs:[
    {t:'mc', q:'In welcher Einheit misst man die MASSE?', tr:{ru:'В каких единицах измеряют массу?',en:'Which unit measures mass?'}, opts:['Kilogramm (kg)','Newton (N)','Meter (m)'], a:0, h:'phMech', pts:1},
    {t:'mc', q:'In welcher Einheit misst man die KRAFT?', tr:{ru:'В каких единицах измеряют силу?',en:'Which unit measures force?'}, opts:['Newton (N)','Kilogramm (kg)','Volt (V)'], a:0, h:'phMech', pts:1},
    {t:'mc', q:'Wie heißt der Übergang von fest zu flüssig?', tr:{ru:'Как называется переход из твёрдого в жидкое?',en:'What is the change from solid to liquid called?'}, opts:['schmelzen','verdampfen','erstarren'], a:0, h:'phOptik', pts:1},
    {t:'mc', q:'Wie heißt der Übergang von flüssig zu gasförmig?', tr:{ru:'Переход из жидкого в газообразное?',en:'Liquid to gas is called ...'}, opts:['verdampfen','schmelzen','kondensieren'], a:0, h:'phOptik', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Stoffe dehnen sich aus, wenn man sie erwärmt."', tr:{ru:'Верно ли: вещества расширяются при нагревании?',en:'True or false: materials expand when heated?'}, a:true, h:'phOptik', pts:1},
    {t:'mc', q:'Was passiert mit den Teilchen, wenn ein Stoff wärmer wird?', tr:{ru:'Что происходит с частицами при нагревании?',en:'What happens to particles when heated?'}, opts:['Sie bewegen sich schneller.','Sie bleiben stehen.','Sie verschwinden.'], a:0, h:'chStoffe', pts:1},
    {t:'num', q:'Wasser gefriert bei wie viel °C?', tr:{ru:'При скольких °C замерзает вода?',en:'Water freezes at how many °C?'}, a:0, unit:'°C', h:'phOptik', pts:1},
    {t:'match', q:'Verbinde Größe und Einheit:', tr:{ru:'Соедини величину и единицу:',en:'Match quantity and unit:'},
      pairs:[['Länge','Meter'],['Masse','Kilogramm'],['Zeit','Sekunde'],['Kraft','Newton']], h:'phMech', pts:4},
  ]},

{ id:'ph7-optik', grade:7, subject:'physik', icon:'🔦',
  title:{de:'Optik: Licht & Schatten',ru:'Оптика: свет и тень',en:'Optics: Light & Shadow'},
  desc:{de:'Reflexion, Brechung und Linsen',ru:'Отражение, преломление и линзы',en:'Reflection, refraction and lenses'},
  qs:[
    {t:'mc', q:'Wie breitet sich Licht aus?', tr:{ru:'Как распространяется свет?',en:'How does light travel?'}, opts:['geradlinig','in Wellenlinien','im Kreis'], a:0, h:'phOptik', pts:1},
    {t:'mc', q:'Wie lautet das Reflexionsgesetz?', tr:{ru:'Как звучит закон отражения?',en:'What is the law of reflection?'}, opts:['Einfallswinkel = Ausfallswinkel','Einfallswinkel = 90°','Der Winkel halbiert sich'], a:0, h:'phOptik', pts:1},
    {t:'mc', q:'Warum sieht ein Stab im Wasser geknickt aus?', tr:{ru:'Почему палка в воде кажется сломанной?',en:'Why does a stick look bent in water?'}, opts:['wegen der Lichtbrechung','wegen der Schwerkraft','weil er wirklich bricht'], a:0, h:'phOptik', pts:1},
    {t:'mc', q:'Was macht eine Sammellinse mit dem Licht?', tr:{ru:'Что делает собирающая линза со светом?',en:'What does a converging lens do?'}, opts:['bündelt es im Brennpunkt','streut es überall hin','verschluckt es'], a:0, h:'phOptik', pts:1},
    {t:'mc', q:'Wann entsteht ein Schatten?', tr:{ru:'Когда возникает тень?',en:'When does a shadow appear?'}, opts:['Wenn ein Körper das Licht blockiert','Wenn es dunkel ist','Wenn Licht reflektiert wird'], a:0, h:'phOptik', pts:1},
    {t:'mc', q:'Welche Farben ergeben zusammen weißes Licht?', tr:{ru:'Какие цвета вместе дают белый свет?',en:'Which colours together make white light?'}, opts:['alle Spektralfarben','nur Rot und Blau','Schwarz und Weiß'], a:0, h:'phOptik', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Der Mond leuchtet selbst."', tr:{ru:'Верно ли: Луна светится сама?',en:'True or false: the moon shines by itself?'}, a:false, h:'phOptik', pts:1},
    {t:'mc', q:'Wie schnell ist Licht ungefähr?', tr:{ru:'Какова примерно скорость света?',en:'How fast is light approximately?'}, opts:['300.000 km pro Sekunde','300 km pro Stunde','1.000 km pro Sekunde'], a:0, h:'phOptik', pts:1},
  ]},

{ id:'ph8-strom', grade:8, subject:'physik', icon:'⚡', genTest:true,
  title:{de:'Elektrizität & Ohmsches Gesetz',ru:'Электричество и закон Ома',en:'Electricity & Ohm’s Law'},
  desc:{de:'Spannung, Stromstärke und Widerstand',ru:'Напряжение, сила тока и сопротивление',en:'Voltage, current and resistance'},
  gen(){ return [qOhm(),qOhm(),
    {t:'mc', q:'Wie lautet das Ohmsche Gesetz?', tr:{ru:'Как звучит закон Ома?',en:'What is Ohm’s law?'}, opts:['U = R · I','U = R : I','U = R + I'], a:0, h:'phStrom', pts:1},
    {t:'mc', q:'In welcher Einheit misst man die Spannung?', tr:{ru:'В каких единицах измеряют напряжение?',en:'Which unit measures voltage?'}, opts:['Volt (V)','Ampere (A)','Ohm (Ω)'], a:0, h:'phStrom', pts:1},
    {t:'mc', q:'In welcher Einheit misst man die Stromstärke?', tr:{ru:'В каких единицах измеряют силу тока?',en:'Which unit measures current?'}, opts:['Ampere (A)','Volt (V)','Watt (W)'], a:0, h:'phStrom', pts:1},
    {t:'mc', q:'Was passiert in einer REIHENSCHALTUNG, wenn eine Lampe kaputtgeht?', tr:{ru:'Что будет в последовательной цепи, если лампа перегорит?',en:'In a series circuit, what happens if one bulb breaks?'}, opts:['Alle Lampen gehen aus.','Nur diese Lampe geht aus.','Nichts passiert.'], a:0, h:'phStrom', pts:1},
    {t:'mc', q:'Wie berechnet man die elektrische Leistung?', tr:{ru:'Как считают электрическую мощность?',en:'How do you calculate electrical power?'}, opts:['P = U · I','P = U : I','P = U + I'], a:0, h:'phStrom', pts:1},
    {t:'num', q:'U = 12 V und R = 4 Ω. Berechne die Stromstärke I.  (I = U : R)', tr:{ru:'U = 12 В, R = 4 Ом. Найди I. (I = U:R)',en:'U = 12 V, R = 4 Ω. Find I.'}, a:3, unit:'A', h:'phStrom', pts:2},
    {t:'tf', q:'Richtig oder falsch?\n„In einer Parallelschaltung liegt an allen Bauteilen die gleiche Spannung an."', tr:{ru:'Верно ли: при параллельном соединении напряжение одинаково?',en:'True or false: in a parallel circuit the voltage is the same everywhere?'}, a:true, h:'phStrom', pts:1}]; } },

{ id:'ph9-mech', grade:9, subject:'physik', icon:'⚙️', genTest:true,
  title:{de:'Mechanik: Kraft, Dichte, Energie',ru:'Механика: сила, плотность, энергия',en:'Mechanics: Force, Density, Energy'},
  desc:{de:'Rechnen mit Formeln wie ein Ingenieur',ru:'Считаем по формулам как инженер',en:'Calculating with formulas like an engineer'},
  gen(){ return [qDensity(),qDensity(),qSpeed(),qSpeed(),
    {t:'mc', q:'Wie berechnet man die Dichte?', tr:{ru:'Как вычисляют плотность?',en:'How do you calculate density?'}, opts:['ρ = m : V','ρ = m · V','ρ = V : m'], a:0, h:'phMech', pts:1},
    {t:'mc', q:'Warum schwimmt Holz auf Wasser?', tr:{ru:'Почему дерево плавает на воде?',en:'Why does wood float on water?'}, opts:['Die Dichte ist kleiner als die von Wasser.','Holz ist leichter als Luft.','Holz hat keine Masse.'], a:0, h:'phMech', pts:1},
    {t:'num', q:'Ein Körper hat die Masse 5 kg. Wie groß ist die Gewichtskraft?  (F = m · g, g = 10 N/kg)', tr:{ru:'Масса 5 кг. Найди силу тяжести (g = 10 Н/кг).',en:'Mass 5 kg. Find the weight force (g = 10 N/kg).'}, a:50, unit:'N', h:'phMech', pts:2},
    {t:'mc', q:'Wie lautet das Hebelgesetz?', tr:{ru:'Как звучит правило рычага?',en:'What is the lever law?'}, opts:['Kraft · Kraftarm = Last · Lastarm','Kraft + Last = 0','Kraft = Last'], a:0, h:'phMech', pts:1},
    {t:'mc', q:'Welche Energieform hat ein hochgehobener Stein?', tr:{ru:'Какая энергия у поднятого камня?',en:'Which energy does a lifted stone have?'}, opts:['Lageenergie (potenzielle Energie)','Bewegungsenergie','Wärmeenergie'], a:0, h:'phMech', pts:1}]; } },

{ id:'ph10-final', grade:10, subject:'physik', icon:'🎓', genTest:true,
  title:{de:'Physik-Abschlusstest',ru:'Итоговый тест по физике',en:'Physics Final Test'},
  desc:{de:'Mechanik, Strom und Optik gemischt',ru:'Механика, электричество и оптика',en:'Mechanics, electricity and optics mixed'},
  gen(){ return [qOhm(),qDensity(),qSpeed(),
    {t:'mc', q:'Einheit der elektrischen Leistung?', tr:{ru:'Единица электрической мощности?',en:'Unit of electrical power?'}, opts:['Watt (W)','Volt (V)','Ohm (Ω)'], a:0, h:'phStrom', pts:1},
    {t:'mc', q:'Was gilt für Energie in einem geschlossenen System?', tr:{ru:'Что верно об энергии в замкнутой системе?',en:'What is true about energy in a closed system?'}, opts:['Sie bleibt erhalten, wandelt sich aber um.','Sie verschwindet.','Sie entsteht neu.'], a:0, h:'phMech', pts:1},
    {t:'mc', q:'Einfallswinkel 30° – wie groß ist der Ausfallswinkel?', tr:{ru:'Угол падения 30° – каков угол отражения?',en:'Angle of incidence 30° – angle of reflection?'}, opts:['30°','60°','90°'], a:0, h:'phOptik', pts:1},
    {t:'num', q:'Ein Auto fährt 90 km/h. Wie viele km schafft es in 3 Stunden?', tr:{ru:'Машина едет 90 км/ч. Сколько км за 3 часа?',en:'A car drives 90 km/h. How far in 3 hours?'}, a:270, unit:'km', h:'speed', pts:2}]; } },

/* ================= CHEMIE ================= */
{ id:'ch7-stoffe', grade:7, subject:'chemie', icon:'🧪',
  title:{de:'Stoffe & Trennverfahren',ru:'Вещества и способы разделения',en:'Substances & Separation'},
  desc:{de:'Reinstoffe, Gemische und wie man sie trennt',ru:'Чистые вещества, смеси и их разделение',en:'Pure substances, mixtures and separation'},
  qs:[
    {t:'mc', q:'Was ist ein REINSTOFF?', tr:{ru:'Что такое чистое вещество?',en:'What is a pure substance?'}, opts:['ein Stoff aus nur einer Teilchensorte','eine Mischung aus mehreren Stoffen','immer eine Flüssigkeit'], a:0, h:'chStoffe', pts:1},
    {t:'mc', q:'Welches ist ein GEMISCH?', tr:{ru:'Что является смесью?',en:'Which one is a mixture?'}, opts:['Luft','Eisen','Sauerstoff'], a:0, h:'chStoffe', pts:1},
    {t:'mc', q:'Wie trennt man Sand von Wasser?', tr:{ru:'Как отделить песок от воды?',en:'How do you separate sand from water?'}, opts:['filtrieren','destillieren','magnetisieren'], a:0, h:'chStoffe', pts:1},
    {t:'mc', q:'Wie gewinnt man Salz aus Salzwasser?', tr:{ru:'Как получить соль из солёной воды?',en:'How do you get salt from salt water?'}, opts:['eindampfen','filtrieren','sieben'], a:0, h:'chStoffe', pts:1},
    {t:'mc', q:'Wie trennt man Eisenspäne von Sand?', tr:{ru:'Как отделить железные опилки от песка?',en:'How do you separate iron filings from sand?'}, opts:['mit einem Magneten','durch Filtrieren','durch Erhitzen'], a:0, h:'chStoffe', pts:1},
    {t:'mc', q:'Im Teilchenmodell: Wie sind die Teilchen in einem FESTKÖRPER?', tr:{ru:'Как расположены частицы в твёрдом теле?',en:'How are particles arranged in a solid?'}, opts:['dicht und geordnet','weit auseinander','völlig frei'], a:0, h:'chStoffe', pts:1},
    {t:'mc', q:'Welche Eigenschaft ist ein STOFFEIGENSCHAFT?', tr:{ru:'Что относится к свойствам вещества?',en:'Which is a property of a substance?'}, opts:['Schmelztemperatur','die Form des Gefäßes','das Gewicht der Verpackung'], a:0, h:'chStoffe', pts:1},
    {t:'match', q:'Verbinde Trennverfahren und Anwendung:', tr:{ru:'Соедини способ и применение:',en:'Match method and use:'},
      pairs:[['Filtrieren','Sand aus Wasser'],['Eindampfen','Salz aus Salzwasser'],['Destillieren','Alkohol von Wasser'],['Magnet','Eisen aus Sand']], h:'chStoffe', pts:4},
  ]},

{ id:'ch8-atom', grade:8, subject:'chemie', icon:'⚛️',
  title:{de:'Atome & chemische Reaktionen',ru:'Атомы и химические реакции',en:'Atoms & Chemical Reactions'},
  desc:{de:'Aufbau der Atome und was bei Reaktionen passiert',ru:'Строение атома и реакции',en:'Atomic structure and reactions'},
  qs:[
    {t:'mc', q:'Woraus besteht der Atomkern?', tr:{ru:'Из чего состоит ядро атома?',en:'What is the nucleus made of?'}, opts:['Protonen und Neutronen','nur Elektronen','nur Protonen'], a:0, h:'chAtom', pts:1},
    {t:'mc', q:'Welche Ladung haben Elektronen?', tr:{ru:'Какой заряд у электронов?',en:'What charge do electrons have?'}, opts:['negativ','positiv','neutral'], a:0, h:'chAtom', pts:1},
    {t:'mc', q:'Was gibt die Ordnungszahl im Periodensystem an?', tr:{ru:'Что показывает порядковый номер?',en:'What does the atomic number tell you?'}, opts:['die Anzahl der Protonen','das Gewicht in Gramm','die Anzahl der Moleküle'], a:0, h:'chAtom', pts:1},
    {t:'mc', q:'Was ist die chemische Formel für Wasser?', tr:{ru:'Химическая формула воды?',en:'Chemical formula of water?'}, opts:['H₂O','CO₂','O₂'], a:0, h:'chAtom', pts:1},
    {t:'mc', q:'Wofür steht CO₂?', tr:{ru:'Что означает CO₂?',en:'What does CO₂ stand for?'}, opts:['Kohlenstoffdioxid','Sauerstoff','Kochsalz'], a:0, h:'chAtom', pts:1},
    {t:'mc', q:'Was entsteht bei einer chemischen Reaktion?', tr:{ru:'Что образуется при химической реакции?',en:'What forms in a chemical reaction?'}, opts:['neue Stoffe','nur Wärme','nichts Neues'], a:0, h:'chAtom', pts:1},
    {t:'mc', q:'Wie nennt man eine Reaktion, bei der Energie FREI wird?', tr:{ru:'Как называется реакция с выделением энергии?',en:'What is a reaction that releases energy called?'}, opts:['exotherm','endotherm','neutral'], a:0, h:'chAtom', pts:1},
    {t:'mc', q:'Was passiert bei einer Verbrennung?', tr:{ru:'Что происходит при горении?',en:'What happens during combustion?'}, opts:['Ein Stoff reagiert mit Sauerstoff.','Ein Stoff verschwindet.','Wasser entsteht aus nichts.'], a:0, h:'chAtom', pts:1},
    {t:'match', q:'Verbinde Formel und Stoff:', tr:{ru:'Соедини формулу и вещество:',en:'Match formula and substance:'},
      pairs:[['H₂O','Wasser'],['CO₂','Kohlenstoffdioxid'],['O₂','Sauerstoff'],['NaCl','Kochsalz']], h:'chAtom', pts:4},
  ]},

{ id:'ch9-saeuren', grade:9, subject:'chemie', icon:'🧫',
  title:{de:'Säuren, Laugen & Salze',ru:'Кислоты, щёлочи и соли',en:'Acids, Bases & Salts'},
  desc:{de:'pH-Wert und Neutralisation',ru:'pH и нейтрализация',en:'pH value and neutralisation'},
  qs:[
    {t:'mc', q:'Welchen pH-Wert haben SÄUREN?', tr:{ru:'Какой pH у кислот?',en:'What pH do acids have?'}, opts:['unter 7','genau 7','über 7'], a:0, h:'chAtom', pts:1},
    {t:'mc', q:'Welchen pH-Wert haben LAUGEN (Basen)?', tr:{ru:'Какой pH у щелочей?',en:'What pH do bases have?'}, opts:['über 7','unter 7','genau 7'], a:0, h:'chAtom', pts:1},
    {t:'mc', q:'Welchen pH-Wert hat reines Wasser?', tr:{ru:'Какой pH у чистой воды?',en:'What is the pH of pure water?'}, opts:['7 (neutral)','1','14'], a:0, h:'chAtom', pts:1},
    {t:'mc', q:'Womit weist man Säuren und Laugen nach?', tr:{ru:'Чем определяют кислоты и щёлочи?',en:'How do you test for acids and bases?'}, opts:['mit einem Indikator (z. B. Lackmus)','mit einem Magneten','mit einem Thermometer'], a:0, h:'chAtom', pts:1},
    {t:'mc', q:'Was entsteht bei einer Neutralisation von Säure und Lauge?', tr:{ru:'Что образуется при нейтрализации?',en:'What forms in a neutralisation?'}, opts:['Salz und Wasser','nur Gas','nur Wärme'], a:0, h:'chAtom', pts:2},
    {t:'mc', q:'Welche Säure ist in Zitronen?', tr:{ru:'Какая кислота в лимонах?',en:'Which acid is in lemons?'}, opts:['Zitronensäure','Salzsäure','Schwefelsäure'], a:0, h:'chAtom', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Säuren sind gefährlich und dürfen nur mit Schutzbrille verwendet werden."', tr:{ru:'Верно ли: с кислотами работают только в защитных очках?',en:'True or false: acids require safety goggles?'}, a:true, h:'chAtom', pts:1},
    {t:'mc', q:'Welche Lauge steckt in vielen Reinigungsmitteln?', tr:{ru:'Какая щёлочь есть в чистящих средствах?',en:'Which base is in many cleaning products?'}, opts:['Natronlauge','Zitronensäure','Essigsäure'], a:0, h:'chAtom', pts:1},
  ]},

/* ================= GESCHICHTE ================= */
{ id:'ge6-antike', grade:6, subject:'geschichte', icon:'🏛️',
  title:{de:'Antike: Ägypten, Griechen, Römer',ru:'Древний мир: Египет, Греция, Рим',en:'Antiquity: Egypt, Greece, Rome'},
  desc:{de:'Die ersten Hochkulturen der Menschheit',ru:'Первые цивилизации человечества',en:'The first great civilisations'},
  qs:[
    {t:'mc', q:'An welchem Fluss lag das alte Ägypten?', tr:{ru:'На какой реке был Древний Египет?',en:'On which river was ancient Egypt?'}, opts:['am Nil','am Rhein','am Tiber'], a:0, h:'gesAntike', pts:1},
    {t:'mc', q:'Wie nannte man die Herrscher Ägyptens?', tr:{ru:'Как называли правителей Египта?',en:'What were Egypt’s rulers called?'}, opts:['Pharaonen','Kaiser','Könige von Athen'], a:0, h:'gesAntike', pts:1},
    {t:'mc', q:'In welcher Stadt entstand die DEMOKRATIE?', tr:{ru:'В каком городе возникла демократия?',en:'In which city did democracy begin?'}, opts:['Athen','Rom','Sparta'], a:0, h:'gesAntike', pts:1},
    {t:'mc', q:'Was bedeutet „Demokratie"?', tr:{ru:'Что означает «демократия»?',en:'What does "democracy" mean?'}, opts:['Herrschaft des Volkes','Herrschaft eines Königs','Herrschaft der Reichen'], a:0, h:'gesAntike', pts:1},
    {t:'num', q:'In welchem Jahr v. Chr. fanden die ersten Olympischen Spiele statt?', tr:{ru:'В каком году до н.э. прошли первые Олимпийские игры?',en:'In which year BC were the first Olympic Games?'}, a:776, h:'gesAntike', pts:1},
    {t:'mc', q:'Wie hieß die Volksversammlung der Römer, die Gesetze beriet?', tr:{ru:'Как назывался римский совет знати?',en:'What was the Roman council called?'}, opts:['der Senat','die Polis','das Forum Romanum'], a:0, h:'gesAntike', pts:1},
    {t:'mc', q:'Wer war der erste römische Kaiser?', tr:{ru:'Кто был первым римским императором?',en:'Who was the first Roman emperor?'}, opts:['Augustus','Cäsar','Nero'], a:0, h:'gesAntike', pts:1},
    {t:'mc', q:'Wie zählt man Jahre vor Christus?', tr:{ru:'Как считают годы до нашей эры?',en:'How do you count years BC?'}, opts:['rückwärts – je größer die Zahl, desto früher','vorwärts wie heute','gar nicht'], a:0, h:'gesAntike', pts:1},
    {t:'match', q:'Verbinde Kultur und Erfindung/Bauwerk:', tr:{ru:'Соедини культуру и изобретение:',en:'Match culture and achievement:'},
      pairs:[['Ägypten','Pyramiden'],['Griechenland','Olympische Spiele'],['Rom','Aquädukte'],['Ägypten (Schrift)','Hieroglyphen']], h:'gesAntike', pts:4},
  ]},

{ id:'ge7-mittelalter', grade:7, subject:'geschichte', icon:'🏰',
  title:{de:'Mittelalter: Ritter, Burgen, Städte',ru:'Средневековье: рыцари и города',en:'Middle Ages: Knights, Castles, Towns'},
  desc:{de:'Lehnswesen, Stände und das Leben auf der Burg',ru:'Феодализм, сословия и жизнь в замке',en:'Feudalism, estates and castle life'},
  qs:[
    {t:'mc', q:'Was bekam ein Adliger vom König im Lehnswesen?', tr:{ru:'Что получал дворянин от короля?',en:'What did a noble get from the king?'}, opts:['Land (ein Lehen)','Gold aus der Kirche','ein Schiff'], a:0, h:'gesMittelalter', pts:1},
    {t:'mc', q:'Was schuldete der Adlige dem König dafür?', tr:{ru:'Что он был должен королю взамен?',en:'What did the noble owe in return?'}, opts:['Treue und Kriegsdienst','Steuern in Gold','nichts'], a:0, h:'gesMittelalter', pts:1},
    {t:'mc', q:'Welcher Stand war im Mittelalter der größte?', tr:{ru:'Какое сословие было самым большим?',en:'Which estate was the largest?'}, opts:['die Bauern','der Adel','der Klerus'], a:0, h:'gesMittelalter', pts:1},
    {t:'mc', q:'Was bedeutet „Stadtluft macht frei"?', tr:{ru:'Что значит «городской воздух делает свободным»?',en:'What does "town air makes you free" mean?'}, opts:['Wer ein Jahr in der Stadt lebte, war kein Leibeigener mehr.','In der Stadt war die Luft sauberer.','Städter mussten keine Steuern zahlen.'], a:0, h:'gesMittelalter', pts:2},
    {t:'mc', q:'Wie nannte man den Zusammenschluss von Handwerkern?', tr:{ru:'Как назывались объединения ремесленников?',en:'What were craftsmen’s associations called?'}, opts:['Zunft','Senat','Orden'], a:0, h:'gesMittelalter', pts:1},
    {t:'mc', q:'Wie lautete der Leitspruch der Mönche?', tr:{ru:'Каким был девиз монахов?',en:'What was the monks’ motto?'}, opts:['ora et labora (bete und arbeite)','veni vidi vici','carpe diem'], a:0, h:'gesMittelalter', pts:1},
    {t:'mc', q:'Wer erfand um 1450 den Buchdruck mit beweglichen Lettern?', tr:{ru:'Кто около 1450 изобрёл книгопечатание?',en:'Who invented printing with movable type around 1450?'}, opts:['Johannes Gutenberg','Martin Luther','Karl der Große'], a:0, h:'gesMittelalter', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Im Mittelalter konnte fast jeder lesen und schreiben."', tr:{ru:'Верно ли: в Средневековье почти все умели читать?',en:'True or false: nearly everyone could read in the Middle Ages?'}, a:false, h:'gesMittelalter', pts:1},
  ]},

{ id:'ge8-neuzeit', grade:8, subject:'geschichte', icon:'🚢',
  title:{de:'Neuzeit: Entdeckungen & Revolution',ru:'Новое время: открытия и революция',en:'Modern Era: Discoveries & Revolution'},
  desc:{de:'Kolumbus, Luther, Französische Revolution',ru:'Колумб, Лютер, Французская революция',en:'Columbus, Luther, French Revolution'},
  qs:[
    {t:'num', q:'In welchem Jahr erreichte Kolumbus Amerika?', tr:{ru:'В каком году Колумб достиг Америки?',en:'In which year did Columbus reach America?'}, a:1492, h:'gesNeuzeit', pts:1},
    {t:'num', q:'In welchem Jahr veröffentlichte Martin Luther seine 95 Thesen?', tr:{ru:'В каком году Лютер опубликовал 95 тезисов?',en:'In which year did Luther publish his 95 theses?'}, a:1517, h:'gesNeuzeit', pts:1},
    {t:'mc', q:'Was folgte aus Luthers Thesen?', tr:{ru:'Что последовало за тезисами Лютера?',en:'What followed from Luther’s theses?'}, opts:['die Reformation und die Spaltung der Kirche','ein neuer Kaiser','die Entdeckung Amerikas'], a:0, h:'gesNeuzeit', pts:1},
    {t:'num', q:'In welchem Jahr begann die Französische Revolution?', tr:{ru:'В каком году началась Французская революция?',en:'In which year did the French Revolution begin?'}, a:1789, h:'gesNeuzeit', pts:1},
    {t:'mc', q:'Wie lautete der Wahlspruch der Französischen Revolution?', tr:{ru:'Каким был девиз Французской революции?',en:'What was the motto of the French Revolution?'}, opts:['Freiheit, Gleichheit, Brüderlichkeit','Blut und Eisen','Gott mit uns'], a:0, h:'gesNeuzeit', pts:1},
    {t:'mc', q:'Welche Erfindung trieb die Industrialisierung an?', tr:{ru:'Какое изобретение двигало индустриализацию?',en:'Which invention drove industrialisation?'}, opts:['die Dampfmaschine','das Telefon','der Computer'], a:0, h:'gesNeuzeit', pts:1},
    {t:'mc', q:'Was sagte Kopernikus über die Erde?', tr:{ru:'Что Коперник сказал о Земле?',en:'What did Copernicus say about the earth?'}, opts:['Sie kreist um die Sonne.','Sie ist der Mittelpunkt der Welt.','Sie ist eine Scheibe.'], a:0, h:'gesNeuzeit', pts:1},
    {t:'mc', q:'Was war die „soziale Frage" der Industrialisierung?', tr:{ru:'Что такое «социальный вопрос» индустриализации?',en:'What was the "social question"?'}, opts:['die schlechten Lebensbedingungen der Arbeiter','die Frage nach neuen Kolonien','der Streit um die Kirche'], a:0, h:'gesNeuzeit', pts:1},
  ]},

{ id:'ge9-20jh', grade:9, subject:'geschichte', icon:'🕰️',
  title:{de:'20. Jahrhundert: Kriege & Demokratie',ru:'XX век: войны и демократия',en:'20th Century: Wars & Democracy'},
  desc:{de:'Weltkriege, NS-Zeit und geteiltes Deutschland',ru:'Мировые войны, нацизм и разделённая Германия',en:'World wars, Nazi era and divided Germany'},
  qs:[
    {t:'num', q:'In welchem Jahr begann der Erste Weltkrieg?', tr:{ru:'В каком году началась Первая мировая война?',en:'In which year did World War I begin?'}, a:1914, h:'ges20', pts:1},
    {t:'num', q:'In welchem Jahr endete der Zweite Weltkrieg?', tr:{ru:'В каком году закончилась Вторая мировая война?',en:'In which year did World War II end?'}, a:1945, h:'ges20', pts:1},
    {t:'mc', q:'Wie hieß die erste deutsche Demokratie (ab 1919)?', tr:{ru:'Как называлась первая немецкая демократия?',en:'What was Germany’s first democracy called?'}, opts:['Weimarer Republik','Bundesrepublik','Deutsches Kaiserreich'], a:0, h:'ges20', pts:1},
    {t:'mc', q:'Was geschah 1933 in Deutschland?', tr:{ru:'Что произошло в Германии в 1933 году?',en:'What happened in Germany in 1933?'}, opts:['Die Nationalsozialisten kamen an die Macht und zerstörten die Demokratie.','Deutschland wurde wiedervereinigt.','Die Mauer fiel.'], a:0, h:'ges20', pts:2},
    {t:'mc', q:'Was war der Holocaust?', tr:{ru:'Что такое Холокост?',en:'What was the Holocaust?'}, opts:['die systematische Verfolgung und Ermordung der Juden','eine Schlacht','ein Friedensvertrag'], a:0, h:'ges20', pts:2},
    {t:'num', q:'In welchem Jahr fiel die Berliner Mauer?', tr:{ru:'В каком году пала Берлинская стена?',en:'In which year did the Berlin Wall fall?'}, a:1989, h:'ges20', pts:1},
    {t:'num', q:'In welchem Jahr wurde Deutschland wiedervereinigt?', tr:{ru:'В каком году Германия объединилась?',en:'In which year was Germany reunified?'}, a:1990, h:'ges20', pts:1},
    {t:'mc', q:'Welche Lehre zieht Deutschland aus der NS-Zeit?', tr:{ru:'Какой урок Германия извлекла из нацизма?',en:'What lesson does Germany draw from the Nazi era?'}, opts:['Menschenwürde und Demokratie müssen geschützt werden.','Man soll die Geschichte vergessen.','Diktaturen sind effizient.'], a:0, h:'ges20', pts:1},
    {t:'match', q:'Verbinde Jahr und Ereignis:', tr:{ru:'Соедини год и событие:',en:'Match year and event:'},
      pairs:[['1914','Beginn 1. Weltkrieg'],['1939','Beginn 2. Weltkrieg'],['1961','Bau der Berliner Mauer'],['1989','Mauerfall']], h:'ges20', pts:4},
  ]},

/* ================= POLITIK / WIRTSCHAFT ================= */
{ id:'po7-demo', grade:7, subject:'politik', icon:'🗳️',
  title:{de:'Demokratie & Grundgesetz',ru:'Демократия и Основной закон',en:'Democracy & Constitution'},
  desc:{de:'Wie Deutschland regiert wird',ru:'Как управляется Германия',en:'How Germany is governed'},
  qs:[
    {t:'mc', q:'Wie heißt die Verfassung Deutschlands?', tr:{ru:'Как называется конституция Германии?',en:'What is Germany’s constitution called?'}, opts:['Grundgesetz','Bundesbuch','Verfassungsvertrag'], a:0, h:'polDemokratie', pts:1},
    {t:'mc', q:'Was steht in Artikel 1 des Grundgesetzes?', tr:{ru:'Что написано в статье 1 Основного закона?',en:'What does Article 1 say?'}, opts:['Die Würde des Menschen ist unantastbar.','Alle zahlen Steuern.','Deutschland ist eine Monarchie.'], a:0, h:'polDemokratie', pts:1},
    {t:'mc', q:'Welche drei Gewalten gibt es?', tr:{ru:'Какие три ветви власти существуют?',en:'What are the three powers?'}, opts:['Legislative, Exekutive, Judikative','Bund, Land, Gemeinde','Partei, Presse, Polizei'], a:0, h:'polDemokratie', pts:1},
    {t:'mc', q:'Wer macht die Gesetze?', tr:{ru:'Кто принимает законы?',en:'Who makes the laws?'}, opts:['der Bundestag','die Gerichte','die Polizei'], a:0, h:'polDemokratie', pts:1},
    {t:'mc', q:'Wer wählt den Bundeskanzler?', tr:{ru:'Кто выбирает канцлера?',en:'Who elects the chancellor?'}, opts:['der Bundestag','das Volk direkt','der Bundespräsident allein'], a:0, h:'polDemokratie', pts:1},
    {t:'mc', q:'Alle wie viele Jahre wird der Bundestag gewählt?', tr:{ru:'Раз в сколько лет выбирают Бундестаг?',en:'How often is the Bundestag elected?'}, opts:['alle 4 Jahre','alle 2 Jahre','alle 10 Jahre'], a:0, h:'polDemokratie', pts:1},
    {t:'mc', q:'Welcher Wahlgrundsatz bedeutet, dass niemand sieht, was du wählst?', tr:{ru:'Какой принцип означает тайну голосования?',en:'Which principle means nobody sees your vote?'}, opts:['geheim','frei','gleich'], a:0, h:'polDemokratie', pts:1},
    {t:'num', q:'Wie viele Bundesländer hat Deutschland?', tr:{ru:'Сколько федеральных земель в Германии?',en:'How many federal states does Germany have?'}, a:16, h:'polDemokratie', pts:1},
  ]},

{ id:'po9-wirt', grade:9, subject:'politik', icon:'💶',
  title:{de:'Wirtschaft & Europa',ru:'Экономика и Европа',en:'Economy & Europe'},
  desc:{de:'Markt, Sozialsystem und die EU',ru:'Рынок, соцсистема и ЕС',en:'Market, social system and the EU'},
  qs:[
    {t:'mc', q:'Was passiert mit dem Preis, wenn die Nachfrage steigt und das Angebot knapp ist?', tr:{ru:'Что будет с ценой при высоком спросе и малом предложении?',en:'What happens to the price when demand rises and supply is scarce?'}, opts:['Er steigt.','Er sinkt.','Er bleibt gleich.'], a:0, h:'polWirtschaft', pts:1},
    {t:'mc', q:'Wie heißt das deutsche Wirtschaftssystem?', tr:{ru:'Как называется экономическая система Германии?',en:'What is Germany’s economic system called?'}, opts:['soziale Marktwirtschaft','Planwirtschaft','reine Marktwirtschaft'], a:0, h:'polWirtschaft', pts:1},
    {t:'mc', q:'Welche gehört NICHT zu den fünf Sozialversicherungen?', tr:{ru:'Что НЕ относится к пяти видам соцстрахования?',en:'Which is NOT one of the five social insurances?'}, opts:['Hausratversicherung','Krankenversicherung','Rentenversicherung'], a:0, h:'polWirtschaft', pts:1},
    {t:'mc', q:'Wofür werden Steuern verwendet?', tr:{ru:'На что идут налоги?',en:'What are taxes used for?'}, opts:['für Schulen, Straßen, Polizei','nur für Politikergehälter','für nichts'], a:0, h:'polWirtschaft', pts:1},
    {t:'num', q:'Wie viele Mitgliedsländer hat die EU (Stand 2024)?', tr:{ru:'Сколько стран в ЕС (2024)?',en:'How many member states does the EU have (2024)?'}, a:27, h:'polWirtschaft', pts:1},
    {t:'mc', q:'Was ist der Euro?', tr:{ru:'Что такое евро?',en:'What is the euro?'}, opts:['die gemeinsame Währung vieler EU-Länder','eine Behörde','ein Vertrag'], a:0, h:'polWirtschaft', pts:1},
    {t:'mc', q:'Was ist das Europäische Parlament?', tr:{ru:'Что такое Европарламент?',en:'What is the European Parliament?'}, opts:['die gewählte Vertretung der EU-Bürger','ein Gericht','eine Bank'], a:0, h:'polWirtschaft', pts:1},
    {t:'mc', q:'Was bedeutet Binnenmarkt?', tr:{ru:'Что значит единый рынок?',en:'What does single market mean?'}, opts:['freier Verkehr von Waren, Personen, Dienstleistungen und Kapital','ein großer Supermarkt','ein Markt nur für Lebensmittel'], a:0, h:'polWirtschaft', pts:1},
  ]},

/* ================= FRANZÖSISCH ================= */
{ id:'fr6-start', grade:6, subject:'franz', icon:'🇫🇷',
  title:{de:'Französisch: Bonjour!',ru:'Французский: Bonjour!',en:'French: Bonjour!'},
  desc:{de:'Erste Wörter, Begrüßung und Zahlen',ru:'Первые слова, приветствия и числа',en:'First words, greetings and numbers'},
  qs:[
    {t:'match', q:'Verbinde die Begrüßungen:', tr:{ru:'Соедини приветствия:',en:'Match the greetings:'},
      pairs:[['Bonjour','Guten Tag'],['Salut','Hallo'],['Au revoir','Auf Wiedersehen'],['Merci','Danke']], h:'frBasics', pts:4},
    {t:'mc', q:'Wie sagt man „Ich heiße Tom"?', tr:{ru:'Как сказать «Меня зовут Том»?',en:'How do you say "My name is Tom"?'}, opts:['Je m’appelle Tom.','Je suis Tom appelle.','Tu t’appelles Tom.'], a:0, h:'frBasics', pts:1},
    {t:'match', q:'Verbinde die Zahlen:', tr:{ru:'Соедини числа:',en:'Match the numbers:'},
      pairs:[['un','1'],['trois','3'],['cinq','5'],['dix','10']], h:'frBasics', pts:4},
    {t:'mc', q:'Welcher Artikel ist WEIBLICH?', tr:{ru:'Какой артикль женского рода?',en:'Which article is feminine?'}, opts:['la','le','les'], a:0, h:'frBasics', pts:1},
    {t:'mc', q:'„Ça va ?" bedeutet ...', tr:{ru:'„Ça va ?" значит ...',en:'"Ça va ?" means ...'}, opts:['Wie geht’s?','Wo bist du?','Wie heißt du?'], a:0, h:'frBasics', pts:1},
    {t:'mc', q:'Wie heißt „bitte" auf Französisch?', tr:{ru:'Как по-французски «пожалуйста»?',en:'How do you say "please" in French?'}, opts:['s’il vous plaît','merci','pardon'], a:0, h:'frBasics', pts:1},
    {t:'mc', q:'Je ___ élève. (ich BIN Schüler)', tr:{ru:'Выбери: Je ___ élève.',en:'Choose: Je ___ élève.'}, opts:['suis','es','est'], a:0, h:'frBasics', pts:1},
    {t:'mc', q:'Tu ___ un frère ? (du HAST einen Bruder?)', tr:{ru:'Выбери: Tu ___ un frère ?',en:'Choose: Tu ___ un frère ?'}, opts:['as','ai','a'], a:0, h:'frBasics', pts:1},
  ]},

{ id:'fr7-verbs', grade:7, subject:'franz', icon:'🗣️',
  title:{de:'Französisch: Verben & Verneinung',ru:'Французский: глаголы и отрицание',en:'French: Verbs & Negation'},
  desc:{de:'-er-Verben, être, avoir und ne ... pas',ru:'Глаголы на -er, être, avoir, ne ... pas',en:'-er verbs, être, avoir and ne ... pas'},
  qs:[
    {t:'text', q:'Konjugiere: je ___ (parler)', tr:{ru:'Проспрягай: je ___ (parler)',en:'Conjugate: je ___ (parler)'}, a:['parle'], h:'frVerbs', pts:1},
    {t:'text', q:'Konjugiere: nous ___ (parler)', tr:{ru:'Проспрягай: nous ___ (parler)',en:'Conjugate: nous ___ (parler)'}, a:['parlons'], h:'frVerbs', pts:1},
    {t:'text', q:'Konjugiere: vous ___ (parler)', tr:{ru:'Проспрягай: vous ___ (parler)',en:'Conjugate: vous ___ (parler)'}, a:['parlez'], h:'frVerbs', pts:1},
    {t:'mc', q:'Wie verneint man auf Französisch?', tr:{ru:'Как строится отрицание во французском?',en:'How do you negate in French?'}, opts:['ne ... pas um das Verb','nur pas','nur ne'], a:0, h:'frVerbs', pts:1},
    {t:'mc', q:'„Ich spreche kein Französisch" heißt:', tr:{ru:'«Я не говорю по-французски»:',en:'"I don’t speak French":'}, opts:['Je ne parle pas français.','Je parle pas ne français.','Je non parle français.'], a:0, h:'frVerbs', pts:1},
    {t:'mc', q:'Nous ___ français. (être)', tr:{ru:'Выбери: Nous ___ français. (être)',en:'Choose: Nous ___ français. (être)'}, opts:['sommes','êtes','sont'], a:0, h:'frBasics', pts:1},
    {t:'mc', q:'Ils ___ deux chats. (avoir)', tr:{ru:'Выбери: Ils ___ deux chats. (avoir)',en:'Choose: Ils ___ deux chats. (avoir)'}, opts:['ont','avons','avez'], a:0, h:'frBasics', pts:1},
    {t:'mc', q:'Wie stellt man eine Frage mit „est-ce que"?', tr:{ru:'Как задать вопрос с „est-ce que"?',en:'How do you ask with "est-ce que"?'}, opts:['Est-ce que tu parles français ?','Tu est-ce que parles ?','Parles est-ce que tu ?'], a:0, h:'frVerbs', pts:1},
  ]},

/* ================= BIOLOGIE 6–10 ================= */
{ id:'b6-zelle', grade:6, subject:'bio', icon:'🔬',
  title:{de:'Zellen & Fotosynthese',ru:'Клетки и фотосинтез',en:'Cells & Photosynthesis'},
  desc:{de:'Der Bauplan des Lebens',ru:'План строения жизни',en:'The blueprint of life'},
  qs:[
    {t:'mc', q:'Woraus bestehen alle Lebewesen?', tr:{ru:'Из чего состоят все живые организмы?',en:'What are all living things made of?'}, opts:['aus Zellen','aus Atomen allein','aus Molekülen ohne Struktur'], a:0, h:'bioZelle', pts:1},
    {t:'mc', q:'Was enthält der Zellkern?', tr:{ru:'Что содержит ядро клетки?',en:'What does the nucleus contain?'}, opts:['die Erbinformation (DNA)','Wasser','Zucker'], a:0, h:'bioZelle', pts:1},
    {t:'mc', q:'Welches Teil hat NUR die Pflanzenzelle?', tr:{ru:'Что есть ТОЛЬКО у растительной клетки?',en:'Which part do ONLY plant cells have?'}, opts:['Chloroplasten','Zellkern','Zellmembran'], a:0, h:'bioZelle', pts:1},
    {t:'mc', q:'Was brauchen Pflanzen für die Fotosynthese?', tr:{ru:'Что нужно растениям для фотосинтеза?',en:'What do plants need for photosynthesis?'}, opts:['Licht, Wasser und Kohlenstoffdioxid','nur Erde','nur Wärme'], a:0, h:'bioZelle', pts:1},
    {t:'mc', q:'Was produzieren Pflanzen bei der Fotosynthese?', tr:{ru:'Что производят растения при фотосинтезе?',en:'What do plants produce in photosynthesis?'}, opts:['Traubenzucker und Sauerstoff','Kohlenstoffdioxid','Stickstoff'], a:0, h:'bioZelle', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Ohne Pflanzen gäbe es keinen Sauerstoff zum Atmen."', tr:{ru:'Верно ли: без растений не было бы кислорода?',en:'True or false: without plants there would be no oxygen?'}, a:true, h:'bioZelle', pts:1},
    {t:'mc', q:'Wie heißt der grüne Farbstoff der Pflanzen?', tr:{ru:'Как называется зелёный пигмент растений?',en:'What is the green pigment of plants called?'}, opts:['Chlorophyll','Hämoglobin','Melanin'], a:0, h:'bioZelle', pts:1},
    {t:'match', q:'Verbinde Zellteil und Aufgabe:', tr:{ru:'Соедини часть клетки и функцию:',en:'Match cell part and job:'},
      pairs:[['Zellkern','Steuerzentrale'],['Zellmembran','Grenze nach außen'],['Chloroplast','Fotosynthese'],['Vakuole','Speicher']], h:'bioZelle', pts:4},
  ]},

{ id:'b8-oeko', grade:8, subject:'bio', icon:'🌳',
  title:{de:'Ökologie & Nahrungsketten',ru:'Экология и пищевые цепи',en:'Ecology & Food Chains'},
  desc:{de:'Wie alles in der Natur zusammenhängt',ru:'Как всё в природе связано',en:'How everything in nature connects'},
  qs:[
    {t:'mc', q:'Was ist ein Ökosystem?', tr:{ru:'Что такое экосистема?',en:'What is an ecosystem?'}, opts:['Lebewesen zusammen mit ihrem Lebensraum','nur die Tiere eines Waldes','nur der Boden'], a:0, h:'bioOeko', pts:1},
    {t:'mc', q:'Warum sind Pflanzen PRODUZENTEN?', tr:{ru:'Почему растения – продуценты?',en:'Why are plants producers?'}, opts:['Sie stellen mit Fotosynthese selbst Nahrung her.','Sie fressen andere Pflanzen.','Sie zersetzen totes Material.'], a:0, h:'bioOeko', pts:1},
    {t:'mc', q:'Wie beginnt eine Nahrungskette immer?', tr:{ru:'С чего всегда начинается пищевая цепь?',en:'How does a food chain always start?'}, opts:['mit einer Pflanze','mit einem Raubtier','mit einem Pilz'], a:0, h:'bioOeko', pts:1},
    {t:'mc', q:'Was machen DESTRUENTEN (Bakterien, Pilze)?', tr:{ru:'Что делают редуценты (бактерии, грибы)?',en:'What do decomposers do?'}, opts:['Sie bauen totes Material wieder ab.','Sie jagen Tiere.','Sie machen Fotosynthese.'], a:0, h:'bioOeko', pts:1},
    {t:'mc', q:'Gras → Hase → Fuchs. Was ist der Hase?', tr:{ru:'Трава → заяц → лиса. Кто заяц?',en:'Grass → hare → fox. What is the hare?'}, opts:['Konsument 1. Ordnung','Produzent','Destruent'], a:0, h:'bioOeko', pts:1},
    {t:'mc', q:'Was verstärkt den Treibhauseffekt?', tr:{ru:'Что усиливает парниковый эффект?',en:'What strengthens the greenhouse effect?'}, opts:['zu viel CO₂ in der Atmosphäre','zu viele Bäume','zu viel Sauerstoff'], a:0, h:'bioOeko', pts:1},
    {t:'mc', q:'Was hilft gegen den Klimawandel?', tr:{ru:'Что помогает против изменения климата?',en:'What helps against climate change?'}, opts:['Energie sparen und Wälder schützen','mehr Autofahren','mehr Kohle verbrennen'], a:0, h:'bioOeko', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„In der Natur gehen Stoffe verloren."', tr:{ru:'Верно ли: в природе вещества исчезают?',en:'True or false: matter is lost in nature?'}, a:false, h:'bioOeko', pts:1},
  ]},

{ id:'b9-koerper', grade:9, subject:'bio', icon:'🧬',
  title:{de:'Genetik & Körper',ru:'Генетика и организм',en:'Genetics & Body'},
  desc:{de:'Vererbung, Pubertät und Gesundheit',ru:'Наследственность, взросление и здоровье',en:'Inheritance, puberty and health'},
  qs:[
    {t:'mc', q:'Wo befindet sich die Erbinformation?', tr:{ru:'Где находится наследственная информация?',en:'Where is the genetic information?'}, opts:['im Zellkern (DNA)','im Blut','in den Muskeln'], a:0, h:'bioZelle', pts:1},
    {t:'mc', q:'Wie viele Chromosomen hat eine menschliche Körperzelle?', tr:{ru:'Сколько хромосом в клетке человека?',en:'How many chromosomes does a human body cell have?'}, opts:['46','23','12'], a:0, h:'bioZelle', pts:1},
    {t:'mc', q:'Was bedeutet „dominant"?', tr:{ru:'Что значит «доминантный»?',en:'What does "dominant" mean?'}, opts:['Das Merkmal setzt sich durch.','Das Merkmal verschwindet.','Das Merkmal ist selten.'], a:0, h:'bioZelle', pts:1},
    {t:'mc', q:'Was steuert die Veränderungen in der Pubertät?', tr:{ru:'Что управляет изменениями в пубертате?',en:'What controls the changes in puberty?'}, opts:['Hormone','Vitamine','Muskeln'], a:0, h:'bioZelle', pts:1},
    {t:'mc', q:'Woher bekommt ein Kind seine Gene?', tr:{ru:'Откуда ребёнок получает гены?',en:'Where does a child get its genes from?'}, opts:['je zur Hälfte von Mutter und Vater','nur von der Mutter','nur vom Vater'], a:0, h:'bioZelle', pts:1},
    {t:'mc', q:'Was ist ein Gen?', tr:{ru:'Что такое ген?',en:'What is a gene?'}, opts:['ein Abschnitt der DNA mit einer Erbinformation','eine Zelle','ein Organ'], a:0, h:'bioZelle', pts:1},
    {t:'mc', q:'Wie schützt man sich vor Infektionskrankheiten?', tr:{ru:'Как защититься от инфекций?',en:'How do you protect against infections?'}, opts:['Hygiene und Impfungen','gar nicht','nur durch Sport'], a:0, h:'bioFood', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Eineiige Zwillinge haben die gleiche Erbinformation."', tr:{ru:'Верно ли: однояйцевые близнецы имеют одинаковые гены?',en:'True or false: identical twins share the same genes?'}, a:true, h:'bioZelle', pts:1},
  ]},

/* ================= ERDKUNDE 6–10 ================= */
{ id:'g6-klima', grade:6, subject:'geo', icon:'🌡️',
  title:{de:'Klimazonen der Erde',ru:'Климатические пояса Земли',en:'Climate Zones of the Earth'},
  desc:{de:'Von den Tropen bis zum Polarkreis',ru:'От тропиков до полярного круга',en:'From the tropics to the polar circle'},
  qs:[
    {t:'mc', q:'Was ist der Unterschied zwischen Wetter und Klima?', tr:{ru:'В чём разница между погодой и климатом?',en:'What is the difference between weather and climate?'}, opts:['Wetter ist jetzt, Klima ist der Durchschnitt vieler Jahre.','Es gibt keinen Unterschied.','Klima ist nur im Sommer.'], a:0, h:'geoKlima', pts:1},
    {t:'mc', q:'In welcher Klimazone liegt Deutschland?', tr:{ru:'В каком климатическом поясе Германия?',en:'Which climate zone is Germany in?'}, opts:['gemäßigte Zone','Tropen','Polarzone'], a:0, h:'geoKlima', pts:1},
    {t:'mc', q:'Wo ist es am wärmsten?', tr:{ru:'Где теплее всего?',en:'Where is it warmest?'}, opts:['am Äquator','an den Polen','in den Subtropen'], a:0, h:'geoKlima', pts:1},
    {t:'mc', q:'Was zeigt die Linie in einem Klimadiagramm?', tr:{ru:'Что показывает линия на климатограмме?',en:'What does the line in a climate chart show?'}, opts:['die Temperatur','den Niederschlag','die Höhe'], a:0, h:'geoKlima', pts:1},
    {t:'mc', q:'Was zeigen die Säulen im Klimadiagramm?', tr:{ru:'Что показывают столбики на климатограмме?',en:'What do the bars show?'}, opts:['den Niederschlag','die Temperatur','die Sonnenstunden'], a:0, h:'geoKlima', pts:1},
    {t:'mc', q:'Wie ändert sich die Temperatur, je höher man ins Gebirge steigt?', tr:{ru:'Как меняется температура с высотой в горах?',en:'How does temperature change with altitude?'}, opts:['sie sinkt','sie steigt','sie bleibt gleich'], a:0, h:'geoKlima', pts:1},
    {t:'mc', q:'In welcher Zone liegen die großen Wüsten wie die Sahara?', tr:{ru:'В каком поясе находятся большие пустыни?',en:'In which zone are the great deserts?'}, opts:['Subtropen','Polarzone','gemäßigte Zone'], a:0, h:'geoKlima', pts:1},
    {t:'match', q:'Verbinde Klimazone und Merkmal:', tr:{ru:'Соедини пояс и признак:',en:'Match zone and feature:'},
      pairs:[['Tropen','heiß und feucht'],['Subtropen','trocken, Wüsten'],['gemäßigte Zone','vier Jahreszeiten'],['Polarzone','sehr kalt, Eis']], h:'geoKlima', pts:4},
  ]},

{ id:'g8-stadt', grade:8, subject:'geo', icon:'🏙️',
  title:{de:'Stadt, Land & Wirtschaft',ru:'Город, село и экономика',en:'City, Country & Economy'},
  desc:{de:'Wirtschaftssektoren und Verstädterung',ru:'Секторы экономики и урбанизация',en:'Economic sectors and urbanisation'},
  qs:[
    {t:'mc', q:'Zu welchem Sektor gehört die Landwirtschaft?', tr:{ru:'К какому сектору относится сельское хозяйство?',en:'Which sector is farming in?'}, opts:['primärer Sektor','sekundärer Sektor','tertiärer Sektor'], a:0, h:'geoStadt', pts:1},
    {t:'mc', q:'Zu welchem Sektor gehört eine Autofabrik?', tr:{ru:'К какому сектору относится автозавод?',en:'Which sector is a car factory in?'}, opts:['sekundärer Sektor','primärer Sektor','tertiärer Sektor'], a:0, h:'geoStadt', pts:1},
    {t:'mc', q:'Zu welchem Sektor gehören Ärzte und Lehrer?', tr:{ru:'К какому сектору относятся врачи и учителя?',en:'Which sector are doctors and teachers in?'}, opts:['tertiärer Sektor (Dienstleistung)','primärer Sektor','sekundärer Sektor'], a:0, h:'geoStadt', pts:1},
    {t:'mc', q:'In welchem Sektor arbeiten in Deutschland die meisten Menschen?', tr:{ru:'В каком секторе работает большинство немцев?',en:'In which sector do most Germans work?'}, opts:['tertiärer Sektor','primärer Sektor','sekundärer Sektor'], a:0, h:'geoStadt', pts:1},
    {t:'mc', q:'Was bedeutet Verstädterung?', tr:{ru:'Что означает урбанизация?',en:'What does urbanisation mean?'}, opts:['immer mehr Menschen ziehen in Städte','Städte werden kleiner','Dörfer wachsen schneller'], a:0, h:'geoStadt', pts:1},
    {t:'mc', q:'Wofür war das Ruhrgebiet früher bekannt?', tr:{ru:'Чем раньше был известен Рурский регион?',en:'What was the Ruhr area known for?'}, opts:['Kohle und Stahl','Weinbau','Tourismus'], a:0, h:'geoStadt', pts:1},
    {t:'mc', q:'Was ist der Strukturwandel im Ruhrgebiet?', tr:{ru:'Что такое структурные изменения в Рурской области?',en:'What is structural change in the Ruhr?'}, opts:['der Wandel von Industrie zu Dienstleistung und Technik','der Bau neuer Kohlebergwerke','die Rückkehr zur Landwirtschaft'], a:0, h:'geoStadt', pts:1},
    {t:'mc', q:'Wo sind die Mieten in einer Stadt am teuersten?', tr:{ru:'Где в городе самая дорогая аренда?',en:'Where is rent most expensive in a city?'}, opts:['in der City (Zentrum)','am Stadtrand','im Industriegebiet'], a:0, h:'geoStadt', pts:1},
  ]},

/* ================= INFORMATIK 6–10 ================= */
{ id:'i7-office', grade:7, subject:'info', icon:'📊',
  title:{de:'Tabellen & Präsentationen',ru:'Таблицы и презентации',en:'Spreadsheets & Presentations'},
  desc:{de:'Excel-Formeln und gute Folien',ru:'Формулы Excel и хорошие слайды',en:'Excel formulas and good slides'},
  qs:[
    {t:'mc', q:'Womit beginnt in einer Tabellenkalkulation JEDE Formel?', tr:{ru:'С чего начинается ЛЮБАЯ формула в таблице?',en:'How does every spreadsheet formula start?'}, opts:['mit =','mit +','mit einem Buchstaben'], a:0, h:'infoOffice', pts:1},
    {t:'mc', q:'Was macht =SUMME(A1:A10)?', tr:{ru:'Что делает =СУММ(A1:A10)?',en:'What does =SUM(A1:A10) do?'}, opts:['addiert alle Werte von A1 bis A10','zählt die Zellen','findet den größten Wert'], a:0, h:'infoOffice', pts:1},
    {t:'mc', q:'Wie heißt die Zelle in Spalte B, Zeile 3?', tr:{ru:'Как называется ячейка в столбце B, строке 3?',en:'What is the cell in column B, row 3 called?'}, opts:['B3','3B','BB3'], a:0, h:'infoOffice', pts:1},
    {t:'mc', q:'Welches Diagramm zeigt ANTEILE am besten?', tr:{ru:'Какая диаграмма лучше показывает доли?',en:'Which chart shows shares best?'}, opts:['Kreisdiagramm','Liniendiagramm','Streudiagramm'], a:0, h:'infoOffice', pts:1},
    {t:'mc', q:'Welches Diagramm zeigt eine Entwicklung über die Zeit?', tr:{ru:'Какая диаграмма показывает динамику во времени?',en:'Which chart shows change over time?'}, opts:['Liniendiagramm','Kreisdiagramm','Tabelle'], a:0, h:'infoOffice', pts:1},
    {t:'mc', q:'Was ist ein Fehler bei Präsentationen?', tr:{ru:'Что является ошибкой в презентации?',en:'What is a mistake in presentations?'}, opts:['zu viel Text auf einer Folie','wenige Stichpunkte','große Schrift'], a:0, h:'infoOffice', pts:1},
    {t:'mc', q:'Welches Tastenkürzel speichert eine Datei?', tr:{ru:'Какое сочетание клавиш сохраняет файл?',en:'Which shortcut saves a file?'}, opts:['Strg + S','Strg + C','Strg + P'], a:0, h:'infoOffice', pts:1},
    {t:'match', q:'Verbinde Tastenkürzel und Funktion:', tr:{ru:'Соедини сочетание и функцию:',en:'Match shortcut and function:'},
      pairs:[['Strg + C','Kopieren'],['Strg + V','Einfügen'],['Strg + Z','Rückgängig'],['Strg + S','Speichern']], h:'infoOffice', pts:4},
  ]},

{ id:'i9-code', grade:9, subject:'info', icon:'👨‍💻',
  title:{de:'Programmieren mit Python',ru:'Программирование на Python',en:'Programming with Python'},
  desc:{de:'Variablen, Schleifen und Bedingungen',ru:'Переменные, циклы и условия',en:'Variables, loops and conditions'},
  qs:[
    {t:'mc', q:'Was macht der Befehl print("Hallo")?', tr:{ru:'Что делает команда print("Привет")?',en:'What does print("Hello") do?'}, opts:['gibt Hallo auf dem Bildschirm aus','druckt auf Papier','speichert eine Datei'], a:0, h:'infoCode', pts:1},
    {t:'mc', q:'Was ist eine VARIABLE?', tr:{ru:'Что такое переменная?',en:'What is a variable?'}, opts:['ein Behälter, der einen Wert speichert','ein Fehler im Programm','eine Schleife'], a:0, h:'infoCode', pts:1},
    {t:'num', q:'Wie oft läuft diese Schleife?\nfor i in range(5):\n    print(i)', tr:{ru:'Сколько раз выполнится цикл for i in range(5)?',en:'How many times does for i in range(5) run?'}, a:5, h:'infoCode', pts:1},
    {t:'mc', q:'Womit prüft man eine Bedingung?', tr:{ru:'Чем проверяют условие?',en:'What checks a condition?'}, opts:['if','for','print'], a:0, h:'infoCode', pts:1},
    {t:'mc', q:'Welcher Datentyp ist "Hallo"?', tr:{ru:'Какой тип данных у "Привет"?',en:'Which data type is "Hello"?'}, opts:['String (Text)','Integer (Zahl)','Boolean'], a:0, h:'infoCode', pts:1},
    {t:'mc', q:'Welcher Datentyp ist True/False?', tr:{ru:'Какой тип данных True/False?',en:'Which data type is True/False?'}, opts:['Boolean','String','Float'], a:0, h:'infoCode', pts:1},
    {t:'mc', q:'Was macht input()?', tr:{ru:'Что делает input()?',en:'What does input() do?'}, opts:['liest eine Eingabe vom Benutzer','gibt Text aus','beendet das Programm'], a:0, h:'infoCode', pts:1},
    {t:'mc', q:'Was solltest du VOR dem Programmieren tun?', tr:{ru:'Что нужно сделать ДО написания кода?',en:'What should you do BEFORE coding?'}, opts:['den Algorithmus in Schritten planen','sofort tippen','das Programm löschen'], a:0, h:'infoCode', pts:1},
  ]},
];
