/* ============ Klasse 6–10: Mathematik · Deutsch · Englisch ============ */
const TESTS_CORE_HIGH = [

/* ================= MATHEMATIK ================= */
{ id:'m6-frac1', grade:6, subject:'math', icon:'🍕', genTest:true,
  title:{de:'Brüche: Kürzen & Anteile',ru:'Дроби: сокращение и части',en:'Fractions: Simplify & Parts'},
  desc:{de:'Brüche kürzen, erweitern und Anteile berechnen',ru:'Сокращение дробей и части от числа',en:'Simplifying fractions and finding parts'},
  gen(){ return [qFracSimplify(),qFracSimplify(),qFracSimplify(),qFracOf(),qFracOf(),qFracOf(),
    {t:'mc', q:'Welcher Bruch ist am größten?', tr:{ru:'Какая дробь больше всех?',en:'Which fraction is the biggest?'}, opts:['3/4','1/2','2/3','1/4'], a:0, h:'frac', pts:1},
    {t:'text', q:'Wie heißt 1/2 als Dezimalzahl? (z. B. 0,25)', tr:{ru:'1/2 в виде десятичной дроби?',en:'Write 1/2 as a decimal.'}, a:['0,5','0.5'], h:'decimal', pts:1}]; } },

{ id:'m6-frac2', grade:6, subject:'math', icon:'➗', genTest:true,
  title:{de:'Bruchrechnen: + − · :',ru:'Действия с дробями',en:'Fraction Arithmetic'},
  desc:{de:'Addieren, subtrahieren, multiplizieren',ru:'Сложение, вычитание, умножение дробей',en:'Adding, subtracting, multiplying fractions'},
  gen(){ return [qFracAddSame(),qFracAddSame(),qFracAddUnlike(),qFracAddUnlike(),qFracMul(),qFracMul(),qFracOf(),qFracSimplify()]; } },

{ id:'m6-dec', grade:6, subject:'math', icon:'🔢', genTest:true,
  title:{de:'Dezimalzahlen',ru:'Десятичные дроби',en:'Decimal Numbers'},
  desc:{de:'Kommazahlen addieren, multiplizieren, verschieben',ru:'Сложение и умножение десятичных дробей',en:'Adding, multiplying and shifting decimals'},
  gen(){ return [qDecAdd(),qDecAdd(),qDecSub(),qDecSub(),qDecMul(),qDecMul(),qDecShift(),qDecShift()]; } },

{ id:'m6-geo', grade:6, subject:'math', icon:'📐', genTest:true,
  title:{de:'Winkel & Flächen',ru:'Углы и площади',en:'Angles & Areas'},
  desc:{de:'Winkelarten, Winkelsumme, Flächen berechnen',ru:'Виды углов, сумма углов, площади',en:'Angle types, angle sum, areas'},
  gen(){ return [qAngleType(),qAngleType(),qAngleTriangle(),qAngleTriangle(),qArea(),qPerimeter(),
    {t:'num', q:'Wie groß ist die Winkelsumme im Viereck?', tr:{ru:'Чему равна сумма углов четырёхугольника?',en:'What is the angle sum in a quadrilateral?'}, a:360, unit:'°', h:'angles', pts:1},
    {t:'mc', q:'Wie nennt man einen Winkel von genau 90°?', tr:{ru:'Как называется угол ровно в 90°?',en:'What is a 90° angle called?'}, opts:['rechter Winkel','spitzer Winkel','stumpfer Winkel'], a:0, h:'angles', pts:1}]; } },

{ id:'m6-mix', grade:6, subject:'math', icon:'🎡', genTest:true,
  title:{de:'Mathe-Mix Klasse 6',ru:'Микс по математике 6 класс',en:'Maths Mix Grade 6'},
  desc:{de:'10 zufällige Aufgaben aus dem ganzen Schuljahr',ru:'10 случайных заданий за весь год',en:'10 random tasks from the whole year'},
  gen(){ const pool=[qFracSimplify,qFracOf,qFracAddSame,qDecAdd,qDecMul,qAngleTriangle,qArea,qUnit,qRound,qOrderOps];
    const qs=[]; for(let i=0;i<10;i++) qs.push(pick(pool)()); return qs; } },

{ id:'m7-neg', grade:7, subject:'math', icon:'➖', genTest:true,
  title:{de:'Negative Zahlen',ru:'Отрицательные числа',en:'Negative Numbers'},
  desc:{de:'Rechnen mit positiven und negativen Zahlen',ru:'Вычисления с отрицательными числами',en:'Calculating with positive and negative numbers'},
  gen(){ return [qNegAdd(),qNegAdd(),qNegAdd(),qNegMul(),qNegMul(),qNegMul(),
    {t:'mc', q:'Minus mal Minus ergibt ...', tr:{ru:'Минус на минус даёт ...',en:'Minus times minus gives ...'}, opts:['Plus','Minus','Null'], a:0, h:'negNum', pts:1},
    {t:'num', q:'Die Temperatur ist −7 °C und steigt um 12 Grad.\nWelche Temperatur ist es jetzt?', tr:{ru:'Температура −7 °C и поднялась на 12 градусов. Сколько стало?',en:'It is −7 °C and rises by 12 degrees. What is it now?'}, a:5, unit:'°C', h:'negNum', pts:2}]; } },

{ id:'m7-percent', grade:7, subject:'math', icon:'💯', genTest:true,
  title:{de:'Prozentrechnung',ru:'Проценты',en:'Percentages'},
  desc:{de:'Prozentwert, Prozentsatz, Rabatte',ru:'Часть, процент, скидки',en:'Percentage value, rate, discounts'},
  gen(){ return [qPercentOf(),qPercentOf(),qPercentOf(),qPercentSatz(),qPercentSatz(),qRabatt(),qRabatt(),
    {t:'mc', q:'25 % sind dasselbe wie ...', tr:{ru:'25 % – это то же самое, что ...',en:'25 % is the same as ...'}, opts:['1/4','1/2','1/3','1/5'], a:0, h:'percent', pts:1}]; } },

{ id:'m7-dreisatz', grade:7, subject:'math', icon:'⚖️', genTest:true,
  title:{de:'Dreisatz & Zuordnungen',ru:'Пропорции и правило трёх',en:'Rule of Three & Proportion'},
  desc:{de:'Proportionale Zuordnungen sicher rechnen',ru:'Прямая пропорциональность',en:'Working with proportional relationships'},
  gen(){ return [qDreisatz(),qDreisatz(),qDreisatz(),qDreisatz(),qSpeed(),qSpeed(),qPercentOf(),
    {t:'mc', q:'Doppelt so viele Hefte kosten auch doppelt so viel. Wie nennt man das?', tr:{ru:'Вдвое больше тетрадей стоят вдвое дороже. Как это называется?',en:'Twice the notebooks cost twice as much. What is this called?'},
     opts:['proportional','antiproportional','zufällig'], a:0, h:'dreisatz', pts:1}]; } },

{ id:'m7-term', grade:7, subject:'math', icon:'🔤', genTest:true,
  title:{de:'Terme & Gleichungen',ru:'Выражения и уравнения',en:'Terms & Equations'},
  desc:{de:'Zusammenfassen, ausmultiplizieren, x berechnen',ru:'Упрощение, раскрытие скобок, поиск x',en:'Simplifying, expanding, solving for x'},
  gen(){ return [qTermSimplify(),qTermSimplify(),qExpand(),qExpand(),qSolveLinear(),qSolveLinear(),qSolveLinear(),
    {t:'text', q:'Stelle einen Term auf: „Das Doppelte einer Zahl x, vermehrt um 5"', tr:{ru:'Составь выражение: «удвоенное число x плюс 5»',en:'Write the term: "twice a number x, increased by 5"'}, a:['2x+5','2x + 5'], h:'term', pts:1}]; } },

{ id:'m8-func', grade:8, subject:'math', icon:'📈', genTest:true,
  title:{de:'Lineare Funktionen',ru:'Линейные функции',en:'Linear Functions'},
  desc:{de:'y = mx + b verstehen und anwenden',ru:'Понять и применять y = mx + b',en:'Understanding y = mx + b'},
  gen(){ return [qLinFunc(),qLinFunc(),qLinFunc(),
    {t:'mc', q:'Was bedeutet das m in y = mx + b?', tr:{ru:'Что означает m в y = mx + b?',en:'What does m mean in y = mx + b?'}, opts:['die Steigung','den y-Achsenabschnitt','den x-Wert'], a:0, h:'linfunc', pts:1},
    {t:'mc', q:'Was bedeutet das b in y = mx + b?', tr:{ru:'Что означает b в y = mx + b?',en:'What does b mean in y = mx + b?'}, opts:['den y-Achsenabschnitt','die Steigung','die Nullstelle'], a:0, h:'linfunc', pts:1},
    {t:'mc', q:'Eine Gerade mit negativer Steigung ...', tr:{ru:'Прямая с отрицательным наклоном ...',en:'A line with negative slope ...'}, opts:['fällt','steigt','ist waagerecht'], a:0, h:'linfunc', pts:1},
    qSolveLinear(), qLGS(), qLGS()]; } },

{ id:'m8-geo', grade:8, subject:'math', icon:'📦', genTest:true,
  title:{de:'Körper: Volumen & Oberfläche',ru:'Тела: объём и поверхность',en:'Solids: Volume & Surface'},
  desc:{de:'Quader, Würfel und Zylinder berechnen',ru:'Параллелепипед, куб и цилиндр',en:'Cuboids, cubes and cylinders'},
  gen(){ const a=ri(3,9); return [qVolumeQuader(),qVolumeQuader(),qCylinder(),
    {t:'num', q:`Ein Würfel hat die Kantenlänge ${a} cm. Berechne das Volumen.  (V = a³)`, tr:{ru:`Куб с ребром ${a} см. Найди объём. (V = a³)`,en:`A cube has edge ${a} cm. Find the volume.`}, a:a*a*a, unit:'cm³', h:'volume', pts:1},
    {t:'num', q:`Ein Würfel hat die Kantenlänge ${a} cm. Berechne die Oberfläche.  (O = 6 · a²)`, tr:{ru:`Куб с ребром ${a} см. Найди площадь поверхности. (S = 6a²)`,en:`A cube has edge ${a} cm. Find the surface area.`}, a:6*a*a, unit:'cm²', h:'volume', pts:2},
    {t:'mc', q:'Wie viele cm³ sind 1 Liter?', tr:{ru:'Сколько см³ в 1 литре?',en:'How many cm³ are 1 litre?'}, opts:['1.000','100','10.000'], a:0, h:'volume', pts:1},
    qArea(), qPerimeter()]; } },

{ id:'m8-stat', grade:8, subject:'math', icon:'📊', genTest:true,
  title:{de:'Statistik & Wahrscheinlichkeit',ru:'Статистика и вероятность',en:'Statistics & Probability'},
  desc:{de:'Mittelwert, Median und Zufall',ru:'Среднее, медиана и вероятность',en:'Mean, median and chance'},
  gen(){ return [qMean(),qMean(),qProbSimple(),qProbSimple(),
    {t:'mc', q:'Wie findest du den MEDIAN?', tr:{ru:'Как найти МЕДИАНУ?',en:'How do you find the MEDIAN?'}, opts:['Werte der Größe nach ordnen, dann den mittleren nehmen','Alle addieren und teilen','Den häufigsten Wert nehmen'], a:0, h:'stats', pts:1},
    {t:'mc', q:'Was ist der MODUS?', tr:{ru:'Что такое МОДА?',en:'What is the MODE?'}, opts:['der häufigste Wert','der mittlere Wert','der Durchschnitt'], a:0, h:'stats', pts:1},
    {t:'num', q:'Ein Würfel wird geworfen. Wie viele mögliche Ergebnisse gibt es?', tr:{ru:'Бросают кубик. Сколько возможных исходов?',en:'A die is rolled. How many possible outcomes?'}, a:6, h:'prob2', pts:1},
    {t:'mc', q:'Wie groß ist die Wahrscheinlichkeit, mit einem Würfel eine 6 zu werfen?', tr:{ru:'Вероятность выбросить 6 на кубике?',en:'Probability of rolling a 6?'}, opts:['1/6','1/3','1/2','6/6'], a:0, h:'prob2', pts:1}]; } },

{ id:'m9-pyth', grade:9, subject:'math', icon:'📏', genTest:true,
  title:{de:'Satz des Pythagoras',ru:'Теорема Пифагора',en:'Pythagorean Theorem'},
  desc:{de:'a² + b² = c² – der Klassiker!',ru:'a² + b² = c² – классика!',en:'a² + b² = c² – the classic!'},
  gen(){ return [qPythagoras(),qPythagoras(),qPythagoras(),qPythagoras(),qRoot(),qRoot(),qPower(),
    {t:'mc', q:'Wie heißt die längste Seite im rechtwinkligen Dreieck?', tr:{ru:'Как называется самая длинная сторона прямоугольного треугольника?',en:'What is the longest side in a right triangle called?'}, opts:['Hypotenuse','Kathete','Diagonale'], a:0, h:'pythagoras', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Der Satz des Pythagoras gilt in jedem Dreieck."', tr:{ru:'Верно ли: теорема Пифагора работает в любом треугольнике?',en:'True or false: Pythagoras works in any triangle?'}, a:false, h:'pythagoras', pts:1}]; } },

{ id:'m9-pot', grade:9, subject:'math', icon:'⬆️', genTest:true,
  title:{de:'Potenzen & Wurzeln',ru:'Степени и корни',en:'Powers & Roots'},
  desc:{de:'Quadratzahlen, Wurzeln und Potenzgesetze',ru:'Квадраты, корни и свойства степеней',en:'Squares, roots and power rules'},
  gen(){ return [qPower(),qPower(),qPower(),qRoot(),qRoot(),qRoot(),qQuadSimple(),
    {t:'num', q:'Berechne:  10³ = ?', tr:{ru:'Вычисли: 10³',en:'Calculate: 10³'}, a:1000, h:'powroot', pts:1},
    {t:'mc', q:'Was ergibt 5⁰?', tr:{ru:'Чему равно 5⁰?',en:'What is 5⁰?'}, opts:['1','0','5'], a:0, h:'powroot', pts:1}]; } },

{ id:'m9-zins', grade:9, subject:'math', icon:'🏦', genTest:true,
  title:{de:'Zinsrechnung',ru:'Проценты по вкладам',en:'Interest Calculation'},
  desc:{de:'Zinsen, Kapital und Zinssatz berechnen',ru:'Проценты, капитал и ставка',en:'Interest, capital and rate'},
  gen(){ return [qZins(),qZins(),qZins(),qPercentOf(),qRabatt(),qPercentSatz(),qDreisatz(),
    {t:'mc', q:'Wie berechnet man die Jahreszinsen?', tr:{ru:'Как считают годовые проценты?',en:'How do you calculate yearly interest?'}, opts:['Z = K · p : 100','Z = K + p','Z = K : p'], a:0, h:'zins', pts:1}]; } },

{ id:'m10-quad', grade:10, subject:'math', icon:'📐', genTest:true,
  title:{de:'Quadratische Gleichungen',ru:'Квадратные уравнения',en:'Quadratic Equations'},
  desc:{de:'Nullstellen finden und Parabeln verstehen',ru:'Корни и парабола',en:'Finding roots, understanding parabolas'},
  gen(){ return [qQuadEq(),qQuadEq(),qQuadSimple(),qQuadSimple(),qBinom(),qBinom(),qRoot(),
    {t:'mc', q:'Wie sieht der Graph einer quadratischen Funktion aus?', tr:{ru:'Как выглядит график квадратичной функции?',en:'What does the graph of a quadratic function look like?'}, opts:['eine Parabel','eine Gerade','ein Kreis'], a:0, h:'quad', pts:1},
    {t:'num', q:'Wie viele Lösungen hat x² = 25?', tr:{ru:'Сколько решений у x² = 25?',en:'How many solutions does x² = 25 have?'}, a:2, h:'quad', pts:1}]; } },

{ id:'m10-trig', grade:10, subject:'math', icon:'📊', genTest:true,
  title:{de:'Trigonometrie',ru:'Тригонометрия',en:'Trigonometry'},
  desc:{de:'sin, cos und tan im Dreieck',ru:'sin, cos и tan в треугольнике',en:'sin, cos and tan in triangles'},
  gen(){ return [qTrig(),qTrig(),qTrig(),qPythagoras(),qPythagoras(),qAngleTriangle(),
    {t:'mc', q:'Welche Seite liegt dem Winkel α gegenüber?', tr:{ru:'Какая сторона лежит напротив угла α?',en:'Which side is opposite angle α?'}, opts:['die Gegenkathete','die Ankathete','die Hypotenuse'], a:0, h:'trig', pts:1},
    {t:'mc', q:'Merkspruch für die Trigonometrie:', tr:{ru:'Мнемоника для тригонометрии:',en:'Memory aid for trigonometry:'}, opts:['GAGA – HUNDE – HAHA','ABC – DEF – GHI','ROT – GELB – GRÜN'], a:0, h:'trig', pts:1}]; } },

{ id:'m10-final', grade:10, subject:'math', icon:'🎓', genTest:true,
  title:{de:'Abschlussprüfung Mathematik',ru:'Выпускной экзамен по математике',en:'Final Exam Mathematics'},
  desc:{de:'Große Wiederholung für den Realschulabschluss',ru:'Большое повторение перед выпуском',en:'Big revision for the final exams'},
  gen(){ return [qPercentOf(),qZins(),qDreisatz(),qSolveLinear(),qLGS(),qLinFunc(),qPythagoras(),
    qCylinder(),qVolumeQuader(),qMean(),qProbSimple(),qQuadSimple(),qPower(),qRoot()]; } },

/* ================= DEUTSCH ================= */
{ id:'d6-satz', grade:6, subject:'german', icon:'🔗',
  title:{de:'Haupt- & Nebensätze',ru:'Главные и придаточные',en:'Main & Subordinate Clauses'},
  desc:{de:'Satzgefüge erkennen und Kommas setzen',ru:'Сложные предложения и запятые',en:'Recognising clauses and setting commas'},
  qs:[
    {t:'mc', q:'„Ich bleibe zu Hause, weil ich krank bin."\nWelcher Teil ist der NEBENSATZ?', tr:{ru:'Какая часть – придаточное предложение?',en:'Which part is the subordinate clause?'}, opts:['weil ich krank bin','Ich bleibe zu Hause'], a:0, h:'satzgefuege', pts:1},
    {t:'mc', q:'Wo steht das Verb im Nebensatz?', tr:{ru:'Где стоит глагол в придаточном?',en:'Where is the verb in a subordinate clause?'}, opts:['am Ende','an zweiter Stelle','am Anfang'], a:0, h:'satzgefuege', pts:1},
    {t:'mc', q:'Welches Wort leitet einen Nebensatz ein?', tr:{ru:'Какое слово вводит придаточное?',en:'Which word introduces a subordinate clause?'}, opts:['obwohl','und','aber'], a:0, h:'satzgefuege', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Vor einem Nebensatz steht immer ein Komma."', tr:{ru:'Верно ли: перед придаточным всегда запятая?',en:'True or false: always a comma before a subordinate clause?'}, a:true, h:'zeichen', pts:1},
    {t:'mc', q:'„Das Buch, das ich lese, ist spannend."\nWie heißt der eingeschobene Satz?', tr:{ru:'Как называется вставленное предложение?',en:'What is the inserted clause called?'}, opts:['Relativsatz','Hauptsatz','Fragesatz'], a:0, h:'satzgefuege', pts:1},
    {t:'mc', q:'Welcher Satz ist RICHTIG?', tr:{ru:'Какое предложение правильное?',en:'Which sentence is correct?'}, opts:['Ich lerne, weil ich eine gute Note will.','Ich lerne weil ich eine gute Note will.','Ich lerne, weil ich will eine gute Note.'], a:0, h:'satzgefuege', pts:1},
    {t:'mc', q:'„Er kam nach Hause und aß zu Abend."\nWie viele HAUPTSÄTZE sind das?', tr:{ru:'Сколько здесь главных предложений?',en:'How many main clauses are these?'}, opts:['zwei','einer','drei'], a:0, h:'satzgefuege', pts:1},
    {t:'match', q:'Verbinde Konjunktion und Bedeutung:', tr:{ru:'Соедини союз и значение:',en:'Match conjunction and meaning:'},
      pairs:[['weil','Grund'],['obwohl','Gegensatz'],['wenn','Bedingung'],['damit','Ziel']], h:'satzgefuege', pts:4},
  ]},

{ id:'d6-text', grade:6, subject:'german', icon:'📝',
  title:{de:'Textsorten: Bericht & Beschreibung',ru:'Типы текстов: отчёт и описание',en:'Text Types: Report & Description'},
  desc:{de:'Sachlich schreiben wie ein Profi',ru:'Пишем фактично, как профи',en:'Writing factually like a pro'},
  qs:[
    {t:'mc', q:'In welcher Zeitform schreibt man einen BERICHT?', tr:{ru:'В каком времени пишут отчёт (Bericht)?',en:'Which tense do you use for a report?'}, opts:['Präteritum','Präsens','Futur'], a:0, h:'textsorten', pts:1},
    {t:'mc', q:'Welche Fragen beantwortet ein Bericht?', tr:{ru:'На какие вопросы отвечает отчёт?',en:'Which questions does a report answer?'}, opts:['Wer? Was? Wann? Wo? Wie? Warum?','Nur: Was gefällt mir?','Nur: Wer ist schuld?'], a:0, h:'textsorten', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„In einem Bericht schreibt man auch seine eigene Meinung."', tr:{ru:'Верно ли: в отчёте пишут своё мнение?',en:'True or false: a report includes your own opinion?'}, a:false, h:'textsorten', pts:1},
    {t:'mc', q:'In welcher Zeitform schreibt man eine BESCHREIBUNG?', tr:{ru:'В каком времени пишут описание?',en:'Which tense for a description?'}, opts:['Präsens','Präteritum','Perfekt'], a:0, h:'textsorten', pts:1},
    {t:'mc', q:'Was gehört NICHT in eine Vorgangsbeschreibung?', tr:{ru:'Что НЕ нужно в описании процесса?',en:'What does NOT belong in a process description?'}, opts:['spannende Übertreibungen','die richtige Reihenfolge','genaue Mengenangaben'], a:0, h:'textsorten', pts:1},
    {t:'mc', q:'Wie beginnt eine gute Inhaltsangabe?', tr:{ru:'Как начинается краткое содержание?',en:'How does a good summary start?'}, opts:['Mit Titel, Autor und Textsorte','Mit dem spannendsten Satz','Mit der eigenen Meinung'], a:0, h:'textsorten', pts:1},
    {t:'mc', q:'In welcher Zeitform schreibt man eine INHALTSANGABE?', tr:{ru:'В каком времени пишут краткое содержание?',en:'Which tense for a summary?'}, opts:['Präsens','Präteritum','Futur'], a:0, h:'textsorten', pts:1},
    {t:'match', q:'Verbinde Textsorte und Merkmal:', tr:{ru:'Соедини тип текста и признак:',en:'Match text type and feature:'},
      pairs:[['Bericht','sachlich, Präteritum'],['Erzählung','spannend, Höhepunkt'],['Beschreibung','genau, Präsens'],['Erörterung','These und Argumente']], h:'textsorten', pts:4},
  ]},

{ id:'d7-aktiv', grade:7, subject:'german', icon:'🔄',
  title:{de:'Aktiv & Passiv',ru:'Актив и пассив',en:'Active & Passive'},
  desc:{de:'Sätze umformen wie ein Grammatik-Profi',ru:'Преобразование предложений',en:'Transforming sentences'},
  qs:[
    {t:'mc', q:'„Der Hund beißt den Mann."\nWelche Form ist das?', tr:{ru:'Какая это форма?',en:'Which voice is this?'}, opts:['Aktiv','Passiv'], a:0, noshuffle:true, h:'aktivPassiv', pts:1},
    {t:'mc', q:'„Der Mann wird gebissen."\nWelche Form ist das?', tr:{ru:'Какая это форма?',en:'Which voice is this?'}, opts:['Passiv','Aktiv'], a:0, noshuffle:true, h:'aktivPassiv', pts:1},
    {t:'mc', q:'Womit bildet man das Passiv?', tr:{ru:'С помощью чего образуется пассив?',en:'How is the passive formed?'}, opts:['werden + Partizip II','haben + Infinitiv','sein + Adjektiv'], a:0, h:'aktivPassiv', pts:1},
    {t:'mc', q:'Aktiv: „Die Bäcker backen Brot."\nWie lautet das Passiv?', tr:{ru:'Как будет в пассиве?',en:'What is the passive?'}, opts:['Brot wird gebacken.','Brot backt.','Brot hat gebacken.'], a:0, h:'aktivPassiv', pts:2},
    {t:'mc', q:'Passiv im Präteritum: „Das Haus ___ gebaut."', tr:{ru:'Пассив в прошедшем: „Das Haus ___ gebaut."',en:'Past passive: "Das Haus ___ gebaut."'}, opts:['wurde','wird','worden'], a:0, h:'aktivPassiv', pts:1},
    {t:'mc', q:'Wann benutzt man das Passiv?', tr:{ru:'Когда используют пассив?',en:'When do you use the passive?'}, opts:['Wenn die Handlung wichtiger ist als der Täter','Wenn man spannend erzählen will','Nur in Gedichten'], a:0, h:'aktivPassiv', pts:1},
    {t:'mc', q:'Aktiv: „Der Lehrer erklärt die Aufgabe."\nPassiv?', tr:{ru:'Как будет в пассиве?',en:'What is the passive?'}, opts:['Die Aufgabe wird erklärt.','Die Aufgabe erklärt.','Der Lehrer wird erklärt.'], a:0, h:'aktivPassiv', pts:2},
    {t:'tf', q:'Richtig oder falsch?\n„Im Passivsatz wird das Akkusativobjekt zum Subjekt."', tr:{ru:'Верно ли: в пассиве дополнение становится подлежащим?',en:'True or false: the object becomes the subject in the passive?'}, a:true, h:'aktivPassiv', pts:1},
  ]},

{ id:'d7-konj', grade:7, subject:'german', icon:'💭',
  title:{de:'Konjunktiv & indirekte Rede',ru:'Конъюнктив и косвенная речь',en:'Subjunctive & Reported Speech'},
  desc:{de:'Wünsche, Träume und Zitate wiedergeben',ru:'Желания, мечты и передача слов',en:'Wishes, dreams and quoting'},
  qs:[
    {t:'mc', q:'„Er sagt, er sei krank."\nWelcher Konjunktiv ist das?', tr:{ru:'Какой это конъюнктив?',en:'Which subjunctive is this?'}, opts:['Konjunktiv I','Konjunktiv II'], a:0, noshuffle:true, h:'konjunktiv', pts:1},
    {t:'mc', q:'„Wenn ich reich wäre, würde ich reisen."\nWelcher Konjunktiv?', tr:{ru:'Какой это конъюнктив?',en:'Which subjunctive?'}, opts:['Konjunktiv II','Konjunktiv I'], a:0, noshuffle:true, h:'konjunktiv', pts:1},
    {t:'mc', q:'Wofür benutzt man Konjunktiv I?', tr:{ru:'Для чего нужен Konjunktiv I?',en:'What is Konjunktiv I for?'}, opts:['für die indirekte Rede','für Wünsche','für Befehle'], a:0, h:'konjunktiv', pts:1},
    {t:'mc', q:'Direkte Rede: „Ich bin müde", sagt Tom.\nIndirekte Rede: Tom sagt, er ___ müde.', tr:{ru:'Косвенная речь: Tom sagt, er ___ müde.',en:'Reported: Tom sagt, er ___ müde.'}, opts:['sei','ist','wäre gewesen'], a:0, h:'konjunktiv', pts:2},
    {t:'mc', q:'Wie bildet man den Konjunktiv II oft?', tr:{ru:'Как часто образуют Konjunktiv II?',en:'How is Konjunktiv II often formed?'}, opts:['mit würde + Grundform','mit haben + Partizip','mit werden + Partizip'], a:0, h:'konjunktiv', pts:1},
    {t:'mc', q:'Welcher Satz drückt einen WUNSCH aus?', tr:{ru:'В каком предложении – желание?',en:'Which sentence expresses a WISH?'}, opts:['Ich hätte gern ein Fahrrad.','Ich habe ein Fahrrad.','Ich hatte ein Fahrrad.'], a:0, h:'konjunktiv', pts:1},
    {t:'text', q:'Konjunktiv II von „sein" (ich ...)?', tr:{ru:'Konjunktiv II глагола „sein" (ich ...)?',en:'Konjunktiv II of "sein" (ich ...)?'}, a:['wäre'], h:'konjunktiv', pts:1},
    {t:'text', q:'Konjunktiv II von „haben" (ich ...)?', tr:{ru:'Konjunktiv II глагола „haben" (ich ...)?',en:'Konjunktiv II of "haben" (ich ...)?'}, a:['hätte'], h:'konjunktiv', pts:1},
  ]},

{ id:'d8-lit', grade:8, subject:'german', icon:'📚',
  title:{de:'Literatur & Stilmittel',ru:'Литература и средства',en:'Literature & Devices'},
  desc:{de:'Gedichte, Fabeln und rhetorische Mittel',ru:'Стихи, басни и приёмы',en:'Poems, fables and rhetorical devices'},
  qs:[
    {t:'mc', q:'„Die Sonne lacht."\nWelches Stilmittel ist das?', tr:{ru:'Какое это средство?',en:'Which device is this?'}, opts:['Personifikation','Vergleich','Alliteration'], a:0, h:'literatur', pts:1},
    {t:'mc', q:'„Stark wie ein Bär."\nWelches Stilmittel?', tr:{ru:'Какое это средство?',en:'Which device?'}, opts:['Vergleich','Metapher','Hyperbel'], a:0, h:'literatur', pts:1},
    {t:'mc', q:'„Milch macht müde Männer munter."\nWelches Stilmittel?', tr:{ru:'Какое это средство?',en:'Which device?'}, opts:['Alliteration','Vergleich','Ironie'], a:0, h:'literatur', pts:1},
    {t:'mc', q:'„Ich habe dir schon tausendmal gesagt ..."\nWelches Stilmittel?', tr:{ru:'Какое это средство?',en:'Which device?'}, opts:['Hyperbel (Übertreibung)','Metapher','Personifikation'], a:0, h:'literatur', pts:1},
    {t:'mc', q:'Reimschema aabb heißt ...', tr:{ru:'Схема рифмы aabb называется ...',en:'Rhyme scheme aabb is called ...'}, opts:['Paarreim','Kreuzreim','umarmender Reim'], a:0, h:'literatur', pts:1},
    {t:'mc', q:'Reimschema abab heißt ...', tr:{ru:'Схема рифмы abab называется ...',en:'Rhyme scheme abab is called ...'}, opts:['Kreuzreim','Paarreim','Schweifreim'], a:0, h:'literatur', pts:1},
    {t:'mc', q:'Was steht am Ende einer FABEL?', tr:{ru:'Что стоит в конце басни?',en:'What comes at the end of a fable?'}, opts:['eine Lehre (Moral)','ein Rätsel','ein Reim'], a:0, h:'literatur', pts:1},
    {t:'mc', q:'Zu welcher Gattung gehört ein Theaterstück?', tr:{ru:'К какому роду относится пьеса?',en:'Which genre is a play?'}, opts:['Dramatik','Lyrik','Epik'], a:0, h:'literatur', pts:1},
    {t:'match', q:'Verbinde Gattung und Beispiel:', tr:{ru:'Соедини род и пример:',en:'Match genre and example:'},
      pairs:[['Lyrik','Gedicht'],['Epik','Roman'],['Dramatik','Theaterstück'],['Fabel','Tiere mit Moral']], h:'literatur', pts:4},
  ]},

{ id:'d9-eroerterung', grade:9, subject:'german', icon:'⚖️',
  title:{de:'Erörterung & Argumentieren',ru:'Аргументация и сочинение',en:'Argumentation & Essays'},
  desc:{de:'Überzeugend schreiben mit These und Argument',ru:'Убедительно писать: тезис и аргумент',en:'Writing convincingly with thesis and arguments'},
  qs:[
    {t:'mc', q:'Wie heißt der Dreischritt beim Argumentieren?', tr:{ru:'Как звучит «три шага» аргументации?',en:'What is the three-step of arguing?'}, opts:['These – Argument – Beispiel','Anfang – Mitte – Ende','Frage – Antwort – Frage'], a:0, h:'textsorten', pts:1},
    {t:'mc', q:'Was ist eine THESE?', tr:{ru:'Что такое тезис?',en:'What is a thesis?'}, opts:['eine Behauptung, die man begründet','ein Beispiel','eine Frage'], a:0, h:'textsorten', pts:1},
    {t:'mc', q:'Was gehört ans ENDE einer Erörterung?', tr:{ru:'Что должно быть в конце сочинения-рассуждения?',en:'What belongs at the END of an essay?'}, opts:['ein Fazit mit eigener Meinung','ein neues Argument','eine Überschrift'], a:0, h:'textsorten', pts:1},
    {t:'mc', q:'Welche Formulierung leitet ein Argument ein?', tr:{ru:'Какая фраза вводит аргумент?',en:'Which phrase introduces an argument?'}, opts:['Ein wichtiger Grund dafür ist ...','Es war einmal ...','Plötzlich ...'], a:0, h:'textsorten', pts:1},
    {t:'mc', q:'Was ist ein GEGENARGUMENT?', tr:{ru:'Что такое контраргумент?',en:'What is a counter-argument?'}, opts:['ein Grund, der gegen die These spricht','ein zweites Beispiel','die Überschrift'], a:0, h:'textsorten', pts:1},
    {t:'mc', q:'In welcher Reihenfolge ordnet man Argumente meist?', tr:{ru:'В каком порядке обычно располагают аргументы?',en:'In which order do you usually put arguments?'}, opts:['vom schwächsten zum stärksten','vom stärksten zum schwächsten','zufällig'], a:0, h:'textsorten', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„In einer Erörterung sollte man Behauptungen immer belegen."', tr:{ru:'Верно ли: утверждения нужно подкреплять?',en:'True or false: claims should always be supported?'}, a:true, h:'textsorten', pts:1},
    {t:'mc', q:'Welcher Satz ist SACHLICH formuliert?', tr:{ru:'Какое предложение сформулировано фактично?',en:'Which sentence is factual?'}, opts:['Studien zeigen, dass Sport die Konzentration verbessert.','Sport ist mega geil!','Wer keinen Sport macht, ist dumm.'], a:0, h:'textsorten', pts:1},
  ]},

{ id:'d10-final', grade:10, subject:'german', icon:'🎓',
  title:{de:'Abschlussprüfung Deutsch',ru:'Выпускной экзамен по немецкому',en:'Final Exam German'},
  desc:{de:'Große Wiederholung: Grammatik, Stil, Textsorten',ru:'Большое повторение: грамматика и тексты',en:'Big revision: grammar, style, text types'},
  qs:[
    {t:'mc', q:'„Das Auto wurde repariert."\nWelche Form?', tr:{ru:'Какая форма?',en:'Which voice?'}, opts:['Passiv Präteritum','Aktiv Präsens','Konjunktiv I'], a:0, h:'aktivPassiv', pts:1},
    {t:'mc', q:'„Er behauptet, er habe nichts gewusst."\nWas ist das?', tr:{ru:'Что это?',en:'What is this?'}, opts:['indirekte Rede (Konjunktiv I)','direkte Rede','Passiv'], a:0, h:'konjunktiv', pts:1},
    {t:'mc', q:'„Das Leben ist eine Reise."\nStilmittel?', tr:{ru:'Какое средство?',en:'Which device?'}, opts:['Metapher','Vergleich','Alliteration'], a:0, h:'literatur', pts:1},
    {t:'mc', q:'Wo fehlt ein Komma?\n„Ich weiß dass du kommst."', tr:{ru:'Где не хватает запятой?',en:'Where is a comma missing?'}, opts:['vor „dass"','nach „weiß du"','am Ende'], a:0, h:'zeichen', pts:1},
    {t:'mc', q:'In welcher Zeitform schreibt man eine Inhaltsangabe?', tr:{ru:'В каком времени пишут краткое содержание?',en:'Which tense for a summary?'}, opts:['Präsens','Präteritum','Perfekt'], a:0, h:'textsorten', pts:1},
    {t:'mc', q:'„Ich helfe meinem Bruder."\nIn welchem Fall steht „meinem Bruder"?', tr:{ru:'В каком падеже?',en:'Which case?'}, opts:['Dativ','Akkusativ','Genitiv'], a:0, h:'faelle', pts:1},
    {t:'mc', q:'Welcher Satz enthält einen Relativsatz?', tr:{ru:'В каком предложении есть определительное придаточное?',en:'Which sentence has a relative clause?'}, opts:['Der Mann, der dort steht, ist mein Onkel.','Ich gehe nach Hause.','Komm bitte her!'], a:0, h:'satzgefuege', pts:1},
    {t:'mc', q:'Wie schreibt man richtig?\n„Wir treffen uns am ___."', tr:{ru:'Как правильно?',en:'Which is correct?'}, opts:['Mittwochabend','mittwochabend','Mittwoch abend'], a:0, h:'grossklein', pts:1},
    {t:'mc', q:'Was ist ein Synonym für „Ergebnis"?', tr:{ru:'Синоним слова „Ergebnis"?',en:'Synonym of "Ergebnis"?'}, opts:['Resultat','Anfang','Aufgabe'], a:0, h:'synonyme', pts:1},
    {t:'mc', q:'Welcher Satz steht im Konjunktiv II?', tr:{ru:'Какое предложение в Konjunktiv II?',en:'Which sentence is Konjunktiv II?'}, opts:['Ich würde gern mitkommen.','Ich komme mit.','Ich bin mitgekommen.'], a:0, h:'konjunktiv', pts:1},
  ]},

/* ================= ENGLISCH ================= */
{ id:'e6-past', grade:6, subject:'english', icon:'⏮️', genTest:true,
  title:{de:'Simple Past',ru:'Simple Past',en:'Simple Past'},
  desc:{de:'Die einfache Vergangenheit + unregelmäßige Verben',ru:'Прошедшее время и неправильные глаголы',en:'The simple past and irregular verbs'},
  gen(){ return [qIrregPast(),qIrregPast(),qIrregPast(),qIrregPast(),
    {t:'mc', q:'She ___ to school yesterday.', tr:{ru:'Выбери: She ___ to school yesterday.',en:'Choose: She ___ to school yesterday.'}, opts:['walked','walks','walk'], a:0, h:'engPast', pts:1},
    {t:'mc', q:'Verneine richtig: „He played football." →', tr:{ru:'Отрицание: „He played football." →',en:'Negate: "He played football." →'}, opts:['He didn’t play football.','He didn’t played football.','He not played football.'], a:0, h:'engPast', pts:1},
    {t:'mc', q:'Welche Frage ist richtig?', tr:{ru:'Какой вопрос правильный?',en:'Which question is correct?'}, opts:['Did you see the film?','Did you saw the film?','You did see the film?'], a:0, h:'engPast', pts:1},
    {t:'text', q:'Simple Past von „study": I ___ for the test.', tr:{ru:'Simple Past глагола „study"?',en:'Simple past of "study"?'}, a:['studied'], h:'engPast', pts:1}]; } },

{ id:'e6-irreg', grade:6, subject:'english', icon:'📋', genTest:true,
  title:{de:'Unregelmäßige Verben – Drill',ru:'Неправильные глаголы – тренировка',en:'Irregular Verbs Drill'},
  desc:{de:'Die 2. und 3. Form auswendig können',ru:'Вторая и третья формы наизусть',en:'Learning the 2nd and 3rd forms'},
  gen(){ const qs=[]; for(let i=0;i<6;i++) qs.push(qIrregPast()); for(let i=0;i<6;i++) qs.push(qIrregPart()); return qs; } },

{ id:'e6-prog', grade:6, subject:'english', icon:'🔄',
  title:{de:'Present Progressive',ru:'Present Progressive',en:'Present Progressive'},
  desc:{de:'Was passiert gerade jetzt?',ru:'Что происходит прямо сейчас?',en:'What is happening right now?'},
  qs:[
    {t:'mc', q:'Look! She ___ a book.', tr:{ru:'Выбери: Look! She ___ a book.',en:'Choose: Look! She ___ a book.'}, opts:['is reading','reads','read'], a:0, h:'engProgressive', pts:1},
    {t:'mc', q:'I ___ TV at the moment.', tr:{ru:'Выбери: I ___ TV at the moment.',en:'Choose: I ___ TV at the moment.'}, opts:['am watching','watch','watches'], a:0, h:'engProgressive', pts:1},
    {t:'mc', q:'They ___ football now.', tr:{ru:'Выбери: They ___ football now.',en:'Choose: They ___ football now.'}, opts:['are playing','play','is playing'], a:0, h:'engProgressive', pts:1},
    {t:'text', q:'Schreibe die ing-Form von „make":', tr:{ru:'ing-форма глагола „make"?',en:'ing-form of "make"?'}, a:['making'], h:'engProgressive', pts:1},
    {t:'text', q:'Schreibe die ing-Form von „sit":', tr:{ru:'ing-форма глагола „sit"?',en:'ing-form of "sit"?'}, a:['sitting'], h:'engProgressive', pts:1},
    {t:'mc', q:'Welches Signalwort passt zum Present Progressive?', tr:{ru:'Какое слово-сигнал для Present Progressive?',en:'Which signal word fits the present progressive?'}, opts:['at the moment','every day','usually'], a:0, h:'engProgressive', pts:1},
    {t:'mc', q:'„Every Monday I ___ swimming."', tr:{ru:'Выбери: „Every Monday I ___ swimming."',en:'Choose: "Every Monday I ___ swimming."'}, opts:['go','am going','going'], a:0, h:'engSimplePres', pts:1},
    {t:'mc', q:'Past Progressive: „I ___ TV when he came."', tr:{ru:'Past Progressive: „I ___ TV when he came."',en:'Past progressive: "I ___ TV when he came."'}, opts:['was watching','watched','am watching'], a:0, h:'engProgressive', pts:1},
  ]},

{ id:'e7-perfect', grade:7, subject:'english', icon:'✅', genTest:true,
  title:{de:'Present Perfect',ru:'Present Perfect',en:'Present Perfect'},
  desc:{de:'have/has + 3. Form – mit Bezug zu jetzt',ru:'have/has + 3-я форма',en:'have/has + past participle'},
  gen(){ return [qIrregPart(),qIrregPart(),qIrregPart(),
    {t:'mc', q:'I ___ my homework. (Ergebnis zählt jetzt)', tr:{ru:'Выбери: I ___ my homework.',en:'Choose: I ___ my homework.'}, opts:['have finished','finished','am finishing'], a:0, h:'engPerfect', pts:1},
    {t:'mc', q:'She ___ never ___ to London.', tr:{ru:'Выбери: She ___ never ___ to London.',en:'Choose: She ___ never ___ to London.'}, opts:['has / been','have / been','has / was'], a:0, h:'engPerfect', pts:1},
    {t:'mc', q:'Welches Signalwort gehört zum Present Perfect?', tr:{ru:'Какое слово-сигнал у Present Perfect?',en:'Which signal word belongs to the present perfect?'}, opts:['already','yesterday','last year'], a:0, h:'engPerfect', pts:1},
    {t:'mc', q:'Welches Signalwort gehört zum Simple Past?', tr:{ru:'Какое слово-сигнал у Simple Past?',en:'Which signal word belongs to the simple past?'}, opts:['yesterday','just','since'], a:0, h:'engPast', pts:1},
    {t:'mc', q:'„I ___ my keys, so I can’t open the door."', tr:{ru:'Выбери правильную форму.',en:'Choose the correct form.'}, opts:['have lost','lost','was losing'], a:0, h:'engPerfect', pts:2}]; } },

{ id:'e7-comp', grade:7, subject:'english', icon:'📊', genTest:true,
  title:{de:'Steigerung & Vergleiche',ru:'Степени сравнения',en:'Comparison of Adjectives'},
  desc:{de:'bigger, the biggest, more interesting ...',ru:'bigger, the biggest, more interesting',en:'bigger, the biggest, more interesting'},
  gen(){ return [qCompAdj(),qCompAdj(),qCompAdj(),qCompAdj(),
    {t:'mc', q:'She is ___ than her brother.', tr:{ru:'Выбери: She is ___ than her brother.',en:'Choose: She is ___ than her brother.'}, opts:['taller','tallest','more tall'], a:0, h:'engComp', pts:1},
    {t:'mc', q:'This is ___ film I have ever seen.', tr:{ru:'Выбери: This is ___ film I have ever seen.',en:'Choose: This is ___ film I have ever seen.'}, opts:['the best','the better','the goodest'], a:0, h:'engComp', pts:1},
    {t:'mc', q:'My bag is as heavy ___ yours.', tr:{ru:'Выбери: My bag is as heavy ___ yours.',en:'Choose: My bag is as heavy ___ yours.'}, opts:['as','than','that'], a:0, h:'engComp', pts:1},
    {t:'mc', q:'Wie steigert man lange Adjektive?', tr:{ru:'Как сравнивают длинные прилагательные?',en:'How do you compare long adjectives?'}, opts:['mit more / most','mit -er / -est','gar nicht'], a:0, h:'engComp', pts:1}]; } },

{ id:'e8-cond', grade:8, subject:'english', icon:'🔀',
  title:{de:'If-Sätze (Conditionals)',ru:'Условные предложения',en:'Conditional Sentences'},
  desc:{de:'Typ I, II und III sicher unterscheiden',ru:'Типы I, II и III',en:'Telling types I, II and III apart'},
  qs:[
    {t:'mc', q:'If it rains, I ___ at home.', tr:{ru:'Выбери: If it rains, I ___ at home.',en:'Choose: If it rains, I ___ at home.'}, opts:['will stay','stayed','would stay'], a:0, h:'engConditional', pts:1},
    {t:'mc', q:'If I ___ rich, I would travel the world.', tr:{ru:'Выбери: If I ___ rich, I would travel.',en:'Choose: If I ___ rich, I would travel.'}, opts:['were','am','will be'], a:0, h:'engConditional', pts:1},
    {t:'mc', q:'Welcher Typ ist: „If I had known, I would have helped."?', tr:{ru:'Какой это тип?',en:'Which type is this?'}, opts:['Typ III','Typ I','Typ II'], a:0, h:'engConditional', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Im if-Teil darf man „will" benutzen."', tr:{ru:'Верно ли: в части с if можно ставить „will"?',en:'True or false: you may use "will" in the if-clause?'}, a:false, h:'engConditional', pts:1},
    {t:'mc', q:'Typ I beschreibt ...', tr:{ru:'Тип I описывает ...',en:'Type I describes ...'}, opts:['etwas Reales, das passieren kann','einen Traum','die Vergangenheit'], a:0, h:'engConditional', pts:1},
    {t:'mc', q:'If she studies harder, she ___ better marks.', tr:{ru:'Выбери форму.',en:'Choose the form.'}, opts:['will get','would get','got'], a:0, h:'engConditional', pts:1},
    {t:'mc', q:'If I were you, I ___ him.', tr:{ru:'Выбери форму.',en:'Choose the form.'}, opts:['would call','will call','called'], a:0, h:'engConditional', pts:1},
    {t:'mc', q:'Welcher Satz ist Typ II?', tr:{ru:'Какое предложение – тип II?',en:'Which sentence is type II?'}, opts:['If I won the lottery, I would buy a car.','If I win, I will buy a car.','If I had won, I would have bought a car.'], a:0, h:'engConditional', pts:1},
  ]},

{ id:'e9-passive', grade:9, subject:'english', icon:'🔄',
  title:{de:'Passive Voice',ru:'Пассивный залог',en:'Passive Voice'},
  desc:{de:'Sätze ins Passiv setzen',ru:'Превращаем предложения в пассив',en:'Turning sentences into the passive'},
  qs:[
    {t:'mc', q:'„Shakespeare wrote Hamlet." → Passive:', tr:{ru:'Пассив от „Shakespeare wrote Hamlet."',en:'Passive of "Shakespeare wrote Hamlet."'}, opts:['Hamlet was written by Shakespeare.','Hamlet is written by Shakespeare.','Hamlet has written by Shakespeare.'], a:0, h:'engPassive', pts:2},
    {t:'mc', q:'„They build houses." → Passive:', tr:{ru:'Пассив от „They build houses."',en:'Passive of "They build houses."'}, opts:['Houses are built.','Houses is built.','Houses were built.'], a:0, h:'engPassive', pts:2},
    {t:'mc', q:'Womit bildet man das Passive?', tr:{ru:'С помощью чего образуется пассив?',en:'How is the passive formed?'}, opts:['form of "be" + past participle','do + infinitive','have + ing-form'], a:0, h:'engPassive', pts:1},
    {t:'mc', q:'Welches Wort nennt den Täter im Passivsatz?', tr:{ru:'Какое слово вводит исполнителя?',en:'Which word introduces the agent?'}, opts:['by','from','with'], a:0, h:'engPassive', pts:1},
    {t:'mc', q:'„The letter ___ yesterday." (send)', tr:{ru:'Выбери форму.',en:'Choose the form.'}, opts:['was sent','is sent','sends'], a:0, h:'engPassive', pts:1},
    {t:'mc', q:'„English ___ all over the world." (speak)', tr:{ru:'Выбери форму.',en:'Choose the form.'}, opts:['is spoken','speaks','has spoken'], a:0, h:'engPassive', pts:1},
    {t:'mc', q:'Wann nutzt man das Passiv?', tr:{ru:'Когда используют пассив?',en:'When do you use the passive?'}, opts:['Wenn die Handlung wichtiger ist als der Täter','Immer in Fragen','Nur in Gedichten'], a:0, h:'engPassive', pts:1},
    {t:'mc', q:'„Somebody has stolen my bike." → Passive:', tr:{ru:'Пассив?',en:'Passive?'}, opts:['My bike has been stolen.','My bike is stolen by somebody.','My bike was stealing.'], a:0, h:'engPassive', pts:2},
  ]},

{ id:'e10-final', grade:10, subject:'english', icon:'🎓', genTest:true,
  title:{de:'Abschlussprüfung Englisch',ru:'Выпускной экзамен по английскому',en:'Final Exam English'},
  desc:{de:'Alle Zeiten, Passiv und If-Sätze gemischt',ru:'Все времена, пассив и условные',en:'All tenses, passive and conditionals mixed'},
  gen(){ return [qIrregPast(),qIrregPart(),qCompAdj(),qCompAdj(),
    {t:'mc', q:'She ___ in London since 2019.', tr:{ru:'Выбери форму.',en:'Choose the form.'}, opts:['has lived','lives','lived'], a:0, h:'engPerfect', pts:1},
    {t:'mc', q:'The book ___ by millions of people.', tr:{ru:'Выбери форму.',en:'Choose the form.'}, opts:['has been read','has read','is reading'], a:0, h:'engPassive', pts:1},
    {t:'mc', q:'If I had more time, I ___ a new language.', tr:{ru:'Выбери форму.',en:'Choose the form.'}, opts:['would learn','will learn','learned'], a:0, h:'engConditional', pts:1},
    {t:'mc', q:'While I ___ , the phone rang.', tr:{ru:'Выбери форму.',en:'Choose the form.'}, opts:['was cooking','cooked','cook'], a:0, h:'engProgressive', pts:1},
    {t:'mc', q:'I ___ visit my grandma next weekend. (fester Plan)', tr:{ru:'Выбери форму (план).',en:'Choose the form (plan).'}, opts:['am going to','will','would'], a:0, h:'engFuture', pts:1},
    {t:'mc', q:'He asked me where I ___ from.', tr:{ru:'Выбери форму.',en:'Choose the form.'}, opts:['came','come','have come'], a:0, h:'engPast', pts:1}]; } },
];
