/* ============ LESSON CATALOGUE ============
   Every lesson key matches the `h` key used by questions, so each question
   always knows the exact lesson it came from.
   Row format: [key, grade, subject, titleDE, titleRU, titleEN]           */
const LESSON_ROWS = [
/* ---------- Klasse 1–3 ---------- */
['zr10',1,'math','Zahlen bis 10','Числа до 10','Numbers up to 10'],
['zr100',2,'math','Zahlen bis 100','Числа до 100','Numbers up to 100'],
['plusminus',2,'math','Plus und Minus im Kopf','Сложение и вычитание в уме','Mental addition & subtraction'],
['einmaleins',3,'math','Das kleine Einmaleins','Таблица умножения','Times tables'],
['uhrLesen',2,'math','Die Uhr lesen','Учимся читать часы','Reading the clock'],
['geldZaehlen',3,'math','Mit Geld rechnen','Считаем деньги','Working with money'],
['geoFormen',2,'math','Formen und Körper','Фигуры и тела','Shapes and solids'],
['lesenStart',1,'german','Lesen lernen','Учимся читать','Learning to read'],
['schreibenStart',1,'german','Erstes Schreiben','Первое письмо','First writing'],
/* ---------- Mathematik 4–5 ---------- */
['mental',4,'math','Kopfrechnen-Tricks','Приёмы устного счёта','Mental maths tricks'],
['addSub',4,'math','Schriftlich addieren & subtrahieren','Сложение и вычитание в столбик','Column addition & subtraction'],
['multWritten',4,'math','Schriftliche Multiplikation','Умножение в столбик','Written multiplication'],
['division',4,'math','Schriftliche Division','Деление в столбик','Long division'],
['divDigits',4,'math','Überschlag: Wie viele Stellen?','Прикидка: сколько цифр?','Estimating the digits'],
['remainder',4,'math','Division mit Rest','Деление с остатком','Division with remainder'],
['rounding',4,'math','Runden','Округление','Rounding'],
['placeValue',4,'math','Stellenwerte','Разряды чисел','Place value'],
['compareNum',4,'math','Zahlen vergleichen','Сравнение чисел','Comparing numbers'],
['units',4,'math','Größen & Einheiten','Величины и единицы','Units and measures'],
['timeCalc',4,'math','Zeitspannen berechnen','Вычисление времени','Calculating time spans'],
['wordProblem',4,'math','Sachaufgaben lösen','Решение текстовых задач','Solving word problems'],
['wordDiv',4,'math','Sachaufgaben mit Division','Задачи на деление','Division word problems'],
['compare',4,'math','Angebote vergleichen','Сравнение предложений','Comparing offers'],
['geoLines',4,'math','Parallel und senkrecht','Параллельно и перпендикулярно','Parallel and perpendicular'],
['quadri',4,'math','Vierecke und ihre Eigenschaften','Четырёхугольники','Quadrilaterals'],
['periArea',5,'math','Umfang & Flächeninhalt','Периметр и площадь','Perimeter and area'],
['diagram',5,'math','Diagramme lesen','Чтение диаграмм','Reading charts'],
['coords',5,'math','Koordinatensystem','Система координат','Coordinate system'],
['divisibility',5,'math','Teilbarkeitsregeln','Признаки делимости','Divisibility rules'],
['orderOps',5,'math','Punkt vor Strich','Порядок действий','Order of operations'],
/* ---------- Mathematik 6–10 ---------- */
['frac',6,'math','Brüche: kürzen & erweitern','Дроби: сокращение','Fractions: simplifying'],
['fracOps',6,'math','Bruchrechnen: + − · :','Действия с дробями','Fraction arithmetic'],
['decimal',6,'math','Dezimalzahlen','Десятичные дроби','Decimal numbers'],
['angles',6,'math','Winkel','Углы','Angles'],
['negNum',7,'math','Negative Zahlen','Отрицательные числа','Negative numbers'],
['percent',7,'math','Prozentrechnung','Проценты','Percentages'],
['dreisatz',7,'math','Dreisatz','Правило трёх','Rule of three'],
['term',7,'math','Terme aufstellen & vereinfachen','Выражения','Terms and expressions'],
['equation',7,'math','Gleichungen lösen','Решение уравнений','Solving equations'],
['linfunc',8,'math','Lineare Funktionen','Линейные функции','Linear functions'],
['lgs',8,'math','Lineare Gleichungssysteme','Системы уравнений','Systems of equations'],
['volume',8,'math','Volumen & Oberfläche','Объём и поверхность','Volume and surface'],
['stats',8,'math','Statistik: Mittelwert & Median','Статистика','Statistics'],
['prob2',8,'math','Wahrscheinlichkeit','Вероятность','Probability'],
['speed',8,'math','Geschwindigkeit, Weg, Zeit','Скорость, путь, время','Speed, distance, time'],
['pythagoras',9,'math','Satz des Pythagoras','Теорема Пифагора','Pythagorean theorem'],
['powroot',9,'math','Potenzen & Wurzeln','Степени и корни','Powers and roots'],
['zins',9,'math','Zinsrechnung','Проценты по вкладам','Interest calculation'],
['quad',10,'math','Quadratische Gleichungen','Квадратные уравнения','Quadratic equations'],
['trig',10,'math','Trigonometrie: sin, cos, tan','Тригонометрия','Trigonometry'],
/* ---------- Deutsch ---------- */
['wortarten',4,'german','Wortarten erkennen','Части речи','Parts of speech'],
['nomen',4,'german','Nomen: Artikel & Mehrzahl','Существительные','Nouns: article & plural'],
['verben',4,'german','Verben konjugieren','Спряжение глаголов','Conjugating verbs'],
['adjektive',4,'german','Adjektive & Steigerung','Прилагательные','Adjectives & comparison'],
['zeiten',4,'german','Die Zeitformen','Времена глагола','German tenses'],
['faelle',4,'german','Die 4 Fälle','4 падежа','The four cases'],
['satzglieder',4,'german','Satzglieder bestimmen','Члены предложения','Sentence parts'],
['satzarten',4,'german','Satzarten','Виды предложений','Sentence types'],
['rechtIE',4,'german','Rechtschreibung: ie und Dehnungs-h','Правописание: ie и h','Spelling: ie and long vowels'],
['rechtDoppel',4,'german','Doppelte Konsonanten, ck, tz','Двойные согласные','Double consonants, ck, tz'],
['rechtSS',4,'german','ß oder ss','ß или ss','ß or ss'],
['rechtEnd',4,'german','Auslaut: b/p, d/t, g/k','Конечные согласные','Final consonants'],
['woertlRede',4,'german','Wörtliche Rede','Прямая речь','Direct speech'],
['lesen',4,'german','Leseverstehen','Понимание текста','Reading comprehension'],
['wortfamilie',5,'german','Wortfamilien & Wortfelder','Семьи слов','Word families and fields'],
['synonyme',5,'german','Synonyme & Antonyme','Синонимы и антонимы','Synonyms and antonyms'],
['grossklein',5,'german','Groß- und Kleinschreibung','Заглавные буквы','Capitalisation'],
['kommas',5,'german','Kommas bei Aufzählungen','Запятые при перечислении','Commas in lists'],
['satzgefuege',6,'german','Haupt- und Nebensätze','Главные и придаточные','Main and subordinate clauses'],
['textsorten',6,'german','Textsorten: Bericht, Beschreibung, Inhaltsangabe','Типы текстов','Text types'],
['aktivPassiv',7,'german','Aktiv und Passiv','Актив и пассив','Active and passive'],
['konjunktiv',7,'german','Konjunktiv & indirekte Rede','Конъюнктив','Subjunctive & reported speech'],
['zeichen',7,'german','Zeichensetzung','Пунктуация','Punctuation'],
['literatur',8,'german','Literatur & Stilmittel','Литература и приёмы','Literature and devices'],
/* ---------- Englisch ---------- */
['engVocab',4,'english','Vokabeln lernen','Учим слова','Learning vocabulary'],
['engTobe',5,'english','to be – am, is, are','Глагол to be','The verb to be'],
['engHave',5,'english','have got / has got','have got / has got','have got / has got'],
['engPlural',5,'english','Plural im Englischen','Множественное число','English plurals'],
['engArticles',5,'english','a oder an','a или an','a or an'],
['engQuestions',5,'english','Fragewörter & Fragen','Вопросы','Questions and question words'],
['engSimplePres',5,'english','Simple Present','Simple Present','Simple Present'],
['engCan',5,'english','can und can’t','can и can’t','can and can’t'],
['engTime',5,'english','Uhrzeit & Datum','Время и дата','Telling the time'],
['engPast',6,'english','Simple Past','Simple Past','Simple Past'],
['engIrregular',6,'english','Unregelmäßige Verben','Неправильные глаголы','Irregular verbs'],
['engProgressive',6,'english','Present & Past Progressive','Progressive формы','Progressive tenses'],
['engPrepositions',6,'english','Präpositionen','Предлоги','Prepositions'],
['engPerfect',7,'english','Present Perfect','Present Perfect','Present Perfect'],
['engComp',7,'english','Steigerung der Adjektive','Степени сравнения','Comparison of adjectives'],
['engModals',7,'english','Modalverben','Модальные глаголы','Modal verbs'],
['engFuture',8,'english','Zukunft: will & going to','Будущее время','The future: will & going to'],
['engConditional',8,'english','If-Sätze','Условные предложения','Conditionals'],
['engRelative',8,'english','Relativsätze','Относительные придаточные','Relative clauses'],
['engPassive',9,'english','Passive Voice','Пассивный залог','Passive voice'],
['engReported',9,'english','Indirekte Rede','Косвенная речь','Reported speech'],
['engWriting',9,'english','Englisch schreiben: E-Mail & Text','Письмо на английском','Writing in English'],
/* ---------- Französisch ---------- */
['frBasics',6,'franz','Bonjour! Erste Schritte','Первые шаги','First steps'],
['frNumbers',6,'franz','Zahlen & Datum','Числа и дата','Numbers and dates'],
['frVocabDaily',6,'franz','Alltagswortschatz','Повседневные слова','Everyday vocabulary'],
['frVerbs',7,'franz','Verben auf -er & Verneinung','Глаголы на -er','-er verbs and negation'],
['frAdjectives',7,'franz','Adjektive','Прилагательные','Adjectives'],
['frPasse',8,'franz','Passé composé','Passé composé','Passé composé'],
/* ---------- Spanisch ---------- */
['esBasics',6,'spanisch','¡Hola! Erste Schritte','Первые шаги','First steps'],
['esVocab',6,'spanisch','Grundwortschatz','Базовая лексика','Core vocabulary'],
['esVerbs',7,'spanisch','Verben im Präsens','Глаголы в настоящем','Present tense verbs'],
['esSerEstar',7,'spanisch','ser und estar','ser и estar','ser and estar'],
/* ---------- Russisch ---------- */
['ruAlphabet',5,'russisch','Das kyrillische Alphabet','Кириллица','The Cyrillic alphabet'],
['ruBasics',5,'russisch','Erste Wörter & Sätze','Первые слова','First words and phrases'],
['ruVocab',6,'russisch','Grundwortschatz','Базовая лексика','Core vocabulary'],
['ruVerbs',7,'russisch','Verben & Aspekt','Глаголы и вид','Verbs and aspect'],
['ruCases',8,'russisch','Die 6 Fälle','6 падежей','The six cases'],
/* ---------- Sachunterricht / Bio / Geo / Physik / Chemie / Geschichte / Politik / Info ---------- */
['kalender',4,'sach','Kalender & Jahreszeiten','Календарь','Calendar and seasons'],
['sachMap',4,'sach','Deutschland & Karten','Германия и карты','Germany and maps'],
['sachWater',4,'sach','Wasserkreislauf','Круговорот воды','The water cycle'],
['sachStrom',4,'sach','Stromkreis','Электрическая цепь','Electric circuits'],
['sachVerkehr',4,'sach','Verkehr & Fahrrad','Дорожное движение','Traffic and bicycles'],
['sachBody',4,'sach','Körper & Ernährung','Тело и питание','Body and nutrition'],
['bioMammal',5,'bio','Säugetiere: Hund & Katze','Млекопитающие','Mammals: dog and cat'],
['bioSkeleton',5,'bio','Skelett & Muskeln','Скелет и мышцы','Skeleton and muscles'],
['bioVertebrates',5,'bio','Die 5 Wirbeltierklassen','Классы позвоночных','The vertebrate classes'],
['bioBirds',5,'bio','Vögel','Птицы','Birds'],
['bioFood',5,'bio','Gesunde Ernährung','Здоровое питание','Healthy eating'],
['bioZelle',6,'bio','Zellen & Fotosynthese','Клетки и фотосинтез','Cells and photosynthesis'],
['bioOeko',8,'bio','Ökologie & Nahrungsketten','Экология','Ecology and food chains'],
['geoWorld',5,'geo','Kontinente & Ozeane','Континенты и океаны','Continents and oceans'],
['geoGermany',5,'geo','Deutschland & NRW','Германия и NRW','Germany and NRW'],
['geoMapSkills',5,'geo','Karte, Kompass, Maßstab','Карта и масштаб','Maps, compass, scale'],
['geoEurope',5,'geo','Europa','Европа','Europe'],
['geoKlima',6,'geo','Klimazonen','Климатические пояса','Climate zones'],
['geoStadt',8,'geo','Stadt, Land & Wirtschaft','Город и экономика','City, country, economy'],
['phMech',6,'physik','Mechanik: Masse, Dichte, Kraft','Механика','Mechanics'],
['phOptik',7,'physik','Optik & Wärme','Оптика и тепло','Optics and heat'],
['phStrom',8,'physik','Elektrizität & Ohmsches Gesetz','Электричество и закон Ома','Electricity and Ohm’s law'],
['chStoffe',7,'chemie','Stoffe & Trennverfahren','Вещества и разделение','Substances and separation'],
['chAtom',8,'chemie','Atome & Reaktionen','Атомы и реакции','Atoms and reactions'],
['gesAntike',6,'geschichte','Antike: Ägypten, Griechen, Römer','Древний мир','Antiquity'],
['gesMittelalter',7,'geschichte','Mittelalter','Средневековье','The Middle Ages'],
['gesNeuzeit',8,'geschichte','Neuzeit: Entdeckungen & Revolution','Новое время','The modern era'],
['ges20',9,'geschichte','20. Jahrhundert','XX век','The 20th century'],
['polDemokratie',7,'politik','Demokratie & Grundgesetz','Демократия','Democracy and constitution'],
['polWirtschaft',9,'politik','Wirtschaft & Europa','Экономика и Европа','Economy and Europe'],
['infoComputer',5,'info','Computer: Hardware & Software','Компьютер','Computer basics'],
['infoInternet',5,'info','Internet & Sicherheit','Интернет и безопасность','Internet and safety'],
['infoScratch',5,'info','Algorithmen & Scratch','Алгоритмы и Scratch','Algorithms and Scratch'],
['infoDaten',5,'info','Dateien, Daten & Binärsystem','Файлы и данные','Files, data, binary'],
['infoOffice',7,'info','Tabellen & Präsentationen','Таблицы и презентации','Spreadsheets and slides'],
['infoCode',9,'info','Programmieren mit Python','Программирование на Python','Programming with Python'],
];

const LESSONS = {};
LESSON_ROWS.forEach(([key,grade,subject,de,ru,en])=>{
  LESSONS[key] = {key, grade, subject, title:{de,ru,en}};
});
function lessonTitle(key){
  const l = LESSONS[key];
  if(!l) return key;
  return l.title[LANG] || l.title.de;
}
function lessonExists(key){ return !!LESSONS[key]; }
