/* ============ INFORMATIK – Klasse 5 (Realschule NRW) ============ */
const TESTS_INFO = [

{ id:'i5-computer', grade:5, subject:'info', icon:'💻',
  title:{de:'Computer: Hardware & Software',ru:'Компьютер: железо и программы',en:'Computer: Hardware & Software'},
  desc:{de:'Das EVA-Prinzip und die Teile des Computers',ru:'Принцип EVA и части компьютера',en:'The IPO principle and computer parts'},
  qs:[
    {t:'mc', q:'Wofür steht das EVA-Prinzip?', tr:{ru:'Что означает принцип EVA?',en:'What does the EVA principle stand for?'},
      opts:['Eingabe – Verarbeitung – Ausgabe','Ein- und Ausschalten','Erst Videos Ansehen'], a:0, h:'infoComputer', pts:1},
    {t:'mc', q:'Welches Gerät ist ein EINGABEGERÄT?', tr:{ru:'Какое устройство – устройство ВВОДА?',en:'Which device is an INPUT device?'}, opts:['die Tastatur','der Monitor','der Drucker','der Lautsprecher'], a:0, h:'infoComputer', pts:1},
    {t:'mc', q:'Welches Gerät ist ein AUSGABEGERÄT?', tr:{ru:'Какое устройство – устройство ВЫВОДА?',en:'Which device is an OUTPUT device?'}, opts:['der Monitor','die Maus','das Mikrofon','der Scanner'], a:0, h:'infoComputer', pts:1},
    {t:'mc', q:'Wie nennt man das „Gehirn" des Computers?', tr:{ru:'Как называется «мозг» компьютера?',en:'What is the computer’s "brain" called?'}, opts:['Prozessor (CPU)','Monitor','Netzteil','Kabel'], a:0, h:'infoComputer', pts:1},
    {t:'mc', q:'Was ist SOFTWARE?', tr:{ru:'Что такое SOFTWARE?',en:'What is SOFTWARE?'},
      opts:['Programme, die auf dem Computer laufen','alle Teile, die man anfassen kann','das Gehäuse des Computers'], a:0, h:'infoComputer', pts:1},
    {t:'mc', q:'Welches ist ein Betriebssystem?', tr:{ru:'Что из этого – операционная система?',en:'Which is an operating system?'}, opts:['Windows','Tastatur','YouTube','WLAN'], a:0, h:'infoComputer', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Die Festplatte (SSD) speichert Daten auch, wenn der Computer aus ist."', tr:{ru:'Верно ли: жёсткий диск (SSD) хранит данные, даже когда компьютер выключен?',en:'True or false: the hard drive (SSD) keeps data even when the computer is off?'}, a:true, h:'infoComputer', pts:1},
    {t:'match', q:'Verbinde Gerät und Aufgabe:', tr:{ru:'Соедини устройство и задачу:',en:'Match device and job:'},
      pairs:[['Tastatur','Text eingeben'],['Monitor','Bilder anzeigen'],['Drucker','auf Papier ausgeben'],['Mikrofon','Ton aufnehmen']], h:'infoComputer', pts:4},
  ]},

{ id:'i5-internet', grade:5, subject:'info', icon:'🌐',
  title:{de:'Internet & Sicherheit',ru:'Интернет и безопасность',en:'Internet & Safety'},
  desc:{de:'Sicher surfen, starke Passwörter, kluge Entscheidungen',ru:'Безопасный интернет, надёжные пароли',en:'Safe surfing, strong passwords, smart choices'},
  qs:[
    {t:'mc', q:'Was ist das Internet?', tr:{ru:'Что такое интернет?',en:'What is the internet?'},
      opts:['ein weltweites Netzwerk aus Computern','ein einzelner Riesencomputer','ein Fernsehprogramm'], a:0, h:'infoInternet', pts:1},
    {t:'mc', q:'Mit welchem Programm besuchst du Webseiten?', tr:{ru:'Какой программой открывают сайты?',en:'With which program do you visit websites?'}, opts:['mit einem Browser (z. B. Chrome, Firefox)','mit einem Drucker-Treiber','mit dem Taschenrechner'], a:0, h:'infoInternet', pts:1},
    {t:'mc', q:'Woran erkennst du eine E-Mail-Adresse?', tr:{ru:'Как узнать адрес электронной почты?',en:'How do you recognise an e-mail address?'}, opts:['am @-Zeichen','am €-Zeichen','am !-Zeichen'], a:0, h:'infoInternet', pts:1},
    {t:'mc', q:'Welches Passwort ist am SICHERSTEN?', tr:{ru:'Какой пароль самый НАДЁЖНЫЙ?',en:'Which password is the SAFEST?'},
      opts:['Blau!Tiger7&Rad','123456','passwort','dein Vorname'], a:0, h:'infoInternet', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Ich darf mein Passwort meinem besten Freund verraten."', tr:{ru:'Верно ли: можно сказать пароль лучшему другу?',en:'True or false: I may tell my password to my best friend?'}, a:false, h:'infoInternet', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Ich gebe Fremden im Internet niemals meinen echten Namen und meine Adresse."', tr:{ru:'Верно ли: незнакомцам в интернете никогда не сообщают имя и адрес?',en:'True or false: never give strangers online your real name and address?'}, a:true, h:'infoInternet', pts:1},
    {t:'mc', q:'Du bekommst eine komische Nachricht von einem Fremden. Was tust du?', tr:{ru:'Тебе пришло странное сообщение от незнакомца. Что делать?',en:'You get a strange message from a stranger. What do you do?'},
      opts:['Nicht antworten und einem Erwachsenen zeigen','sofort antworten','den Link anklicken'], a:0, h:'infoInternet', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Alles, was im Internet steht, ist wahr."', tr:{ru:'Верно ли: всё, что написано в интернете, – правда?',en:'True or false: everything on the internet is true?'}, a:false, h:'infoInternet', pts:1},
  ]},

{ id:'i5-scratch', grade:5, subject:'info', icon:'🐱',
  title:{de:'Algorithmen & Scratch',ru:'Алгоритмы и Scratch',en:'Algorithms & Scratch'},
  desc:{de:'Schritt für Schritt denken wie ein Programmierer',ru:'Думай пошагово, как программист',en:'Think step by step like a programmer'},
  qs:[
    {t:'mc', q:'Was ist ein Algorithmus?', tr:{ru:'Что такое алгоритм?',en:'What is an algorithm?'},
      opts:['eine Schritt-für-Schritt-Anleitung','ein Computerspiel','ein Passwort'], a:0, h:'infoScratch', pts:1},
    {t:'mc', q:'Was ist im Alltag wie ein Algorithmus?', tr:{ru:'Что в жизни похоже на алгоритм?',en:'What in everyday life is like an algorithm?'},
      opts:['ein Kochrezept','ein Gemälde','ein Lied'], a:0, h:'infoScratch', pts:1},
    {t:'mc', q:'Womit programmiert man in Scratch?', tr:{ru:'Чем программируют в Scratch?',en:'What do you program with in Scratch?'},
      opts:['mit bunten Blöcken zum Zusammenstecken','mit langen Textbefehlen','mit Sprachnachrichten'], a:0, h:'infoScratch', pts:1},
    {t:'mc', q:'„Wiederhole 4-mal: [gehe 100 Schritte, drehe dich um 90°]"\nWelche Form läuft die Figur?', tr:{ru:'«Повтори 4 раза: [иди 100 шагов, повернись на 90°]» – какую фигуру нарисует персонаж?',en:'"Repeat 4 times: [move 100 steps, turn 90°]" – which shape does the sprite walk?'},
      opts:['ein Quadrat','einen Kreis','ein Dreieck'], a:0, h:'infoScratch', pts:1},
    {t:'mc', q:'Wie nennt man eine Wiederholung im Programm?', tr:{ru:'Как называется повторение в программе?',en:'What is a repetition in a program called?'},
      opts:['Schleife','Knoten','Sprung'], a:0, h:'infoScratch', pts:1},
    {t:'mc', q:'„WENN die Leertaste gedrückt wird, DANN springt die Figur."\nWie nennt man so einen Baustein?', tr:{ru:'«ЕСЛИ нажат пробел, ТО фигура прыгает» – как называется такой блок?',en:'"IF space is pressed, THEN the sprite jumps." What is this called?'},
      opts:['Bedingung (wenn–dann)','Schleife','Kommentar'], a:0, h:'infoScratch', pts:1},
    {t:'mc', q:'Wie nennt man einen Fehler im Programm?', tr:{ru:'Как называется ошибка в программе?',en:'What is a mistake in a program called?'}, opts:['Bug','Bit','Byte'], a:0, h:'infoScratch', pts:1},
    {t:'num', q:'Ein Programm sagt: „Wiederhole 3-mal: hüpfe 2 Felder vor."\nWie viele Felder kommt die Figur insgesamt voran?', tr:{ru:'Программа: «Повтори 3 раза: прыгни на 2 клетки вперёд». На сколько клеток продвинется фигура?',en:'A program says: "Repeat 3 times: hop 2 squares forward." How many squares in total?'}, a:6, h:'infoScratch', pts:2},
    {t:'mc', q:'Bringe die Schritte in die richtige Reihenfolge: Was kommt beim Zähneputzen ZUERST?', tr:{ru:'Правильный порядок действий: что при чистке зубов идёт ПЕРВЫМ?',en:'Order the steps: what comes FIRST when brushing teeth?'},
      opts:['Zahnpasta auf die Bürste geben','Mund ausspülen','Zähne putzen'], a:0, h:'infoScratch', pts:1},
  ]},

{ id:'i5-daten', grade:5, subject:'info', icon:'📁',
  title:{de:'Dateien, Daten & Binärsystem',ru:'Файлы, данные и двоичная система',en:'Files, Data & Binary'},
  desc:{de:'Ordnung am Computer und die Sprache der Nullen und Einsen',ru:'Порядок в компьютере и язык нулей и единиц',en:'Computer tidiness and the language of 0s and 1s'},
  qs:[
    {t:'mc', q:'Was ist ein ORDNER?', tr:{ru:'Что такое ПАПКА?',en:'What is a FOLDER?'},
      opts:['ein Behälter, der Dateien sortiert','ein Bild vom Computer','ein Programm zum Spielen'], a:0, h:'infoDaten', pts:1},
    {t:'match', q:'Verbinde Dateiendung und Inhalt:', tr:{ru:'Соедини расширение файла и содержимое:',en:'Match file ending and content:'},
      pairs:[['.jpg','Bild'],['.mp3','Musik'],['.mp4','Video'],['.txt','Text']], h:'infoDaten', pts:4},
    {t:'mc', q:'Mit welchen Ziffern rechnet ein Computer?', tr:{ru:'Какими цифрами считает компьютер?',en:'Which digits does a computer calculate with?'},
      opts:['nur mit 0 und 1','mit 0 bis 9','nur mit 1 und 2'], a:0, h:'infoDaten', pts:1},
    {t:'num', q:'Aus wie vielen verschiedenen Ziffern besteht das Binärsystem?', tr:{ru:'Сколько разных цифр в двоичной системе?',en:'How many different digits does the binary system have?'}, a:2, h:'infoDaten', pts:1},
    {t:'mc', q:'Was ist die „Cloud"?', tr:{ru:'Что такое «облако» (Cloud)?',en:'What is the "cloud"?'},
      opts:['Speicherplatz im Internet','eine echte Wolke','ein Computerspiel'], a:0, h:'infoDaten', pts:1},
    {t:'mc', q:'Warum solltest du deine Arbeit regelmäßig SPEICHERN?', tr:{ru:'Почему нужно регулярно СОХРАНЯТЬ работу?',en:'Why should you SAVE your work regularly?'},
      opts:['Damit nichts verloren geht, wenn der Computer ausgeht','Damit der Computer schneller wird','Weil es schön aussieht'], a:0, h:'infoDaten', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Ich darf Fotos von anderen Menschen ohne ihre Erlaubnis ins Internet stellen."', tr:{ru:'Верно ли: можно выкладывать чужие фото в интернет без разрешения?',en:'True or false: I may post photos of other people online without permission?'}, a:false, h:'infoDaten', pts:1},
    {t:'mc', q:'Was bedeutet DATENSCHUTZ?', tr:{ru:'Что значит «защита данных»?',en:'What does DATA PROTECTION mean?'},
      opts:['Persönliche Daten werden geschützt und nicht einfach weitergegeben.','Der Computer wird vor Regen geschützt.','Daten werden immer gelöscht.'], a:0, h:'infoDaten', pts:1},
  ]},
];
