/* ============ SPRACHEN: Englisch (tief) · Französisch · Spanisch · Russisch ============ */
const TESTS_LANG = [

/* ================= ENGLISCH – Vertiefung ================= */
{ id:'e6-prep', grade:6, subject:'english', icon:'📍',
  title:{de:'Prepositions – Ort & Zeit',ru:'Предлоги места и времени',en:'Prepositions – Place & Time'},
  desc:{de:'in, on, under, at, between ...',ru:'in, on, under, at, between ...',en:'in, on, under, at, between ...'},
  qs:[
    {t:'mc', q:'The cat is ___ the table. (auf dem Tisch)', tr:{ru:'Выбери: The cat is ___ the table. (на столе)',en:'Choose: The cat is ___ the table.'}, opts:['on','in','under'], a:0, h:'engPrepositions', pts:1},
    {t:'mc', q:'The ball is ___ the box. (in der Kiste)', tr:{ru:'Выбери: The ball is ___ the box. (в коробке)',en:'Choose: The ball is ___ the box.'}, opts:['in','on','at'], a:0, h:'engPrepositions', pts:1},
    {t:'mc', q:'My school is ___ the park. (neben dem Park)', tr:{ru:'Выбери: My school is ___ the park. (рядом)',en:'Choose: My school is ___ the park.'}, opts:['next to','under','between'], a:0, h:'engPrepositions', pts:1},
    {t:'mc', q:'I get up ___ 7 o’clock.', tr:{ru:'Выбери: I get up ___ 7 o’clock.',en:'Choose: I get up ___ 7 o’clock.'}, opts:['at','on','in'], a:0, h:'engPrepositions', pts:1},
    {t:'mc', q:'We have sports ___ Monday.', tr:{ru:'Выбери: We have sports ___ Monday.',en:'Choose: We have sports ___ Monday.'}, opts:['on','at','in'], a:0, h:'engPrepositions', pts:1},
    {t:'mc', q:'My birthday is ___ May.', tr:{ru:'Выбери: My birthday is ___ May.',en:'Choose: My birthday is ___ May.'}, opts:['in','on','at'], a:0, h:'engPrepositions', pts:1},
    {t:'mc', q:'The shop is ___ the bank and the café. (zwischen)', tr:{ru:'Выбери: между банком и кафе.',en:'Choose: between the bank and the café.'}, opts:['between','behind','in front of'], a:0, h:'engPrepositions', pts:1},
    {t:'match', q:'Verbinde Präposition und Bedeutung:', tr:{ru:'Соедини предлог и значение:',en:'Match preposition and meaning:'},
      pairs:[['under','unter'],['behind','hinter'],['in front of','vor'],['next to','neben']], h:'engPrepositions', pts:4},
  ]},

{ id:'e7-modals', grade:7, subject:'english', icon:'🎯',
  title:{de:'Modalverben',ru:'Модальные глаголы',en:'Modal Verbs'},
  desc:{de:'can, must, may, should, mustn’t',ru:'can, must, may, should, mustn’t',en:'can, must, may, should, mustn’t'},
  qs:[
    {t:'mc', q:'You ___ wear a helmet when you cycle. (Pflicht)', tr:{ru:'Выбери (обязанность): You ___ wear a helmet.',en:'Choose (obligation): You ___ wear a helmet.'}, opts:['must','can','may'], a:0, h:'engModals', pts:1},
    {t:'mc', q:'She ___ speak three languages. (Fähigkeit)', tr:{ru:'Выбери (умение): She ___ speak three languages.',en:'Choose (ability): She ___ speak three languages.'}, opts:['can','must','should'], a:0, h:'engModals', pts:1},
    {t:'mc', q:'You ___ smoke here! (Verbot)', tr:{ru:'Выбери (запрет): You ___ smoke here!',en:'Choose (prohibition): You ___ smoke here!'}, opts:['mustn’t','don’t have to','can'], a:0, h:'engModals', pts:2},
    {t:'mc', q:'It’s Sunday – you ___ get up early. (nicht nötig)', tr:{ru:'Выбери (не обязательно): you ___ get up early.',en:'Choose (not necessary): you ___ get up early.'}, opts:['don’t have to','mustn’t','can’t'], a:0, h:'engModals', pts:2},
    {t:'mc', q:'You ___ do your homework first. (Rat)', tr:{ru:'Выбери (совет): You ___ do your homework first.',en:'Choose (advice): You ___ do your homework first.'}, opts:['should','must not','may not'], a:0, h:'engModals', pts:1},
    {t:'mc', q:'Welcher Satz ist RICHTIG?', tr:{ru:'Какое предложение правильное?',en:'Which sentence is correct?'}, opts:['He can swim.','He cans swim.','He can to swim.'], a:0, h:'engModals', pts:1},
    {t:'mc', q:'___ I open the window, please?', tr:{ru:'Выбери: ___ I open the window, please?',en:'Choose: ___ I open the window, please?'}, opts:['May','Must','Should'], a:0, h:'engModals', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Nach einem Modalverb steht die Grundform ohne to."', tr:{ru:'Верно ли: после модального глагола – начальная форма без to?',en:'True or false: after a modal you use the base form without to?'}, a:true, h:'engModals', pts:1},
  ]},

{ id:'e8-relative', grade:8, subject:'english', icon:'🔗',
  title:{de:'Relative Clauses',ru:'Относительные придаточные',en:'Relative Clauses'},
  desc:{de:'who, which, that, whose',ru:'who, which, that, whose',en:'who, which, that, whose'},
  qs:[
    {t:'mc', q:'The man ___ lives next door is a doctor.', tr:{ru:'Выбери: The man ___ lives next door.',en:'Choose: The man ___ lives next door.'}, opts:['who','which','whose'], a:0, h:'engRelative', pts:1},
    {t:'mc', q:'The book ___ I bought is great.', tr:{ru:'Выбери: The book ___ I bought is great.',en:'Choose: The book ___ I bought is great.'}, opts:['which','who','whose'], a:0, h:'engRelative', pts:1},
    {t:'mc', q:'That’s the girl ___ bike was stolen.', tr:{ru:'Выбери: That’s the girl ___ bike was stolen.',en:'Choose: That’s the girl ___ bike was stolen.'}, opts:['whose','who','which'], a:0, h:'engRelative', pts:1},
    {t:'mc', q:'Welches Wort passt für Personen UND Dinge?', tr:{ru:'Какое слово подходит и для людей, и для вещей?',en:'Which word works for people AND things?'}, opts:['that','who','which'], a:0, h:'engRelative', pts:1},
    {t:'mc', q:'This is the house ___ we lived in.', tr:{ru:'Выбери форму.',en:'Choose the form.'}, opts:['which','who','whose'], a:0, h:'engRelative', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Im notwendigen Relativsatz steht im Englischen ein Komma."', tr:{ru:'Верно ли: в определительном придаточном в английском ставится запятая?',en:'True or false: defining relative clauses take a comma in English?'}, a:false, h:'engRelative', pts:1},
    {t:'mc', q:'The film ___ we watched yesterday was boring.', tr:{ru:'Выбери форму.',en:'Choose the form.'}, opts:['that','who','whose'], a:0, h:'engRelative', pts:1},
    {t:'mc', q:'Do you know the boy ___ won the race?', tr:{ru:'Выбери форму.',en:'Choose the form.'}, opts:['who','which','whose'], a:0, h:'engRelative', pts:1},
  ]},

{ id:'e9-reported', grade:9, subject:'english', icon:'💬',
  title:{de:'Reported Speech',ru:'Косвенная речь',en:'Reported Speech'},
  desc:{de:'Wiedergeben, was jemand gesagt hat',ru:'Передаём чужие слова',en:'Reporting what someone said'},
  qs:[
    {t:'mc', q:'"I am tired." → He said he ___ tired.', tr:{ru:'"I am tired." → He said he ___ tired.',en:'"I am tired." → He said he ___ tired.'}, opts:['was','is','has been'], a:0, h:'engReported', pts:1},
    {t:'mc', q:'"I saw the film." → She said she ___ the film.', tr:{ru:'Выбери форму.',en:'Choose the form.'}, opts:['had seen','saw','has seen'], a:0, h:'engReported', pts:2},
    {t:'mc', q:'"I will call you." → He said he ___ call me.', tr:{ru:'Выбери форму.',en:'Choose the form.'}, opts:['would','will','should'], a:0, h:'engReported', pts:1},
    {t:'mc', q:'"I can swim." → She said she ___ swim.', tr:{ru:'Выбери форму.',en:'Choose the form.'}, opts:['could','can','will'], a:0, h:'engReported', pts:1},
    {t:'mc', q:'"Where do you live?" → He asked where I ___.', tr:{ru:'Выбери форму.',en:'Choose the form.'}, opts:['lived','did live','do live'], a:0, h:'engReported', pts:2},
    {t:'mc', q:'Wie wird aus „today" in der indirekten Rede?', tr:{ru:'Во что превращается „today" в косвенной речи?',en:'What does "today" become?'}, opts:['that day','this day','the day'], a:0, h:'engReported', pts:1},
    {t:'mc', q:'Wie wird aus „tomorrow"?', tr:{ru:'Во что превращается „tomorrow"?',en:'What does "tomorrow" become?'}, opts:['the next day','yesterday','that day'], a:0, h:'engReported', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„In indirekten Fragen benutzt man do/did."', tr:{ru:'Верно ли: в косвенных вопросах используют do/did?',en:'True or false: indirect questions use do/did?'}, a:false, h:'engReported', pts:1},
  ]},

{ id:'e9-writing', grade:9, subject:'english', icon:'✉️',
  title:{de:'Writing: E-Mail & Text',ru:'Письмо на английском',en:'Writing: Email & Text'},
  desc:{de:'Richtig schreiben und formulieren',ru:'Как правильно писать',en:'Writing properly'},
  qs:[
    {t:'mc', q:'Wie beginnst du eine FORMELLE E-Mail?', tr:{ru:'Как начать ФОРМАЛЬНОЕ письмо?',en:'How do you start a FORMAL email?'}, opts:['Dear Sir or Madam,','Hey!','Hi mate,'], a:0, h:'engWriting', pts:1},
    {t:'mc', q:'Wie beendest du eine formelle E-Mail?', tr:{ru:'Как закончить формальное письмо?',en:'How do you end a formal email?'}, opts:['Yours sincerely,','See ya!','Bye bye'], a:0, h:'engWriting', pts:1},
    {t:'mc', q:'Welches Wort verbindet einen GEGENSATZ?', tr:{ru:'Какое слово вводит противопоставление?',en:'Which word shows contrast?'}, opts:['however','because','also'], a:0, h:'engWriting', pts:1},
    {t:'mc', q:'Welches Wort gibt einen GRUND an?', tr:{ru:'Какое слово вводит причину?',en:'Which word gives a reason?'}, opts:['because','however','finally'], a:0, h:'engWriting', pts:1},
    {t:'mc', q:'Wie schreibt man „ich" im Englischen?', tr:{ru:'Как пишется «я» по-английски?',en:'How is "I" written in English?'}, opts:['immer groß: I','immer klein: i'], a:0, noshuffle:true, h:'engWriting', pts:1},
    {t:'mc', q:'Welcher Satz ist richtig?', tr:{ru:'Какое предложение правильное?',en:'Which sentence is correct?'}, opts:['I am looking forward to hearing from you.','I am looking forward to hear from you.','I look forward hear from you.'], a:0, h:'engWriting', pts:1},
    {t:'mc', q:'Wie gliedert man einen guten Text?', tr:{ru:'Как строится хороший текст?',en:'How do you structure a good text?'}, opts:['Einleitung – Hauptteil – Schluss','nur ein langer Absatz','Schluss zuerst'], a:0, h:'engWriting', pts:1},
    {t:'match', q:'Verbinde Verbindungswort und Funktion:', tr:{ru:'Соедини связку и функцию:',en:'Match linker and function:'},
      pairs:[['first','Anfang'],['then','danach'],['finally','zum Schluss'],['so','deshalb']], h:'engWriting', pts:4},
  ]},

{ id:'e8-future', grade:8, subject:'english', icon:'🔮',
  title:{de:'Future: will & going to',ru:'Будущее: will и going to',en:'Future: will & going to'},
  desc:{de:'Pläne, Vorhersagen und Termine',ru:'Планы, прогнозы и встречи',en:'Plans, predictions and arrangements'},
  qs:[
    {t:'mc', q:'Look at those clouds! It ___ rain.', tr:{ru:'Выбери форму (видно по признакам).',en:'Choose (visible evidence).'}, opts:['is going to','will','would'], a:0, h:'engFuture', pts:2},
    {t:'mc', q:'The phone is ringing – I ___ answer it.', tr:{ru:'Выбери (спонтанное решение).',en:'Choose (spontaneous decision).'}, opts:['will','am going to','would'], a:0, h:'engFuture', pts:2},
    {t:'mc', q:'We ___ visit Paris next summer. (schon geplant)', tr:{ru:'Выбери (уже запланировано).',en:'Choose (already planned).'}, opts:['are going to','will','would'], a:0, h:'engFuture', pts:1},
    {t:'mc', q:'I think robots ___ do our homework one day.', tr:{ru:'Выбери (прогноз).',en:'Choose (prediction).'}, opts:['will','are going to','would'], a:0, h:'engFuture', pts:1},
    {t:'mc', q:'I ___ Tom at 5 o’clock. (fester Termin)', tr:{ru:'Выбери (назначенная встреча).',en:'Choose (fixed arrangement).'}, opts:['am meeting','will meet','would meet'], a:0, h:'engFuture', pts:1},
    {t:'mc', q:'Wofür nutzt man „going to"?', tr:{ru:'Для чего используют „going to"?',en:'What is "going to" used for?'}, opts:['für geplante Absichten','für spontane Entscheidungen','für Vergangenheit'], a:0, h:'engFuture', pts:1},
    {t:'mc', q:'I promise I ___ help you.', tr:{ru:'Выбери (обещание).',en:'Choose (promise).'}, opts:['will','am going to','would'], a:0, h:'engFuture', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Nach will steht die Grundform ohne to."', tr:{ru:'Верно ли: после will идёт начальная форма без to?',en:'True or false: after will comes the base form without to?'}, a:true, h:'engFuture', pts:1},
  ]},

/* ================= FRANZÖSISCH ================= */
{ id:'fr6-num', grade:6, subject:'franz', icon:'🔢',
  title:{de:'Zahlen & Wochentage',ru:'Числа и дни недели',en:'Numbers & Weekdays'},
  desc:{de:'Von un bis quatre-vingt-dix',ru:'От un до quatre-vingt-dix',en:'From un to quatre-vingt-dix'},
  qs:[
    {t:'match', q:'Verbinde die Zahlen:', tr:{ru:'Соедини числа:',en:'Match the numbers:'},
      pairs:[['deux','2'],['sept','7'],['neuf','9'],['douze','12']], h:'frNumbers', pts:4},
    {t:'mc', q:'Wie heißt 20 auf Französisch?', tr:{ru:'Как будет 20 по-французски?',en:'What is 20 in French?'}, opts:['vingt','trente','quarante'], a:0, h:'frNumbers', pts:1},
    {t:'mc', q:'Wie heißt 70 auf Französisch?', tr:{ru:'Как будет 70 по-французски?',en:'What is 70 in French?'}, opts:['soixante-dix','septante','sept-dix'], a:0, h:'frNumbers', pts:1},
    {t:'mc', q:'Wie heißt 80 auf Französisch?', tr:{ru:'Как будет 80 по-французски?',en:'What is 80 in French?'}, opts:['quatre-vingts','huitante','octante'], a:0, h:'frNumbers', pts:1},
    {t:'match', q:'Verbinde die Wochentage:', tr:{ru:'Соедини дни недели:',en:'Match the weekdays:'},
      pairs:[['lundi','Montag'],['mercredi','Mittwoch'],['vendredi','Freitag'],['dimanche','Sonntag']], h:'frNumbers', pts:4},
    {t:'mc', q:'Welcher Tag ist „mardi"?', tr:{ru:'Какой день „mardi"?',en:'Which day is "mardi"?'}, opts:['Dienstag','Montag','Donnerstag'], a:0, h:'frNumbers', pts:1},
  ]},

{ id:'fr6-vocab', grade:6, subject:'franz', icon:'🥖',
  title:{de:'Alltagswortschatz',ru:'Повседневные слова',en:'Everyday Vocabulary'},
  desc:{de:'Familie, Schule, Essen, Farben',ru:'Семья, школа, еда, цвета',en:'Family, school, food, colours'},
  qs:[
    {t:'match', q:'Verbinde die Familie:', tr:{ru:'Соедини членов семьи:',en:'Match the family:'},
      pairs:[['la mère','die Mutter'],['le père','der Vater'],['la sœur','die Schwester'],['le frère','der Bruder']], h:'frVocabDaily', pts:4},
    {t:'match', q:'Verbinde die Schulsachen:', tr:{ru:'Соедини школьные вещи:',en:'Match the school things:'},
      pairs:[['le cahier','das Heft'],['le stylo','der Stift'],['le livre','das Buch'],['l’école','die Schule']], h:'frVocabDaily', pts:4},
    {t:'mc', q:'Was bedeutet „le pain"?', tr:{ru:'Что значит „le pain"?',en:'What does "le pain" mean?'}, opts:['das Brot','die Milch','der Apfel'], a:0, h:'frVocabDaily', pts:1},
    {t:'mc', q:'Was bedeutet „rouge"?', tr:{ru:'Что значит „rouge"?',en:'What does "rouge" mean?'}, opts:['rot','blau','grün'], a:0, h:'frVocabDaily', pts:1},
    {t:'mc', q:'Was bedeutet „la maison"?', tr:{ru:'Что значит „la maison"?',en:'What does "la maison" mean?'}, opts:['das Haus','die Straße','der Garten'], a:0, h:'frVocabDaily', pts:1},
    {t:'mc', q:'Wie heißt „das Wasser" auf Französisch?', tr:{ru:'Как «вода» по-французски?',en:'How do you say "water" in French?'}, opts:['l’eau','le lait','le jus'], a:0, h:'frVocabDaily', pts:1},
  ]},

{ id:'fr7-adj', grade:7, subject:'franz', icon:'🌈',
  title:{de:'Adjektive im Französischen',ru:'Прилагательные',en:'French Adjectives'},
  desc:{de:'Stellung und Angleichung',ru:'Место и согласование',en:'Position and agreement'},
  qs:[
    {t:'mc', q:'Wo steht das Adjektiv meistens?', tr:{ru:'Где обычно стоит прилагательное?',en:'Where does the adjective usually go?'}, opts:['nach dem Nomen','vor dem Nomen','am Satzende'], a:0, h:'frAdjectives', pts:1},
    {t:'mc', q:'Wie heißt die weibliche Form von „petit"?', tr:{ru:'Женская форма „petit"?',en:'Feminine form of "petit"?'}, opts:['petite','petits','petit'], a:0, h:'frAdjectives', pts:1},
    {t:'mc', q:'Welches Adjektiv steht VOR dem Nomen?', tr:{ru:'Какое прилагательное стоит ПЕРЕД существительным?',en:'Which adjective goes BEFORE the noun?'}, opts:['grand','rouge','intéressant'], a:0, h:'frAdjectives', pts:1},
    {t:'mc', q:'„eine rote Tür" heißt:', tr:{ru:'«красная дверь» по-французски:',en:'"a red door" in French:'}, opts:['une porte rouge','une rouge porte','un porte rouge'], a:0, h:'frAdjectives', pts:1},
    {t:'mc', q:'Wie bildet man den Plural von Adjektiven meist?', tr:{ru:'Как обычно образуется множественное число прилагательных?',en:'How do you usually form the plural?'}, opts:['mit -s','mit -en','gar nicht'], a:0, h:'frAdjectives', pts:1},
    {t:'mc', q:'„un grand jardin" bedeutet:', tr:{ru:'Что значит „un grand jardin"?',en:'What does "un grand jardin" mean?'}, opts:['ein großer Garten','ein kleiner Garten','ein grüner Garten'], a:0, h:'frAdjectives', pts:1},
  ]},

{ id:'fr8-passe', grade:8, subject:'franz', icon:'⏮️',
  title:{de:'Passé composé',ru:'Passé composé',en:'Passé composé'},
  desc:{de:'Die französische Vergangenheit',ru:'Прошедшее время во французском',en:'The French past tense'},
  qs:[
    {t:'mc', q:'Womit bildet man das Passé composé?', tr:{ru:'С помощью чего образуется passé composé?',en:'How is the passé composé formed?'}, opts:['avoir oder être + participe passé','être + Infinitiv','avoir + Infinitiv'], a:0, h:'frPasse', pts:1},
    {t:'mc', q:'J’___ mangé une pomme.', tr:{ru:'Выбери: J’___ mangé une pomme.',en:'Choose: J’___ mangé une pomme.'}, opts:['ai','suis','es'], a:0, h:'frPasse', pts:1},
    {t:'mc', q:'Je ___ allé à l’école. (gehen = Bewegung!)', tr:{ru:'Выбери: Je ___ allé à l’école.',en:'Choose: Je ___ allé à l’école.'}, opts:['suis','ai','es'], a:0, h:'frPasse', pts:2},
    {t:'text', q:'Participe passé von „parler"?', tr:{ru:'Participe passé глагола „parler"?',en:'Past participle of "parler"?'}, a:['parlé'], h:'frPasse', pts:1},
    {t:'text', q:'Participe passé von „finir"?', tr:{ru:'Participe passé глагола „finir"?',en:'Past participle of "finir"?'}, a:['fini'], h:'frPasse', pts:1},
    {t:'mc', q:'Welches Verb nimmt ÊTRE?', tr:{ru:'Какой глагол требует ÊTRE?',en:'Which verb takes ÊTRE?'}, opts:['aller','manger','parler'], a:0, h:'frPasse', pts:1},
    {t:'mc', q:'Elle est ___ (aller) au cinéma.', tr:{ru:'Выбери форму (женский род!).',en:'Choose (feminine agreement!).'}, opts:['allée','allé','aller'], a:0, h:'frPasse', pts:2},
  ]},

/* ================= SPANISCH ================= */
{ id:'es6-start', grade:6, subject:'spanisch', icon:'🇪🇸',
  title:{de:'¡Hola! Erste Schritte',ru:'¡Hola! Первые шаги',en:'¡Hola! First Steps'},
  desc:{de:'Begrüßung, Zahlen und Artikel',ru:'Приветствия, числа и артикли',en:'Greetings, numbers and articles'},
  qs:[
    {t:'match', q:'Verbinde die Begrüßungen:', tr:{ru:'Соедини приветствия:',en:'Match the greetings:'},
      pairs:[['¡Hola!','Hallo'],['Buenos días','Guten Morgen'],['Adiós','Tschüss'],['Gracias','Danke']], h:'esBasics', pts:4},
    {t:'mc', q:'Wie sagt man „Ich heiße Ali"?', tr:{ru:'Как сказать «Меня зовут Али»?',en:'How do you say "My name is Ali"?'}, opts:['Me llamo Ali.','Yo soy llamo Ali.','Mi nombre llamo Ali.'], a:0, h:'esBasics', pts:1},
    {t:'match', q:'Verbinde die Zahlen:', tr:{ru:'Соедини числа:',en:'Match the numbers:'},
      pairs:[['uno','1'],['tres','3'],['cinco','5'],['diez','10']], h:'esBasics', pts:4},
    {t:'mc', q:'Welcher Artikel ist männlich?', tr:{ru:'Какой артикль мужского рода?',en:'Which article is masculine?'}, opts:['el','la','las'], a:0, h:'esBasics', pts:1},
    {t:'mc', q:'Wie spricht man das „h" in „hola"?', tr:{ru:'Как произносится «h» в „hola"?',en:'How is the "h" in "hola" pronounced?'}, opts:['gar nicht (stumm)','wie ein deutsches h','wie ch'], a:0, h:'esBasics', pts:1},
    {t:'mc', q:'Was bedeutet „por favor"?', tr:{ru:'Что значит „por favor"?',en:'What does "por favor" mean?'}, opts:['bitte','danke','tschüss'], a:0, h:'esBasics', pts:1},
    {t:'mc', q:'„¿Cómo estás?" bedeutet:', tr:{ru:'Что значит „¿Cómo estás?"',en:'What does "¿Cómo estás?" mean?'}, opts:['Wie geht’s?','Wie heißt du?','Wo wohnst du?'], a:0, h:'esBasics', pts:1},
  ]},

{ id:'es6-vocab', grade:6, subject:'spanisch', icon:'🍎',
  title:{de:'Grundwortschatz',ru:'Базовая лексика',en:'Core Vocabulary'},
  desc:{de:'Familie, Schule, Essen, Farben',ru:'Семья, школа, еда, цвета',en:'Family, school, food, colours'},
  qs:[
    {t:'match', q:'Verbinde die Familie:', tr:{ru:'Соедини членов семьи:',en:'Match the family:'},
      pairs:[['la madre','die Mutter'],['el padre','der Vater'],['la hermana','die Schwester'],['el hermano','der Bruder']], h:'esVocab', pts:4},
    {t:'match', q:'Verbinde die Farben:', tr:{ru:'Соедини цвета:',en:'Match the colours:'},
      pairs:[['rojo','rot'],['azul','blau'],['verde','grün'],['negro','schwarz']], h:'esVocab', pts:4},
    {t:'mc', q:'Was bedeutet „el libro"?', tr:{ru:'Что значит „el libro"?',en:'What does "el libro" mean?'}, opts:['das Buch','der Stift','die Schule'], a:0, h:'esVocab', pts:1},
    {t:'mc', q:'Was bedeutet „el agua"?', tr:{ru:'Что значит „el agua"?',en:'What does "el agua" mean?'}, opts:['das Wasser','das Brot','die Milch'], a:0, h:'esVocab', pts:1},
    {t:'mc', q:'Wie heißt „die Schule" auf Spanisch?', tr:{ru:'Как «школа» по-испански?',en:'How do you say "school" in Spanish?'}, opts:['la escuela','la casa','la clase'], a:0, h:'esVocab', pts:1},
    {t:'mc', q:'Was bedeutet „mañana"?', tr:{ru:'Что значит „mañana"?',en:'What does "mañana" mean?'}, opts:['morgen','heute','gestern'], a:0, h:'esVocab', pts:1},
  ]},

{ id:'es7-verbs', grade:7, subject:'spanisch', icon:'🗣️',
  title:{de:'Verben im Präsens',ru:'Глаголы в настоящем времени',en:'Present Tense Verbs'},
  desc:{de:'-ar, -er, -ir und tener',ru:'-ar, -er, -ir и tener',en:'-ar, -er, -ir and tener'},
  qs:[
    {t:'text', q:'Konjugiere: yo ___ (hablar)', tr:{ru:'Проспрягай: yo ___ (hablar)',en:'Conjugate: yo ___ (hablar)'}, a:['hablo'], h:'esVerbs', pts:1},
    {t:'text', q:'Konjugiere: tú ___ (hablar)', tr:{ru:'Проспрягай: tú ___ (hablar)',en:'Conjugate: tú ___ (hablar)'}, a:['hablas'], h:'esVerbs', pts:1},
    {t:'text', q:'Konjugiere: nosotros ___ (comer)', tr:{ru:'Проспрягай: nosotros ___ (comer)',en:'Conjugate: nosotros ___ (comer)'}, a:['comemos'], h:'esVerbs', pts:1},
    {t:'text', q:'Konjugiere: él ___ (vivir)', tr:{ru:'Проспрягай: él ___ (vivir)',en:'Conjugate: él ___ (vivir)'}, a:['vive'], h:'esVerbs', pts:1},
    {t:'mc', q:'Welche drei Verbgruppen gibt es im Spanischen?', tr:{ru:'Какие три группы глаголов в испанском?',en:'Which three verb groups exist in Spanish?'}, opts:['-ar, -er, -ir','-er, -en, -ir','-ar, -or, -ur'], a:0, h:'esVerbs', pts:1},
    {t:'mc', q:'Yo ___ un hermano. (tener = haben)', tr:{ru:'Выбери: Yo ___ un hermano.',en:'Choose: Yo ___ un hermano.'}, opts:['tengo','tienes','tiene'], a:0, h:'esVerbs', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Im Spanischen kann man das Personalpronomen weglassen."', tr:{ru:'Верно ли: в испанском можно опускать местоимение?',en:'True or false: Spanish can drop the personal pronoun?'}, a:true, h:'esVerbs', pts:1},
  ]},

{ id:'es7-ser', grade:7, subject:'spanisch', icon:'⚖️',
  title:{de:'ser oder estar',ru:'ser или estar',en:'ser or estar'},
  desc:{de:'Die zwei Wörter für „sein"',ru:'Два глагола «быть»',en:'The two words for "to be"'},
  qs:[
    {t:'mc', q:'Yo ___ de Alemania. (Herkunft)', tr:{ru:'Выбери (происхождение): Yo ___ de Alemania.',en:'Choose (origin): Yo ___ de Alemania.'}, opts:['soy','estoy','es'], a:0, h:'esSerEstar', pts:1},
    {t:'mc', q:'Yo ___ cansado. (müde – Zustand)', tr:{ru:'Выбери (состояние): Yo ___ cansado.',en:'Choose (state): Yo ___ cansado.'}, opts:['estoy','soy','es'], a:0, h:'esSerEstar', pts:1},
    {t:'mc', q:'Madrid ___ en España. (Ort)', tr:{ru:'Выбери (местоположение): Madrid ___ en España.',en:'Choose (location): Madrid ___ en España.'}, opts:['está','es','son'], a:0, h:'esSerEstar', pts:1},
    {t:'mc', q:'Ella ___ profesora. (Beruf)', tr:{ru:'Выбери (профессия): Ella ___ profesora.',en:'Choose (profession): Ella ___ profesora.'}, opts:['es','está','soy'], a:0, h:'esSerEstar', pts:1},
    {t:'mc', q:'Wofür benutzt man SER?', tr:{ru:'Для чего используют SER?',en:'What is SER used for?'}, opts:['dauerhafte Eigenschaften','vorübergehende Zustände','nur Orte'], a:0, h:'esSerEstar', pts:1},
    {t:'mc', q:'Wofür benutzt man ESTAR?', tr:{ru:'Для чего используют ESTAR?',en:'What is ESTAR used for?'}, opts:['Zustand und Ort','Beruf und Herkunft','nur Zahlen'], a:0, h:'esSerEstar', pts:1},
    {t:'mc', q:'Nosotros ___ estudiantes.', tr:{ru:'Выбери форму.',en:'Choose the form.'}, opts:['somos','estamos','sois'], a:0, h:'esSerEstar', pts:1},
  ]},

/* ================= RUSSISCH ================= */
{ id:'ru5-alpha', grade:5, subject:'russisch', icon:'🔡',
  title:{de:'Das kyrillische Alphabet',ru:'Кириллица',en:'The Cyrillic Alphabet'},
  desc:{de:'Buchstaben lesen und vergleichen',ru:'Читаем и сравниваем буквы',en:'Reading and comparing letters'},
  qs:[
    {t:'num', q:'Wie viele Buchstaben hat das russische Alphabet?', tr:{ru:'Сколько букв в русском алфавите?',en:'How many letters has the Russian alphabet?'}, a:33, h:'ruAlphabet', pts:1},
    {t:'match', q:'Verbinde Buchstabe und Laut:', tr:{ru:'Соедини букву и звук (по-немецки):',en:'Match letter and sound:'},
      pairs:[['В в','w'],['Р р','r'],['С с','s'],['Н н','n']], h:'ruAlphabet', pts:4},
    {t:'mc', q:'Wie klingt der Buchstabe „У у"?', tr:{ru:'Как звучит буква «У у» (по-немецки)?',en:'How does the letter "У у" sound?'}, opts:['u','y','a'], a:0, h:'ruAlphabet', pts:1},
    {t:'mc', q:'Wie klingt „Ж ж"?', tr:{ru:'Как звучит «Ж ж»?',en:'How does "Ж ж" sound?'}, opts:['wie ein weiches sch','wie k','wie t'], a:0, h:'ruAlphabet', pts:1},
    {t:'mc', q:'Welcher Buchstabe sieht aus wie ein lateinisches P, klingt aber wie R?', tr:{ru:'Какая буква похожа на латинскую P, но звучит как Р?',en:'Which letter looks like Latin P but sounds like R?'}, opts:['Р р','П п','Ф ф'], a:0, h:'ruAlphabet', pts:1},
    {t:'mc', q:'Wie klingt „Ч ч"?', tr:{ru:'Как звучит «Ч ч»?',en:'How does "Ч ч" sound?'}, opts:['tsch','sch','ts'], a:0, h:'ruAlphabet', pts:1},
    {t:'mc', q:'Welche Buchstaben haben KEINEN eigenen Laut?', tr:{ru:'Какие буквы не обозначают звука?',en:'Which letters have no sound of their own?'}, opts:['ь und ъ','а und о','м und н'], a:0, h:'ruAlphabet', pts:1},
  ]},

{ id:'ru5-basics', grade:5, subject:'russisch', icon:'👋',
  title:{de:'Erste Wörter & Sätze',ru:'Первые слова и фразы',en:'First Words & Phrases'},
  desc:{de:'Begrüßung, Zahlen und Grundregeln',ru:'Приветствия, числа и правила',en:'Greetings, numbers and basic rules'},
  qs:[
    {t:'match', q:'Verbinde Russisch und Deutsch:', tr:{ru:'Соедини русское и немецкое:',en:'Match Russian and German:'},
      pairs:[['Привет','Hallo'],['Спасибо','Danke'],['Пожалуйста','Bitte'],['Пока','Tschüss']], h:'ruBasics', pts:4},
    {t:'match', q:'Verbinde die Zahlen:', tr:{ru:'Соедини числа:',en:'Match the numbers:'},
      pairs:[['один','1'],['три','3'],['пять','5'],['десять','10']], h:'ruBasics', pts:4},
    {t:'mc', q:'Wie sagt man höflich „Guten Tag"?', tr:{ru:'Как вежливо сказать «Здравствуйте»?',en:'How do you say a polite "Good day"?'}, opts:['Здравствуйте','Привет','Пока'], a:0, h:'ruBasics', pts:1},
    {t:'mc', q:'Was bedeutet „Меня зовут ..."?', tr:{ru:'Что значит «Меня зовут …»?',en:'What does "Меня зовут ..." mean?'}, opts:['Ich heiße ...','Wie geht es dir?','Ich wohne in ...'], a:0, h:'ruBasics', pts:1},
    {t:'tf', q:'Richtig oder falsch?\n„Im Russischen gibt es Artikel wie der, die, das."', tr:{ru:'Верно ли: в русском есть артикли как der, die, das?',en:'True or false: Russian has articles like der/die/das?'}, a:false, h:'ruBasics', pts:1},
    {t:'mc', q:'Wie sagt man „Ich bin Schüler" auf Russisch?', tr:{ru:'Как сказать «Я ученик»?',en:'How do you say "I am a pupil"?'}, opts:['Я ученик.','Я есть ученик.','Я быть ученик.'], a:0, h:'ruBasics', pts:2},
  ]},

{ id:'ru6-vocab', grade:6, subject:'russisch', icon:'📚',
  title:{de:'Grundwortschatz',ru:'Базовая лексика',en:'Core Vocabulary'},
  desc:{de:'Familie, Schule, Essen, Farben',ru:'Семья, школа, еда, цвета',en:'Family, school, food, colours'},
  qs:[
    {t:'match', q:'Verbinde Familie (Russisch ↔ Deutsch):', tr:{ru:'Соедини (русский ↔ немецкий):',en:'Match family words:'},
      pairs:[['мама','die Mutter'],['папа','der Vater'],['брат','der Bruder'],['сестра','die Schwester']], h:'ruVocab', pts:4},
    {t:'match', q:'Verbinde Schulwörter:', tr:{ru:'Соедини школьные слова:',en:'Match school words:'},
      pairs:[['школа','die Schule'],['учитель','der Lehrer'],['книга','das Buch'],['тетрадь','das Heft']], h:'ruVocab', pts:4},
    {t:'mc', q:'Was bedeutet „хлеб"?', tr:{ru:'Что значит «хлеб» по-немецки?',en:'What does "хлеб" mean?'}, opts:['das Brot','die Milch','das Wasser'], a:0, h:'ruVocab', pts:1},
    {t:'mc', q:'Was bedeutet „красный"?', tr:{ru:'Что значит «красный» по-немецки?',en:'What does "красный" mean?'}, opts:['rot','blau','grün'], a:0, h:'ruVocab', pts:1},
    {t:'mc', q:'Wie heißt „heute" auf Russisch?', tr:{ru:'Как «сегодня» будет в этом списке?',en:'Which word means "today"?'}, opts:['сегодня','завтра','вчера'], a:0, h:'ruVocab', pts:1},
    {t:'mc', q:'Warum ist die Betonung im Russischen wichtig?', tr:{ru:'Почему в русском важно ударение?',en:'Why is stress important in Russian?'}, opts:['Sie kann die Bedeutung ändern','Sie ist nur für Gedichte wichtig','Sie ist unwichtig'], a:0, h:'ruVocab', pts:1},
  ]},

{ id:'ru7-verbs', grade:7, subject:'russisch', icon:'🏃',
  title:{de:'Verben & Aspekt',ru:'Глаголы и вид',en:'Verbs & Aspect'},
  desc:{de:'Der größte Unterschied zum Deutschen',ru:'Главное отличие от немецкого',en:'The biggest difference from German'},
  qs:[
    {t:'mc', q:'Wie heißt „ich lese" auf Russisch?', tr:{ru:'Как будет «я читаю»?',en:'How do you say "I read"?'}, opts:['я читаю','я читать','я читал'], a:0, h:'ruVerbs', pts:1},
    {t:'mc', q:'Wie heißt „wir lesen"?', tr:{ru:'Как будет «мы читаем»?',en:'How do you say "we read"?'}, opts:['мы читаем','мы читают','мы читаешь'], a:0, h:'ruVerbs', pts:1},
    {t:'mc', q:'Was ist der ASPEKT im Russischen?', tr:{ru:'Что такое ВИД глагола?',en:'What is verbal ASPECT?'}, opts:['unvollendet (читать) und vollendet (прочитать)','Vergangenheit und Zukunft','männlich und weiblich'], a:0, h:'ruVerbs', pts:2},
    {t:'mc', q:'Welches Verb ist VOLLENDET (fertig gemacht)?', tr:{ru:'Какой глагол совершенного вида?',en:'Which verb is perfective?'}, opts:['прочитать','читать','делать'], a:0, h:'ruVerbs', pts:1},
    {t:'mc', q:'„Она читала" – wer hat gelesen?', tr:{ru:'«Она читала» – кто читал?',en:'"Она читала" – who was reading?'}, opts:['eine Frau/ein Mädchen','ein Mann','mehrere Personen'], a:0, h:'ruVerbs', pts:1},
    {t:'mc', q:'Woran erkennt man im Russischen die Vergangenheit?', tr:{ru:'Как узнать прошедшее время?',en:'How do you recognise the past tense?'}, opts:['an der Endung -л (читал, читала, читали)','am Artikel','an der Wortstellung'], a:0, h:'ruVerbs', pts:1},
  ]},

{ id:'ru8-cases', grade:8, subject:'russisch', icon:'❓',
  title:{de:'Die 6 russischen Fälle',ru:'Шесть падежей',en:'The Six Russian Cases'},
  desc:{de:'Zwei mehr als im Deutschen!',ru:'На два больше, чем в немецком!',en:'Two more than in German!'},
  qs:[
    {t:'num', q:'Wie viele Fälle hat das Russische?', tr:{ru:'Сколько падежей в русском языке?',en:'How many cases does Russian have?'}, a:6, h:'ruCases', pts:1},
    {t:'match', q:'Verbinde Fall und Frage:', tr:{ru:'Соедини падеж и вопрос:',en:'Match case and question:'},
      pairs:[['Именительный','кто? что?'],['Родительный','кого? чего?'],['Дательный','кому? чему?'],['Винительный','кого? что?']], h:'ruCases', pts:4},
    {t:'mc', q:'Welchen Fall gibt es im Russischen, aber NICHT im Deutschen?', tr:{ru:'Какой падеж есть в русском, но нет в немецком?',en:'Which case exists in Russian but not German?'}, opts:['Творительный (Instrumental)','Дательный','Винительный'], a:0, h:'ruCases', pts:2},
    {t:'mc', q:'Mit welchem Fall sagt man „mit dem Buch"?', tr:{ru:'Каким падежом говорят «книгой»?',en:'Which case says "with the book"?'}, opts:['Творительный','Родительный','Предложный'], a:0, h:'ruCases', pts:1},
    {t:'mc', q:'„о книге" – welcher Fall ist das?', tr:{ru:'«о книге» – какой это падеж?',en:'"о книге" – which case?'}, opts:['Предложный','Именительный','Винительный'], a:0, h:'ruCases', pts:1},
    {t:'mc', q:'Wie heißt der 1. Fall (Grundform)?', tr:{ru:'Как называется первый падеж?',en:'What is the first case called?'}, opts:['Именительный','Родительный','Дательный'], a:0, h:'ruCases', pts:1},
  ]},
];
